using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TE2PolishLocalizationNamespace
{
    public static class Cutscenes
    {
        public static readonly Dictionary<string, string> Data = new Dictionary<string, string>
        {
            { "Text.Cutscene.A17.Generic.A", "Złap to!" },
            { "Text.Cutscene.A17.Generic.B", "Chodź tu, ty mały…" },
            { "Text.Cutscene.A17.Generic.C", "Ha! Mamy cię!" },
            { "Text.Cutscene.A17.Generic.D", "Czekaj, co?!" },
            { "Text.Cutscene.A17.Generic.E", "ARRGHHH!" },
            { "Text.Cutscene.A17.Generic.F", "OOOF!" },
            { "Text.Cutscene.A17.Generic.G", "Gdzie jest uciekinier?!" },
            { "Text.Cutscene.A17.Intro.A", "Ach, nasz najnowszy obiekt testowy w końcu dotarł!" },
            { "Text.Cutscene.A17.Intro.B", "Nie sądzę, żebyś mnie słyszał, ale kontynuujmy wycieczkę…" },
            { "Text.Cutscene.A17.Intro.C", "Tutaj odbywa się apel." },
            { "Text.Cutscene.A17.Intro.D", "Tu dostajesz swoje codzienne składniki odżywcze i witaminy." },
            { "Text.Cutscene.A17.Intro.E", "Jeśli czujesz się źle, zawroty głowy lub niski poziom zdrowia – odwiedź naszych genialnych naukowców medycznych." },
            { "Text.Cutscene.A17.Intro.F", "Ludzie lubią pracować za pieniądze, tu możesz tego spróbować." },
            { "Text.Cutscene.A17.Intro.G", "Jeśli czujesz się słabo – to idealne miejsce, by poćwiczyć." },
            { "Text.Cutscene.A17.Intro.H", "Nasi Agenci mają wiele pytań – usiądź i pogadaj z nimi." },
            { "Text.Cutscene.A17.Intro.I", "Na koniec – to twój nowy dom z dala od domu. Mam nadzieję, że ci się spodoba?" },
            { "Text.Cutscene.A17.Intro.J", "Dobrze, możemy wracać do pracy nad tym ustrojstwem…" },
            { "Text.Cutscene.A17.MP.A", "Są pewni, że UFO już nigdy nie poleci…" },
            { "Text.Cutscene.A17.MP.B", "Eee…" },
            { "Text.Cutscene.A17.SP.A", "Nie przypominam sobie, żebym cię dziś widział." },
            { "Text.Cutscene.A17.SP.B", "Potwierdzam. Ja też cię nie widziałem." },
            { "Text.Cutscene.A17.SP.C", "Okej. Jesteś tu tymczasowo?" },
            { "Text.Cutscene.A17.SP.D", "Tak, jestem tymczasowo… czymś." },
            { "Text.Cutscene.A17.SP.E", "Dobrze. Papierkowa robota się zgadza." },
            { "Text.Cutscene.A17.SP.F", "Miłego wieczoru." },
            { "Text.Cutscene.A17.SP.G", "Ciesz się dzisiejszym tlenem!" },
            { "Text.Cutscene.A17.SP.H", "Czekaj, co?" },
            { "Text.Cutscene.A17.SP.I", "To znaczy... na razie!" },
            { "Text.Cutscene.A17.SP.J", "?" },
            { "Text.Cutscene.Boat.Intro.A", "Zepsute zamki to nie powód, żebyś opuszczał celę." },
            { "Text.Cutscene.Boat.Intro.B", "Proszę, nie odchodź..." },
            { "Text.Cutscene.Boat.Intro.C", "Jeśli jeszcze raz cię zobaczę, przekonasz się, że to nie tylko morze będzie dziś wzburzone!" },
            { "Text.Cutscene.Boat.MP.Helicopter.A", "Wysiadaj z helikoptera!" },
            { "Text.Cutscene.Boat.MP.Helicopter.B", "Nie rób mi krzywdy!" },
            { "Text.Cutscene.Boat.MP.Helicopter.C", "Co?" },
            { "Text.Cutscene.Boat.MP.Helicopter.D", "Co do...?" },
            { "Text.Cutscene.Boat.MP.Helicopter.E", "Kto to zatwierdził?!" },
            { "Text.Cutscene.Boat.MP.Helicopter.F", "Dodać 'Nowy helikopter' do listy zakupów." },
            { "Text.Cutscene.Boat.MP.TakeControl.A", "Masz pomysł, jak to prowadzić?" },
            { "Text.Cutscene.Boat.MP.TakeControl.B", "Może to koło coś robi, kapitanie?" },
            { "Text.Cutscene.Boat.MP.TakeControl.C", "Wypływamy stąd, marynarze!" },
            { "Text.Cutscene.Boat.SP.Jetski.A", "Kto to tu zostawił?!" },
            { "Text.Cutscene.Boat.SP.Scuba.A", "Taśma klejąca i kawałek rury... co może pójść nie tak?" },
            { "Text.Cutscene.Boat.SP.Scuba.B", "*Bulgotanie*" },
            { "Text.Cutscene.Dictator.Generic.A", "Myślę, że nazwę szósty dzień tygodnia na swoją cześć." },
            { "Text.Cutscene.Dictator.Generic.B", "Co?" },
            { "Text.Cutscene.Dictator.Generic.C", "Chwała Przywódcy!!" },
            { "Text.Cutscene.Dictator.Generic.D", "NIE PRZERYWAJ MI, GDY MÓWIĘ!" },
            { "Text.Cutscene.Dictator.Generic.E", "Jak mówiłem..." },
            { "Text.Cutscene.Dictator.Generic.F", "Spójrz, Chwalebny Przywódco!" },
            { "Text.Cutscene.Dictator.Generic.G", "Uciekinier na murze!" },
            { "Text.Cutscene.Dictator.Generic.H", "PRZECIEŻ TAM NIC NIE MA?!" },
            { "Text.Cutscene.Dictator.Generic.I", "PRZESTAŃ MI PRZERYWAĆ!" },
            { "Text.Cutscene.Dictator.Generic.J", "JA! JA! JA MÓWIĘ!!" },
            { "Text.Cutscene.Dictator.Generic.K", "JESTEM WASZYM PRZYWÓDCĄ!" },
            { "Text.Cutscene.Dictator.Generic.L", "Ale…" },
            { "Text.Cutscene.Dictator.Generic.M", "CISZA! NIE DAŁEM CI POZWOLENIA NA MÓWIENIE." },
            { "Text.Cutscene.Dictator.Generic.N", "KIEDY JA MÓWIĘ, TY SŁUCHASZ!" },
            { "Text.Cutscene.Dictator.Generic.O", "Dobrze. Kontynuujmy." },
            { "Text.Cutscene.Dictator.Intro.A", "Witamy w najlepszym miejscu do życia na świecie." },
            { "Text.Cutscene.Dictator.Intro.B", "Ręcznie zbudowane, cegła po cegle, przez naszego Chwalebnego Przywódcę." },
            { "Text.Cutscene.Dictator.Intro.C", "Tutaj odbywa się apel." },
            { "Text.Cutscene.Dictator.Intro.D", "W cieniu naszego Chwalebnego Przywódcy." },
            { "Text.Cutscene.Dictator.Intro.E", "Najlepsze posiłki." },
            { "Text.Cutscene.Dictator.Intro.F", "Podawane są tutaj." },
            { "Text.Cutscene.Dictator.Intro.G", "Wszystko to dzięki naszemu Chwalebnemu Przywódcy." },
            { "Text.Cutscene.Dictator.Intro.H", "Każde nieoczekiwane obrażenie…" },
            { "Text.Cutscene.Dictator.Intro.I", "Zostanie naprawione przez najlepszych lekarzy." },
            { "Text.Cutscene.Dictator.Intro.J", "Oczywiście, dzięki naszemu Chwalebnemu Przywódcy." },
            { "Text.Cutscene.Dictator.Intro.K", "Tutaj trenujemy ciało i umysł." },
            { "Text.Cutscene.Dictator.Intro.L", "By być tak silnym jak nasz Chwalebny Przywódca." },
            { "Text.Cutscene.Dictator.Intro.M", "Witaj, odwiedzający." },
            { "Text.Cutscene.Dictator.Intro.N", "Witaj, przyjacielu." },
            { "Text.Cutscene.Dictator.Intro.O", "Za co jesteś wdzięczny?" },
            { "Text.Cutscene.Dictator.Intro.P", "To Centrum Odwiedzin zostało ufundowane przez naszego Chwalebnego Przywódcę." },
            { "Text.Cutscene.Dictator.Intro.Q", "Tutaj dostaniesz pracę." },
            { "Text.Cutscene.Dictator.Intro.R", "Choć my już ją mamy." },
            { "Text.Cutscene.Dictator.Intro.S", "Dzięki naszemu Chwalebnemu Przywódcy." },
            { "Text.Cutscene.Dictator.Intro.T", "W końcu, nasz Chwalebny Przywódca przybył!" },
            { "Text.Cutscene.Dictator.Intro.U", "Nie wolno ci tego oglądać. Wracaj do swojej celi." },
            { "Text.Cutscene.Dictator.MP.A", "Po prostu to weź!" },
            { "Text.Cutscene.Dictator.MP.B", "NIE! TO MOJE!" },
            { "Text.Cutscene.Dictator.MP.C", "AAARRGHHHH!" },
            { "Text.Cutscene.Dictator.MP.D", "PUŚĆ MNIE!!" },
            { "Text.Cutscene.Dictator.MP.E", "Ukradli MÓJ helikopter!" },
            { "Text.Cutscene.Dictator.MP.F", "AAARGHHH!" },
            { "Text.Cutscene.Dictator.MP.G", "NIE NIE NIE NIE!" },
            { "Text.Cutscene.Dictator.SP.A", "Co?" },
            { "Text.Cutscene.Dictator.SP.B", "Nareszcie coś ciekawego się tu dzieje..." },
            { "Text.Cutscene.Dictator.SP.C", "Cóż, to zabiło 20 minut…" },
            { "Text.Cutscene.Gulag.Generic.A", "Żeby złapać tego rzecznego potwora, będę potrzebował odpowiedniej przynęty…" },
            { "Text.Cutscene.Gulag.Generic.B", "Złapałem coś!" },
            { "Text.Cutscene.Gulag.Generic.C", "Co do...?!" },
            { "Text.Cutscene.Gulag.Generic.D", "Wow! Ale tam zimno!" },
            { "Text.Cutscene.Gulag.Generic.E", "Eee..." },
            { "Text.Cutscene.Gulag.Intro.A", "Szybko, wiatr jest lodowaty… i niedźwiedzie. Mnóstwo niedźwiedzi." },
            { "Text.Cutscene.Gulag.Intro.B", "Jedzenie tutaj utrzyma cię w cieple." },
            { "Text.Cutscene.Gulag.Intro.C", "Złaź stamtąd!" },
            { "Text.Cutscene.Gulag.Intro.D", "Personel medyczny postara się jak może, ale niczego nie obiecujemy." },
            { "Text.Cutscene.Gulag.Intro.E", "Tutaj znajdziesz pracę." },
            { "Text.Cutscene.Gulag.Intro.F", "W tym więzieniu." },
            { "Text.Cutscene.Gulag.Intro.G", "Świeże powietrze wypełni twoje płuca…" },
            { "Text.Cutscene.Gulag.Intro.H", "Trening tutaj uczyni cię silnym jak niedźwiedź." },
            { "Text.Cutscene.Gulag.Intro.I", "Jeśli kiedykolwiek pozwolimy na odwiedziny…" },
            { "Text.Cutscene.Gulag.Intro.J", "A jeśli przetrwają zimno i niedźwiedzie…" },
            { "Text.Cutscene.Gulag.Intro.K", "To trafią tutaj." },
            { "Text.Cutscene.Gulag.Intro.L", "I to kończy naszą wycieczkę." },
            { "Text.Cutscene.Gulag.Intro.M", "Jak widzisz, nic się stąd nie wydostaje… ani nic nie wchodzi." },
            { "Text.Cutscene.Gulag.Intro.N", "Niuch, niuch" },
            { "Text.Cutscene.Gulag.MP.A", "Umiesz prowadzić, prawda?" },
            { "Text.Cutscene.Gulag.MP.B", "Tak, tak, tak..." },
            { "Text.Cutscene.Gulag.MP.C", "Zróbmy to! Gaz do dechy!" },
            { "Text.Cutscene.Gulag.MP.D", "Ups!" },
            { "Text.Cutscene.Gulag.MP.E", "HEJ! WRACAĆ TU!" },
            { "Text.Cutscene.Gulag.SP.A", "Dlaczego robię to dzień po wieczorze ze stroganoffem..." },
            { "Text.Cutscene.Gulag.SP.B", "Pachnę jak farma!" },
            { "Text.Cutscene.Gulag.SP.C", "Co do...?" },
            { "Text.Cutscene.Gulag.SP.D", "O mój Boże!" },
            { "Text.Cutscene.Gulag.SP.E", "Zadzwońcie po konserwację! Kanały znowu straszą psy!" },
            { "Text.Cutscene.OWF.Generic.A", "Wracaj tutaj, ty!" },
            { "Text.Cutscene.OWF.Generic.B", "TY wracaj tutaj!" },
            { "Text.Cutscene.OWF.Generic.C", "Jak ci się to podoba?!" },
            { "Text.Cutscene.OWF.Generic.D", "Jak to się dzieje!" },
            { "Text.Cutscene.OWF.Generic.E", "Ooooof!" },
            { "Text.Cutscene.OWF.Intro.A", "Witaj, partnerze, w najbezpieczniejszej fortecy, jaką kiedykolwiek zobaczysz." },
            { "Text.Cutscene.OWF.Intro.B", "Tu odbywa się Apel, pamiętaj, żeby się pojawić!" },
            { "Text.Cutscene.OWF.Intro.C", "Chcesz coś zjeść? Mamy tu wszystkie rodzaje mięsa ptaków, jakie możesz chcieć" },
            { "Text.Cutscene.OWF.Intro.D", "To miejsce, do którego warto przyjść, gdy masz ciężkie czasy" },
            { "Text.Cutscene.OWF.Intro.E", "To są dostępne prace. W końcu możesz tu zarobić uczciwie i dobrze." },
            { "Text.Cutscene.OWF.Intro.F", "Jak widzisz, nasza siłownia jest najwyższej klasy" },
            { "Text.Cutscene.OWF.Intro.G", "Ciekawostka. Całe więzienie stoi na starej, niestabilnej kopalni. Uważaj więc na krok!" },
            { "Text.Cutscene.OWF.MP.A", "Auć!" },
            { "Text.Cutscene.OWF.MP.B", "Hę?" },
            { "Text.Cutscene.OWF.MP.C", "Ten plan śmierdzi. Dosłownie." },
            { "Text.Cutscene.OWF.SP.A", "Weeeeeee!" },
            { "Text.Cutscene.OWF.SP.B", "Wolność!" },
            { "Text.Cutscene.Perks.Generic.A", "Ile mamy taśm?" },
            { "Text.Cutscene.Perks.Generic.B", "Okropieństwo! To strażnicy!" },
            { "Text.Cutscene.Perks.Generic.C", "I..." },
            { "Text.Cutscene.Perks.Generic.D", "AKCJA!" },
            { "Text.Cutscene.Perks.Generic.E", "Hę?" },
            { "Text.Cutscene.Perks.Generic.F", "No weź!" },
            { "Text.Cutscene.Perks.Generic.G", "O, jesteś tutaj!" },
            { "Text.Cutscene.Perks.Intro.A", "Witaj w Center Perks 2.0. Twoja reforma zaczyna się tutaj." },
            { "Text.Cutscene.Perks.Intro.B", "Apel jest obowiązkowy." },
            { "Text.Cutscene.Perks.Intro.C", "Więzienie zostanie zamknięte, jeśli Cię nie będzie." },
            { "Text.Cutscene.Perks.Intro.D", "Jedzenie w naszej stołówce jest doskonałym źródłem zdrowia i energii." },
            { "Text.Cutscene.Perks.Intro.E", "Próby ucieczki będą zgłaszane do centrum kontroli." },
            { "Text.Cutscene.Perks.Intro.F", "Zwiększ swoją inteligencję, czytając nasze książki…" },
            { "Text.Cutscene.Perks.Intro.G", "... i korzystaj z siłowni, aby zwiększyć siłę i szybkość." },
            { "Text.Cutscene.Perks.Intro.H", "Zarób trochę pieniędzy, odwiedzając naszych oficerów pracy." },
            { "Text.Cutscene.Perks.Intro.I", "Przydzielimy Ci jeden z tych pokoi do zamieszkania." },
            { "Text.Cutscene.Perks.Intro.J", "Jak widzisz, mamy ekipę filmową na jakiś czas." },
            { "Text.Cutscene.Perks.Intro.K", "Proszę, nie przerywajcie im nagrywania." },
            { "Text.Cutscene.Perks.MP.A", "*Kaszel*" },
            { "Text.Cutscene.Perks.MP.B", "Ciii!" },
            { "Text.Cutscene.Perks.SP.A", "Ile jeszcze materiału potrzebujemy o tej grupie?" },
            { "Text.Cutscene.Perks.SP.B", "Nie są zbyt dynamiczni…" },
            { "Text.Cutscene.Perks.SP.C", "Powodzenia z dokumentem, frajerzy!" },
            { "Text.Cutscene.Plane.Intro.A", "To była twoja ostatnia ostrzeżenie, więźniu…" },
            { "Text.Cutscene.Plane.Intro.B", "Następnym razem, gdy złapiemy Cię poza celą…" },
            { "Text.Cutscene.Plane.Intro.C", "Nie będziemy tacy mili!" },
            { "Text.Cutscene.Plane.MP.Raft.A", "Włącz przełącznik! Czas się stąd wydostać!" },
            { "Text.Cutscene.Plane.MP.Raft.B", "To całkowicie bezpieczne." },
            { "Text.Cutscene.Plane.MP.TakeControl.A", "Dokąd ustawiamy autopilota?" },
            { "Text.Cutscene.Plane.MP.TakeControl.B", "Gdzieś ciepło i tropikalnie!" },
            { "Text.Cutscene.Plane.MP.TakeControl.C", "Zrozumiano!" },
            { "Text.Cutscene.Plane.MP.TakeControl.D", "Jedziemy!" },
            { "Text.Cutscene.Plane.MP.TakeControl.E", "To… to nie jest tropikalnie?" },
            { "Text.Cutscene.Plane.MP.TakeControl.F", "Wooooo!" },
            { "Text.Cutscene.Plane.MP.TakeControl.G", "Gdzie jest plaża?" },
            { "Text.Cutscene.Plane.SP.Forcelanding.A", "Dalej…" },
            { "Text.Cutscene.Plane.SP.Forcelanding.B", "Po prostu hamuj!" },
            { "Text.Cutscene.Plane.SP.Forcelanding.C", "Jest!" },
            { "Text.Cutscene.Plane.SP.Forcelanding.D", "OSTRZEŻENIE! Natychmiast znajdź bezpieczne miejsce do lądowania." },
            { "Text.Cutscene.Plane.SP.Forcelanding.E", "Zebranie punktów Air Miles poczeka!" },
            { "Text.Cutscene.Plane.SP.Parachute.A", "Ok. Głęboki oddech." },
            { "Text.Cutscene.Plane.SP.Parachute.B", "Teraz powoli wychodzimy z…" },
            { "Text.Cutscene.POW.Generic.A", "Tam!" },
            { "Text.Cutscene.POW.Generic.B", "Stop!" },
            { "Text.Cutscene.POW.Generic.C", "Poczekaj! Ten tutaj…" },
            { "Text.Cutscene.POW.Generic.D", "Hej!" },
            { "Text.Cutscene.POW.Generic.E", "Gdzie jesteś?!" },
            { "Text.Cutscene.POW.Generic.F", "*Jęk*" },
            { "Text.Cutscene.POW.Generic.G", "Hę?" },
            { "Text.Cutscene.POW.Generic.H", "Hehehe!" },
            { "Text.Cutscene.POW.Generic.I", "Łobuz ukradł mój mundur!" },
            { "Text.Cutscene.POW.Intro.A", "Ah, witaj. Więc to ty myślisz, że możesz uciec z KAŻDEGO więzienia. Zobaczymy." },
            { "Text.Cutscene.POW.Intro.B", "Jak w każdym obozie wojskowym, liczenie głów jest regularne i obowiązkowe. MUSISZ pojawić się na Apelu." },
            { "Text.Cutscene.POW.Intro.C", "Posiłki są podawane tutaj, lokalna kuchnia wkrótce Ci się spodoba." },
            { "Text.Cutscene.POW.Intro.D", "Nasza izba chorych działa bardzo wydajnie." },
            { "Text.Cutscene.POW.Intro.E", "Abyś nie czuł się całkowicie bezużyteczny, przydzielimy Ci tu pracę." },
            { "Text.Cutscene.POW.Intro.F", "Kto nie lubi ćwiczyć na świeżym powietrzu?!" },
            { "Text.Cutscene.POW.Intro.G", "Odwiedziny są dozwolone w czasie wolnym… jeśli ktoś chce Cię zobaczyć." },
            { "Text.Cutscene.POW.Intro.H", "Nie wchodź na górę… to nawiedzone!" },
            { "Text.Cutscene.POW.Intro.I", "Nie mogę już tego znieść!" },
            { "Text.Cutscene.POW.MP.A", "Kolejny wspaniały dzień bez prób ucieczki!" },
            { "Text.Cutscene.POW.MP.B", "Zwołaj Dyrektora! Włącz samoloty! Wypuść psy! Weź czołg! Cokolwiek!" },
            { "Text.Cutscene.POW.SP.A", "To jest to. Celuj w rampę." },
            { "Text.Cutscene.POW.SP.B", "Co do…?!" },
            { "Text.Cutscene.POW.SP.C", "AAAAAARRRRRGHHHHH!!!" },
            { "Text.Cutscene.POW.SP.D", "Dyrektor będzie zachwycony!" },
            { "Text.Cutscene.Rig.BlueTug.A", "Nie da się mnie powstrzymać!" },
            { "Text.Cutscene.Rig.Intro.A", "Ahoy! Witaj na pokładzie. Mam nadzieję, że podróż była przyjemna?" },
            { "Text.Cutscene.Rig.Intro.B", "Podejdź tutaj na Apel" },
            { "Text.Cutscene.Rig.Intro.C", "Nie ma nic lepszego niż świeże powietrze, które przenika do kości…" },
            { "Text.Cutscene.Rig.Intro.D", "Tu jemy. Ryby podawane są w poniedziałki, wtorki…" },
            { "Text.Cutscene.Rig.Intro.E", "Środy, czwartki…" },
            { "Text.Cutscene.Rig.Intro.F", "Piątek…" },
            { "Text.Cutscene.Rig.Intro.G", "Soboty, niedziele" },
            { "Text.Cutscene.Rig.Intro.H", "Jeśli czujesz chorobę morską, przyjdź tutaj, żeby postawić stopy na suchym lądzie" },
            { "Text.Cutscene.Rig.Intro.I", "A po naszej prawej jest Biuro Pracy, jeśli chcesz coś robić w wolnym czasie" },
            { "Text.Cutscene.Rig.Intro.J", "Tam jest siłownia, jeśli chcesz się trochę wygadać" },
            { "Text.Cutscene.Rig.Intro.K", "A to są Twoje kajuty, albo jak wolisz je nazywać, cele" },
            { "Text.Cutscene.Rig.Intro.L", "Na koniec, proszę nie przeszkadzać lokalnym delfinom" },
            { "Text.Cutscene.Rig.Intro.M", "Gdy zaczną mówić, nigdy się nie zamykają…" },
            { "Text.Cutscene.Rig.Intro.N", "Klik, Klik" },
            { "Text.Cutscene.Rig.Intro.O", "Gwizd, Gwizd, Gwizd" },
            { "Text.Cutscene.Rig.MP.A", "DIVE! DIVE! DIVE!" },
            { "Text.Cutscene.Rig.MP.B", "Nie widać tego okrętu podwodnego, proszę pana..." },
            { "Text.Cutscene.Rig.RedTug.A", "Uwielbiam mój nowy mały czerwony stateczek!" },
            { "Text.Cutscene.Rig.Snoot.A", "Dobrze. Wykonałem swoją część umowy, teraz twoja kolej…" },
            { "Text.Cutscene.Rig.Snoot.B", "Najlepszy." },
            { "Text.Cutscene.Rig.Snoot.C", "Dzień." },
            { "Text.Cutscene.Rig.Snoot.D", "W historii!" },
            { "Text.Cutscene.Rig.SP.A", "Te worki robią się coraz cięższe…" },
            { "Text.Cutscene.Rig.SP.B", "OOOF!" },
            { "Text.Cutscene.Rig.SP.C", "Mam nadzieję, że będą prysznice, dokąd idziemy…" },
            { "Text.Cutscene.Space.Generic.A", "Gdzie jest przycisk nawigacji satelitarnej?" },
            { "Text.Cutscene.Space.Generic.B", "Może ten?" },
            { "Text.Cutscene.Space.Generic.C", "Ups!" },
            { "Text.Cutscene.Space.Generic.D", "Nie, nie ten…" },
            { "Text.Cutscene.Space.Generic.E", "Gdzie on jest?!" },
            { "Text.Cutscene.Space.Generic.F", "Proszę o legalny zawrót, gdy to możliwe." },
            { "Text.Cutscene.Space.Generic.G", "Wystarczy!" },
            { "Text.Cutscene.Space.Intro.A", "Podejdź, więźniu." },
            { "Text.Cutscene.Space.Intro.B", "Po 70 latach w kriosnie, aby dotrzeć do tego więzienia, możesz rozpocząć 12-miesięczny wyrok." },
            { "Text.Cutscene.Space.Intro.C", "Wszyscy więźniowie muszą uczestniczyć w Apelu." },
            { "Text.Cutscene.Space.Intro.D", "Tutaj wydawane są różne składniki odżywcze." },
            { "Text.Cutscene.Space.Intro.E", "Rozpoczynamy skanowanie smaku." },
            { "Text.Cutscene.Space.Intro.F", "Proszę ograniczyć konsumpcję." },
            { "Text.Cutscene.Space.Intro.G", "Wyniki: 0/10." },
            { "Text.Cutscene.Space.Intro.H", "Odwiedź Infirmarium, jeśli twoje ciało jest uszkodzone." },
            { "Text.Cutscene.Space.Intro.I", "To nie są mechanicy." },
            { "Text.Cutscene.Space.Intro.J", "Zwiększ swoją wydajność korzystając z siłowni." },
            { "Text.Cutscene.Space.Intro.K", "Z kilkoma drobnymi modyfikacjami tutaj…" },
            { "Text.Cutscene.Space.Intro.L", "O nie, proszę, proszę, PRZESTAŃ!" },
            { "Text.Cutscene.Space.Intro.M", "TO JEST ZA SZYBKIE!" },
            { "Text.Cutscene.Space.Intro.N", "Te maszyny przydzielą Ci pracę." },
            { "Text.Cutscene.Space.Intro.O", "Więzień." },
            { "Text.Cutscene.Space.Intro.P", "W przypadku awarii. Proszę skorzystać z dostępnych kapsuł ratunkowych." },
            { "Text.Cutscene.Space.Intro.Q", "Gdy będą gotowe do użycia." },
            { "Text.Cutscene.Space.MP.A", "Już tam jesteśmy?" },
            { "Text.Cutscene.Space.MP.B", "Nie." },
            { "Text.Cutscene.Space.MP.C", "PROSZĘ! PRZESTAŃ PYTAĆ!" },
            { "Text.Cutscene.Space.SP.A", "Nie naciskaj tego…" },
            { "Text.Cutscene.Space.SP.B", "PRZESTAŃ." },
            { "Text.Cutscene.Space.SP.C", "BŁĄD. POMOC. ZADZWOŃ. ADMIN." },
            { "Text.Cutscene.Train.Intro.A", "Jeśli zostaniesz przyłapany poza celą, zostaniesz potraktowany siłą." },
            { "Text.Cutscene.Train.Intro.B", "Zaatakujemy Cię natychmiast, jeśli Cię zobaczymy." },
            { "Text.Cutscene.Train.Intro.C", "Miłej podróży." },
            { "Text.Cutscene.Train.MP.Caboose.A", "To tu, kierunek granica!" },
            { "Text.Cutscene.Train.MP.Caboose.B", "Gdzie jest granica?" },
            { "Text.Cutscene.Train.MP.Caboose.C", "Ehm… po prostu wybierz kierunek i biegnij!" },
            { "Text.Cutscene.Train.MP.TakeControl.A", "Nie mogę w to uwierzyć…" },
            { "Text.Cutscene.Train.MP.TakeControl.B", "LOL!" },
            { "Text.Cutscene.Train.MP.TakeControl.C", "Wszyscy na pokład!" },
            { "Text.Cutscene.Train.SP.Gantry.A", "Gdzie ja jestem?" },
            { "Text.Cutscene.Train.SP.Gantry.B", "Ehm…?" },
            { "Text.Cutscene.Train.SP.Gantry.C", "Cóż. Jest jak jest." },
            { "Text.Cutscene.Train.SP.Horse.A", "Konik!" },
            { "Text.Cutscene.Train.SP.Horse.B", "Chodź tutaj..." },
            { "Text.Cutscene.Train.SP.Horse.C", "Proszę..." },
            { "Text.Cutscene.Train.SP.Horse.D", "To wszystko!" },
            { "Text.Cutscene.Train.SP.Horse.E", "Jak sprawić, żeby koń się zatrzymał?!" },
            { "Text.Cutscene.Train.SP.Horse.F", "Ktoś?!" },
            { "Text.Cutscene.Perks.Intro.L", "Psst!" },
            { "Text.Cutscene.Perks.Intro.M", "Nazywam się Robinson…" },
            { "Text.Cutscene.Perks.Intro.N", "Mam kilka pomysłów, jak uciec z tego miejsca…" },
            { "Text.Cutscene.Perks.Intro.O", "Przyjdź do mnie, jeśli chcesz poznać mój plan" },
            { "Text.Cutscene.Perks.Intro.P", "Decyzja należy do Ciebie" },
            { "Text.Cutscene.Perks.Intro.Q", "Lepiej się zbieraj" },
            { "Text.Cutscene.Intro.A", "Gdzie… gdzie ja jestem?" },
            { "Text.Cutscene.Intro.B", "CO JESTEŚ?!" },
            { "Text.Cutscene.Intro.C", "Jesteś przytomny!" },
            { "Text.Cutscene.Intro.D", "To zaczynamy…" },
            { "Text.Cutscene.Intro.E", "Profesor wybrał Cię jako osobę do eksperymentu." },
            { "Text.Cutscene.Intro.F", "Masz szczęście…" },
            { "Text.Cutscene.Intro.G", "Oczekuje się, że przyjdziesz na apel." },
            { "Text.Cutscene.Intro.H", "Nasi kucharze serwują jedzenie tutaj…" },
            { "Text.Cutscene.Intro.I", "Ale zmarli 90 lat temu, więc ich smak…" },
            { "Text.Cutscene.Intro.J", "Nie istnieje…" },
            { "Text.Cutscene.Intro.K", "Personel naszej izby chorych zna najnowsze technologie…" },
            { "Text.Cutscene.Intro.L", "Wszystko można wyleczyć pijawkami…" },
            { "Text.Cutscene.Intro.M", "Wyglądam dobrze jak na 105 lat, prawda?..." },
            { "Text.Cutscene.Intro.N", "Ale dlaczego ja…" },
            { "Text.Cutscene.Intro.O", "Kontynuujmy…." },
            { "Text.Cutscene.Intro.P", "Mamy siłownię!" },
            { "Text.Cutscene.Intro.Q", "Podobno wy, ciepłokrwiści, lubicie takie rzeczy?" },
            { "Text.Cutscene.Intro.R", "Nasze psy strażnicze to jeden z eksperymentów Profesora…" },
            { "Text.Cutscene.Intro.S", "Łącząc DNA psa z czystą agresją!" },
            { "Text.Cutscene.Intro.T", "Ale to nie ma sensu…" },
            { "Text.Cutscene.Intro.U", "NIE KWESTIONUJ TEGO!" },
            { "Text.Cutscene.Intro.V", "Profesor jest bardzo zajęty…" },
            { "Text.Cutscene.Intro.W", "Musisz trzymać się z dala od jego laboratorium…" },
            { "Text.Cutscene.Intro.X", "Teraz… do celi…" },
            { "Text.Cutscene.Intro.Y", "Ale nie powinienem tu być…" },
            { "Text.Cutscene.Gen.A", "Tym razem mam dobre zdobycze…" },
            { "Text.Cutscene.Gen.B", "Ktoś dał mi oko!" },
            { "Text.Cutscene.Gen.C", "… prawdziwe oko!" },
            { "Text.Cutscene.Gen.D", "To naprawdę kiepski strój, stary…" },
            { "Text.Cutscene.Gen.E", "O nie…" },
            { "Text.Cutscene.Gen.F", "To dopiero jest strój…" },
            { "Text.Cutscene.MP.A", "Mamy prąd!" },
            { "Text.Cutscene.MP.B", "To to…" },
            { "Text.Cutscene.MP.C", "Ożyło!" },
            { "Text.Cutscene.MP.D", "Piorun uderzył w budynek!" },
            { "Text.Cutscene.MP.E", "Idź sprawdzić szkody…" },
            { "Text.Cutscene.MP.F", "Tak, Mistrzu…" },
            { "Text.Cutscene.MP.G", "AAAAAUUUUURRRRRGGHHH" },
            { "Text.Cutscene.MP.H", "CO DO…?!!!" },
            { "Text.Cutscene.MP.I", "AAAAARRGHHH!" },
            { "Text.Cutscene.MP.J", "Wygląda na to, że ktoś zapomniał zamknąć drzwi…" },
            { "Text.Cutscene.SP.A", "Co tu mamy?" },
            { "Text.Cutscene.SP.B", "Musiałem coś przegapić…" },
            { "Text.Cutscene.SP.C", "No to…" },
            { "Text.Cutscene.SP.D", "No proszę! Otwór na klucz…" },
            { "Text.Cutscene.SP.E", "AAARGHHH!" },
            { "Text.Cutscene.SP.F", "Halo?..." },
            { "Text.Cutscene.SP.G", "Szaleniec!" },
            { "Text.IntroCutscene.A", "Powinienem był skończyć na lunch dzisiaj…" },
            { "Text.IntroCutscene.B", "DZIĘKI" },
            { "Text.IntroCutscene.C", "Roll Call odbywa się tutaj" },
            { "Text.IntroCutscene.D", "Nie daj się zwieść słodkim dekoracjom…" },
            { "Text.IntroCutscene.E", "Pokonamy cię, jeśli się nie stawisz" },
            { "Text.IntroCutscene.F", "Rozumiesz?" },
            { "Text.IntroCutscene.G", "Zauważysz sprzęt na siłowni na zewnątrz" },
            { "Text.IntroCutscene.H", "Dyrektor 'przeorganizował' naszą halę sportową…" },
            { "Text.IntroCutscene.I", "To nasza nowoczesna siłownia" },
            { "Text.IntroCutscene.J", "Obecnie nazywana przez dyrektora…" },
            { "Text.IntroCutscene.K", "Teatr" },
            { "Text.IntroCutscene.L", "Dyrektor jest bardzo entuzjastyczny w tym okresie roku…" },
            { "Text.IntroCutscene.M", "Nawet sprowadził producenta do prowadzenia sprawy" },
            { "Text.IntroCutscene.N", "Napisał kiepską historię o mówiącym koniu" },
            { "Text.IntroCutscene.O", "MYŚL! Jak publiczność…" },
            { "Text.IntroCutscene.P", "STAŃ SIĘ PUBLICZNOŚCIĄ" },
            { "Text.IntroCutscene.Q", "To biuro dyrektora…" },
            { "Text.IntroCutscene.R", "Ma naprawdę wygodny salonik" },
            { "Text.IntroCutscene.S", "Mój świąteczny list jest w końcu skończony!" },
            { "Text.IntroCutscene.T", "Na zewnątrz mamy…" },
            { "Text.IntroCutscene.U", "*BZZZZT*" },
            { "Text.IntroCutscene.V", "No proszę, w końcu mogę iść do domu…" },
            { "Text.IntroCutscene.w", "E… cześć?" },
            { "Text.GenericCutscene.A", "Nie mogli daleko uciec!" },
            { "Text.GenericCutscene.B", "Hehehe…" },
            { "Text.MPCutscene.A", "Brawo!" },
            { "Text.MPCutscene.B", "Hura!" },
            { "Text.MPCutscene.C", "To nie było całkiem okropne!" },
            { "Text.MPCutscene.D", "Wracaj!" },
            { "Text.MPCutscene.E", "Jeszcze!" },
            { "Text.MPCutscene.F", "Jeszcze raz!" },
            { "Text.MPCutscene.G", "Co…" },
            { "Text.MPCutscene.H", "Chwila" },
            { "Text.MPCutscene.I", "Gdzie oni poszli?" },
            { "Text.MPCutscene.J", "Szybko! Zablokuj ich!" },
            { "Text.MPCutscene.K", "Na razie!" },
            { "Text.MPCutscene.L", "Ktoś jest?!" },
            { "Text.MPCutscene.M", "Otwórz natychmiast!" },
            { "Text.MPCutscene.N", "Halo?" },
            { "Text.SPCutscene.A", "Ooof!" },
            { "Text.SPCutscene.B", "Niech będzie!" },
            { "Text.SPCutscene.C", "Au!" },
            { "Text.SPCutscene.D", "Nadrabiam to w przyszłym roku, obiecuję…" },
            { "Text.SPCutscene.E", "No to uciekajmy stąd!" },
            { "Text.SPCutscene.F", "Woah!" },
            { "Text.SPCutscene.G", "Powoli!" },
            { "Text.SPCutscene.H", "Hej! Gdzie jest mój prezent?!" },
            { "Text.MPCutscene.O", "Wróć na scenę!" },
            { "Text.MPCutscene.P", "Chcemy więcej!" },
            { "Text.MPCutscene.Q", "Kochamy cię!" },
            { "Text.MPCutscene.R", "Zrób jeszcze raz ten dziwny taniec!" },
            { "Text.MPCutscene.S", "Czy ktoś widział mój portfel?!" },
            { "Text.MPCutscene.T", "Woooo!" },
            { "Text.DLC04.Intro.Cutscene.A", "Witaj!" },
            { "Text.DLC04.Intro.Cutscene.B", "Udało nam się cię wydostać z poprzedniego więzienia…" },
            { "Text.DLC04.Intro.Cutscene.C", "Dostajemy artystę, system więzienny zwalnia celę…" },
            { "Text.DLC04.Intro.Cutscene.D", "Każdy wygrywa!" },
            { "Text.DLC04.Intro.Cutscene.E", "Spędziłem lata rozwijając Cirque Du Catastrophe…" },
            { "Text.DLC04.Intro.Cutscene.F", "W najlepszy wędrowny cyrk!" },
            { "Text.DLC04.Intro.Cutscene.G", "Wykorzystując nadwyżki systemu więziennego…" },
            { "Text.DLC04.Intro.Cutscene.H", "Aby utrzymać publiczność w rozrywce!" },
            { "Text.DLC04.Intro.Cutscene.I", "Co oczywiście oznacza…" },
            { "Text.DLC04.Intro.Cutscene.J", "BĘDZIESZ musiał występować tutaj…" },
            { "Text.DLC04.Intro.Cutscene.K", "Każdej nocy." },
            { "Text.DLC04.Intro.Cutscene.V", "Och, brawo!" },
            { "Text.DLC04.Intro.Cutscene.W", "Poproś o moją zgodę następnym razem!" },
            { "Text.DLC04.Intro.Cutscene.L", "Dbamy o jakość naszych artystów" },
            { "Text.DLC04.Intro.Cutscene.M", "Eee…" },
            { "Text.DLC04.Intro.Cutscene.X", "Chcesz zobaczyć słonia?" },
            { "Text.DLC04.Intro.Cutscene.N", "Bardzo dbam o wszystkie moje zwierzęta" },
            { "Text.DLC04.Intro.Cutscene.O", "Ufaj mi, że nie będziesz ich niepokoić" },
            { "Text.DLC04.Intro.Cutscene.P", "Nasz kontrakt nakazuje ci wciąż przestrzegać rutyn…" },
            { "Text.DLC04.Intro.Cutscene.Q", "Apel, posiłki, kąpiele… itd. itd." },
            { "Text.DLC04.Intro.Cutscene.R", "Zanim zapytasz…" },
            { "Text.DLC04.Intro.Cutscene.S", "Nie. Jest zepsute…" },
            { "Text.DLC04.Intro.Cutscene.T", "Nie mogliśmy go wystrzelić od tygodni" },
            { "Text.DLC04.Intro.Cutscene.U", "Lepiej się wyśpij, niebawem czas na pokaz…" },
            { "Text.DLC04.Generic.Cutscene.A", "Muszę znaleźć drogę ucieczki…" },
            { "Text.DLC04.Generic.Cutscene.B", "Dalej!" },
            { "Text.DLC04.Generic.Cutscene.C", "Wow… idealnie…" },
            { "Text.DLC04.SP.Cutscene.A", "Muszę tylko założyć mój Kokosowy Hełm…" },
            { "Text.DLC04.SP.Cutscene.B", "Bezpieczeństwo przede wszystkim!" },
            { "Text.DLC04.SP.Cutscene.C", "AAAAARRRGHHHH!" },
            { "Text.DLC04.SP.Cutscene.D", "JAK DOTĄD…" },
            { "Text.DLC04.SP.Cutscene.E", "TAK DOBRZE…" },
            { "Text.DLC04.SP.Cutscene.F", "Ouch!" },
            { "Text.DLC04.SP.Cutscene.G", "Ufff, dobrze, że wylądowało na…" },
            { "Text.DLC04.SP.Cutscene.H", "wolność, aby teraz biec do…" },
            { "Text.DLC04.MP.Cutscene.A", "Czas na twój popis, mechaniczna myszko!" },
            { "Text.DLC04.MP.Cutscene.B", "Wiesz co?" },
            { "Text.DLC04.MP.Cutscene.C", "To najlepsza naprawa, jaką kiedykolwiek wykonałem" },
            { "Text.DLC04.MP.Cutscene.D", "Jakość…" },
            { "Text.DLC04.MP.Cutscene.E", "Będę musiał zrobić zdjęcie tego…" },
            { "Text.DLC04.MP.Cutscene.F", "To po prostu perfekcja" },
            { "Text.DLC04.MP.Cutscene.G", "Absolutnie perfekcyjne" },
            { "Text.DLC04.MP.Cutscene.H", "Ten kawałek ściany" },
            { "Text.DLC04.MP.Cutscene.I", "Dokładnie tam…" },
            { "Text.DLC04.MP.Cutscene.J", "Jestem z tego taki dumny…" },
            { "Text.DLC04.MP.Cutscene.K", "No dobrze, czas na herbatkę!" },
            { "Text.DLC04.MP.Cutscene.L", "HURA!" },
            { "Text.DLC05.Cutscene.Intro.A", "Dzień dobry" },
            { "Text.DLC05.Cutscene.Intro.B", "Mam nadzieję, że lubisz dramaty historyczne…" },
            { "Text.DLC05.Cutscene.Intro.C", "Bo właśnie w takim się znajdziesz." },
            { "Text.DLC05.Cutscene.Intro.D", "Witaj w Zamku Locke!" },
            { "Text.DLC05.Cutscene.Intro.E", "Otoczony martwą fosą," },
            { "Text.DLC05.Cutscene.Intro.F", "I grubymi kamiennymi murami," },
            { "Text.DLC05.Cutscene.Intro.G", "Stąd nie uciekniesz…" },
            { "Text.DLC05.Cutscene.Intro.H", "Budowla i jej zawartość są bardzo stare." },
            { "Text.DLC05.Cutscene.Intro.I", "Traktuj je z szacunkiem!" },
            { "Text.DLC05.Cutscene.Intro.J", "Bywałeś już za kratami…" },
            { "Text.DLC05.Cutscene.Intro.K", "Więc wiesz, żeby stawić się na Apelu…" },
            { "Text.DLC05.Cutscene.Intro.L", "Albo oberwiesz" },
            { "Text.DLC05.Cutscene.Intro.M", "Posiłki będą w Wielkiej Sali." },
            { "Text.DLC05.Cutscene.Intro.N", "Ale na rozkaz Nadzorcy…" },
            { "Text.DLC05.Cutscene.Intro.O", "Zabezpieczyliśmy 'wytworne talerze'." },
            { "Text.DLC05.Cutscene.Intro.P", "Siłownia powinna cię zająć:" },
            { "Text.DLC05.Cutscene.Intro.Q", "Zdrowe ciało, zdrowy umysł…" },
            { "Text.DLC05.Cutscene.Intro.R", "Jeśli lubisz takie rzeczy." },
            { "Text.DLC05.Cutscene.Intro.S", "Niektóre części zamku są trochę…" },
            { "Text.DLC05.Cutscene.Intro.T", "nadgryzione zębem czasu." },
            { "Text.DLC05.Cutscene.Intro.U", "Więc bądź ostrożny." },
            { "Text.DLC05.Cutscene.Intro.V", "Dobrze, koniec zwiedzania." },
            { "Text.DLC05.Cutscene.Intro.W", "Do swojej celi" },
            { "Text.DLC05.Cutscene.Intro.X", "Zamknij zwodzony most!" },
            { "Text.DLC05.Cutscene.SPEscape.A", "Panie i Panowie!" },
            { "Text.DLC05.Cutscene.SPEscape.B", "Dziękujemy za przybycie na to spotkanie." },
            { "Text.DLC05.Cutscene.SPEscape.C", "Dotyczące finansowej czarnej dziury, w którą wpadliśmy…" },
            { "Text.DLC05.Cutscene.SPEscape.D", "Och… nie powinienem tego czytać." },
            { "Text.DLC05.Cutscene.SPEscape.E", "Wszystko w porządku, naprawdę…" },
            { "Text.DLC05.Cutscene.SPEscape.F", "Zaczynajmy!" },
            { "Text.DLC05.Cutscene.SPEscape.G", "Darmowe lunche od poniedziałku już nie będą serwowane." },
            { "Text.DLC05.Cutscene.SPEscape.H", "No weź…" },
            { "Text.DLC05.Cutscene.SPEscape.I", "Co…" },
            { "Text.DLC05.Cutscene.SPEscape.J", "*westchnienie*" },
            { "Text.DLC05.Cutscene.SPEscape.K", "Huh?..." },
            { "Text.DLC05.Cutscene.SPEscape.L", "Walczysz siłą wielu mężczyzn, rycerzu." },
            { "Text.DLC05.Cutscene.SPEscape.M", "Jestem pewien, że dojdziemy do porozumienia…" },
            { "Text.DLC05.Cutscene.SPEscape.N", "Ehm… do zobaczenia, dzielny rycerzu!" },
            { "Text.DLC05.Cutscene.SPEscape.O", "Ojej…" },
            { "Text.DLC05.Cutscene.SPEscape.P", "Kto pokona… to." },
            { "Text.DLC05.Cutscene.SPEscape.Q", "Zachowa swoją przepustkę na darmowy lunch." },
            { "Text.DLC05.Cutscene.SPEscape.R", "Jeśli ktoś zapyta…" },
            { "Text.DLC05.Cutscene.SPEscape.S", "Starałem się bardziej, ok?" },
            { "Text.DLC05.Cutscene.DYNEscape.A", "Cóż, to miłe… " },
            { "Text.DLC05.Cutscene.DYNEscape.B", "Udało się!" },
            { "Text.DLC05.Cutscene.DYNEscape.C", "Jak ci się podoba, hm?!" },
            { "Text.DLC05.Cutscene.DYNEscape.D", "UCIEKAJ!" },
            { "Text.DLC05.Cutscene.GENEscape.A", "Ok, więc zachowujemy się w charakterze, zgoda?" },
            { "Text.DLC05.Cutscene.GENEscape.B", "Tylko język i przedmioty z epoki." },
            { "Text.DLC05.Cutscene.GENEscape.C", "Dołączamy do siebie nawzajem ponownie." },
            { "Text.DLC05.Cutscene.GENEscape.D", "Wzywam cię do pojedynku!" },
            { "Text.DLC05.Cutscene.GENEscape.E", "Och, jesteś słabym przeciwnikiem!" },
            { "Text.DLC05.Cutscene.GENEscape.F", "Huh?.." },
            { "Text.DLC05.Cutscene.GENEscape.G", "Aaaarghhh!" },
            { "Text.DLC05.Cutscene.GENEscape.H", "Co do…?!" },
            { "Text.DLC05.Cutscene.GENEscape.I", "Metalowy koń przez las się przebija?!" },
            { "Text.DLC05.Cutscene.GENEscape.J", "Och, odpuść…" },
            { "Text.DLC05.Cutscene.MPEscape.A", "Czy wszyscy gotowi?" },
            { "Text.DLC05.Cutscene.MPEscape.B", "Nie zapomnijcie, że sami to zbudowaliśmy…" },
            { "Text.DLC05.Cutscene.MPEscape.C", "Więc prawdopodobnie nie będzie zbyt potężne…" },
            { "Text.DLC05.Cutscene.MPEscape.D", "Co do…" },
            { "Text.DLC05.Cutscene.MPEscape.E", "Jak ci się udało wyjść?!" },
            { "Text.DLC05.Cutscene.MPEscape.F", "Ooof!" },
            { "Text.DLC05.Cutscene.MPEscape.G", "Może chcesz zejść z drogi…" },
            { "Text.DLC05.Cutscene.MPEscape.H", "AARGHH!" },
            { "Text.DLC05.Cutscene.MPEscape.I", "Nie szkodzi…" },
            { "Text.DLC05.Cutscene.MPEscape.J", "Wiesz co, weź to…." }
        };
    }
}
