using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TE2PolishLocalizationNamespace
{
    public static class Editor
    {
        public static readonly Dictionary<string, string> Data = new Dictionary<string, string>
        {
            { "Text.Editor.MyPrisons", "MOJE WIĘZIENIA" },
            { "Text.Editor.Subscribed", "SUBSKRYBOWANE" },
            { "Text.Editor.BrowseGames", "PRZEGLĄDAJ GRY" },
            { "Text.Editor.SteamWorkshop", "STEAM WORKSHOP" },
            { "Text.Editor.SubscribedInfo", "Tutaj znajdziesz wszystkie więzienia, które subskrybowałeś w Steam Workshop." },
            { "Text.Editor.BrowseGamesInfo", "Przeglądaj wszystkie hostowane niestandardowe więzienia. Dołączaj do gier i graj z innymi graczami." },
            { "Text.Editor.SteamWorkshopInfo", "Uzyskaj dostęp do całej zawartości społeczności i subskrybuj tworzenia innych graczy!" },
            { "Text.Editor.CustomPrisons", "NIESTANDARDOWE WIĘZIENIA" },
            { "Text.Editor.CreatePrison", "STWÓRZ WIĘZIENIE" },
            { "Text.Editor.Delete", "USUŃ" },
            { "Text.Editor.Publishing", "PUBLIKOWANIE" },
            { "Text.Editor.EditPrison", "EDYTUJ WIĘZIENIE" },
            { "Text.Editor.PrisonTools", "NARZĘDZIA WIĘZIENNE" },
            { "Text.Editor.MyPrisonsDescription", "Twórz, udostępniaj, hostuj i graj w swoje więzienia zarówno lokalnie, jak i online!" },
            { "Text.Editor.SubscribedDescription", "Graj w swoje subskrybowane więzienia zarówno lokalnie, jak i online." },
            { "Text.Editor.CustomPrisonsDescription", "Twórz, udostępniaj, hostuj, subskrybuj i graj w niestandardowe więzienia przez Steam Workshop." },
            { "Text.Editor.Presence.FrontEndGeneral", "Myślę nad budową więzienia." },
            { "Text.Editor.GrassTile.Name", "Trawa" },
            { "Text.Editor.PathTile.Name", "Ścieżka" },
            { "Text.Editor.WaterTile.Name", "Woda" },
            { "Text.Editor.RoofTile.Name", "Dach" },
            { "Text.Editor.WallTile.Name", "Ściana" },
            { "Text.Editor.FenceTile.Name", "Płot" },
            { "Text.Editor.WindowsTile.Name", "Okno" },
            { "Text.Editor.CellBarsTile.Name", "Krata celi" },
            { "Text.Editor.FakeStepsTile.Name", "Schody" },
            { "Text.Editor.GlassWallTile.Name", "Szklana ściana" },
            { "Text.Editor.GuardTowerTile.Name", "Wieża strażnicza" },
            { "Text.Editor.CorridorTile.Name", "Korytarz" },
            { "Text.Editor.ConcreteTile.Name", "Beton" },
            { "Text.Editor.RedCheckTile.Name", "Czerwona szachownica" },
            { "Text.Editor.WoodTile.Name", "Drewniana" },
            { "Text.Editor.BlueCheckTile.Name", "Niebieska szachownica" },
            { "Text.Editor.YellowCheckTile.Name", "Żółta szachownica" },
            { "Text.Editor.GreenCheckTile.Name", "Zielona szachownica" },
            { "Text.Editor.GratingTile.Name", "Kratka" },
            { "Text.Editor.ShowersTile.Name", "Łazienka" },
            { "Text.Editor.VentTile.Name", "Wentylacja" },
            { "Text.Editor.DirtTile.Name", "Brud" },
            { "Text.Editor.GrassTile.Desc", "Soczysta, zielona pasza dla krów. " },
            { "Text.Editor.PathTile.Desc", "Idę samotną drogą." },
            { "Text.Editor.WaterTile.Desc", "Uniemożliwia więźniom zbyt daleki wypad." },
            { "Text.Editor.RoofTile.Desc", "Pokrycie dla Twojego więzienia." },
            { "Text.Editor.WallTile.Desc", "Podstawowy blok budowlany. Może być uszkodzony przez narzędzia do dłutowania." },
            { "Text.Editor.FenceTile.Desc", "Jak ściana, ale bardziej krucha. Może być uszkodzona przez narzędzia tnące." },
            { "Text.Editor.WindowsTile.Desc", "Okno i ściana w jednym." },
            { "Text.Editor.CellBarsTile.Desc", "Nie da się z tym negocjować… ani zniszczyć, ale można przykryć prześcieradłami."},
            { "Text.Editor.FakeStepsTile.Desc", "Uważaj na schody." },
            { "Text.Editor.GlassWallTile.Desc", "Przezroczyste, więc uważaj co robisz. Nie śpiewaj też zbyt głośno."},
            { "Text.Editor.GuardTowerTile.Desc", "Ci goście strzelają do nieposłusznych więźniów. Trzymaj się z dala od świateł w nocy."},
            { "Text.Editor.CorridorTile.Desc", "Tania płytka podłogowa do codziennego użytku."},
            { "Text.Editor.ConcreteTile.Desc", "Trwały materiał, który nie wygra żadnych nagród estetycznych."},
            { "Text.Editor.RedCheckTile.Desc", "Płytka podłogowa w szaro-czerwony wzór."},
            { "Text.Editor.WoodTile.Desc", "Jak drzewo, ale płaskie. Naprawdę płaskie."},
            { "Text.Editor.BlueCheckTile.Desc", "Płytka w szaro-niebieski wzór."},
            { "Text.Editor.YellowCheckTile.Desc", "Ułożenie płytek w żółto-szarym kolorze."},
            { "Text.Editor.GreenCheckTile.Desc", "Płytka w zielono-szarym kolorze."},
            { "Text.Editor.GratingTile.Desc", "Metalowa podłoga. Wygląda jak kratka."},
            { "Text.Editor.ShowersTile.Desc", "Najlepiej używać w wilgotnych warunkach."},
            { "Text.Editor.VentTile.Desc", "Do systemów wentylacyjnych. Pewnie."},
            { "Text.Editor.DirtTile.Desc", "Źle utrzymana powierzchnia na zewnątrz."},
            { "Text.Editor.Door_H.Name", "Drzwi" },
            { "Text.Editor.Door_H_Cyan.Name", "Cyjanowe drzwi" },
            { "Text.Editor.Door_H_Green.Name", "Zielone drzwi" },
            { "Text.Editor.Door_H_Guard.Name", "Drzwi do pokoju kontrabandy" },
            { "Text.Editor.Door_H_Medic.Name", "Drzwi do zapasów infirmerii" },
            { "Text.Editor.Door_H_Purple.Name", "Fioletowe drzwi" },
            { "Text.Editor.Door_H_Red.Name", "Czerwone drzwi" },
            { "Text.Editor.Door_H_Solitary.Name", "Drzwi do izolacji" },
            { "Text.Editor.Door_H_Yellow.Name", "Żółte drzwi" },
            { "Text.Editor.Door_V.Name", "Drzwi" },
            { "Text.Editor.Door_V_Cyan.Name", "Cyjanowe drzwi" },
            { "Text.Editor.Door_V_Green.Name", "Zielone drzwi" },
            { "Text.Editor.Door_V_Guard.Name", "Drzwi do pokoju kontrabandy" },
            { "Text.Editor.Door_V_Medic.Name", "Drzwi do zapasów infirmerii" },
            { "Text.Editor.Door_V_Purple.Name", "Fioletowe drzwi" },
            { "Text.Editor.Door_V_Red.Name", "Czerwone drzwi" },
            { "Text.Editor.Door_V_Solitary.Name", "Drzwi do izolacji" },
            { "Text.Editor.Door_V_Yellow.Name", "Żółte drzwi" },
            { "Text.Editor.DoubleDoor_H.Name", "Podwójne drzwi" },
            { "Text.Editor.DoubleDoor_H_Cyan.Name", "Podwójne cyjanowe drzwi" },
            { "Text.Editor.DoubleDoor_H_Green.Name", "Podwójne zielone drzwi" },
            { "Text.Editor.DoubleDoor_H_Purple.Name", "Podwójne fioletowe drzwi" },
            { "Text.Editor.DoubleDoor_H_Red.Name", "Podwójne czerwone drzwi" },
            { "Text.Editor.DoubleDoor_V.Name", "Podwójne drzwi" },
            { "Text.Editor.DoubleDoor_V_Cyan.Name", "Podwójne cyjanowe drzwi" },
            { "Text.Editor.DoubleDoor_V_Green.Name", "Podwójne zielone drzwi" },
            { "Text.Editor.DoubleDoor_V_Purple.Name", "Podwójne fioletowe drzwi" },
            { "Text.Editor.DoubleDoor_V_Red.Name", "Podwójne czerwone drzwi" },
            { "Text.Editor.Door_H.Desc", "Zwykłe więzienne drzwi." },
            { "Text.Editor.Door_H_Cyan.Desc", "Drzwi na klucz w kolorze cyjanowym. Wykończone w Solitary Cyan." },
            { "Text.Editor.Door_H_Green.Desc", "Drzwi na klucz w kolorze zielonym. Wykończone w Gallows Green." },
            { "Text.Editor.Door_H_Guard.Desc", "Tylko dla personelu (strażnicy)." },
            { "Text.Editor.Door_H_Medic.Desc", "Tylko dla personelu (medycy)." },
            { "Text.Editor.Door_H_Purple.Desc", "Drzwi dostępne dla wszystkich, zamykane podczas Lights Out. Wykończone w Prisoner Purple." },
            { "Text.Editor.Door_H_Red.Desc", "Drzwi na klucz w kolorze czerwonym. Wykończone w Rapsheet Red." },
            { "Text.Editor.Door_H_Solitary.Desc", "Drzwi zwykle znajdują się w bloku izolacyjnym." },
            { "Text.Editor.Door_H_Yellow.Desc", "Ulubione drzwi więźniów. Zamykane podczas Lights Out. Wykończone w Prison-Yard Yellow." },
            { "Text.Editor.Door_V.Desc", "Zwykłe więzienne drzwi." },
            { "Text.Editor.Door_V_Cyan.Desc", "Drzwi na klucz w kolorze cyjanowym. Wykończone w Solitary Cyan." },
            { "Text.Editor.Door_V_Green.Desc", "Drzwi na klucz w kolorze zielonym. Wykończone w Gallows Green." },
            { "Text.Editor.Door_V_Guard.Desc", "Tylko dla personelu (strażnicy)." },
            { "Text.Editor.Door_V_Medic.Desc", "Tylko dla personelu (medycy)." },
            { "Text.Editor.Door_V_Purple.Desc", "Drzwi dostępne dla wszystkich, zamykane podczas Lights Out. Wykończone w Prisoner Purple." },
            { "Text.Editor.Door_V_Red.Desc", "Drzwi na klucz w kolorze czerwonym. Wykończone w Rapsheet Red." },
            { "Text.Editor.Door_V_Solitary.Desc", "Drzwi zwykle znajdują się w bloku izolacyjnym." },
            { "Text.Editor.Door_V_Yellow.Desc", "Ulubione drzwi więźniów. Zamykane podczas Lights Out. Wykończone w Prison-Yard Yellow." },
            { "Text.Editor.DoubleDoor_H.Desc", "Zestaw zwykłych podwójnych drzwi." },
            { "Text.Editor.DoubleDoor_H_Cyan.Desc", "Podwójne drzwi na klucz w kolorze cyjanowym. Wykończone w Solitary Cyan." },
            { "Text.Editor.DoubleDoor_H_Green.Desc", "Podwójne drzwi na klucz w kolorze zielonym. Wykończone w Gallows Green." },
            { "Text.Editor.DoubleDoor_H_Red.Desc", "Podwójne drzwi na klucz w kolorze czerwonym. Wykończone w Rapsheet Red." },
            { "Text.Editor.DoubleDoor_V.Desc", "Zestaw zwykłych podwójnych drzwi." },
            { "Text.Editor.DoubleDoor_V_Cyan.Desc", "Podwójne drzwi na klucz w kolorze cyjanowym. Wykończone w Solitary Cyan." },
            { "Text.Editor.DoubleDoor_V_Green.Desc", "Podwójne drzwi na klucz w kolorze zielonym. Wykończone w Gallows Green." },
            { "Text.Editor.DoubleDoor_V_Red.Desc", "Podwójne drzwi na klucz w kolorze czerwonym. Wykończone w Rapsheet Red." },
            { "Text.Editor.Bin.Name", "Kosz na śmieci" },
            { "Text.Editor.Bush_Large.Name", "Krzak (6)" },
            { "Text.Editor.Coffee_Table.Name", "Stolik kawowy" },
            { "Text.Editor.Coffee_Table_01.Name", "Stolik kawowy" },
            { "Text.Editor.Coffee_Table_02.Name", "Stolik kawowy (3)" },
            { "Text.Editor.Coffee_Table_03.Name", "Stolik kawowy (4)" },
            { "Text.Editor.CrateLarge.Name", "Skrzynia (1)" },
            { "Text.Editor.CrateSingle.Name", "Skrzynia" },
            { "Text.Editor.CrateStack.Name", "Stos skrzyń (1)" },
            { "Text.Editor.Filing_Cabinet.Name", "Szafka na dokumenty" },
            { "Text.Editor.InmateDesk.Name", "Biurko więźnia" },
            { "Text.Editor.Locker.Name", "Szafka" },
            { "Text.Editor.MedicalBay_BedsideCupboard.Name", "Szafka przy łóżku" },
            { "Text.Editor.MedicalBay_Trolly.Name", "Wózek medyczny" },
            { "Text.Editor.MedicalBay_Table.Name", "Biurko administracji medycznej" },
            { "Text.Editor.OfficeChair.Name", "Krzesło biurowe" },
            { "Text.Editor.Potted_Plant.Name", "Roślina w doniczce" },
            { "Text.Editor.Seat.Name", "Krzesło plastikowe" },
            { "Text.Editor.Shrub.Name", "Krzak" },
            { "Text.Editor.Sofa_2_Seater.Name", "Sofa (2 osoby)" },
            { "Text.Editor.Sofa_3_SeaterChesterfield.Name", "Sofa (3 osoby)" },
            { "Text.Editor.Table.Name", "Stół (1)" },
            { "Text.Editor.Table_CoffeeBooks.Name", "Stół" },
            { "Text.Editor.Table_CoffeePhotos.Name", "Stół (3)" },
            { "Text.Editor.Table_Donuts.Name", "Stół (4)" },
            { "Text.Editor.Table_PaintingStuff.Name", "Stół (5)" },
            { "Text.Editor.Table_OfficeLampFolder.Name", "Stanowisko biurowe" },
            { "Text.Editor.Table_OfficeLampPhone.Name", "Stanowisko biurowe (2)" },
            { "Text.Editor.VentCover.Name", "Kratka wentylacyjna" },
            { "Text.Editor.VentFloor.Name", "Wentylacja podłogowa" },
            { "Text.Editor.WoodenBench.Name", "Ławka drewniana" },
            { "Text.Editor.Gym_Treadmill.Name", "Bieżnia" },
            { "Text.Editor.Gym_WeightBench.Name", "Ławka do ćwiczeń" },
            { "Text.Editor.Bookcase_Down.Name", "Regał na książki" },
            { "Text.Editor.Wardens_Chair.Name", "Luksusowe krzesło" },
            { "Text.Editor.Sun_Lounger_Left.Name", "Leżak" },
            { "Text.Editor.BBQ_Down.Name", "Grill" },
            { "Text.Editor.Patio_Table_2x2.Name", "Stół drewniany" },
            { "Text.Editor.Security_Light.Name", "Lampa bezpieczeństwa" },
            { "Text.Editor.Bush_01.Name", "Krzak (1)" },
            { "Text.Editor.Bush_02.Name", "Krzak (2)" },
            { "Text.Editor.Bush_03.Name", "Krzak (3)" },
            { "Text.Editor.Bush_04.Name", "Krzak" },
            { "Text.Editor.Bush_05.Name", "Krzak (5)" },
            { "Text.Editor.CCTVCamera.Name", "Kamera bezpieczeństwa" },
            { "Text.Editor.Contraband.Name", "Wykrywacz kontrabandy" },
            { "Text.Editor.Fountain.Name", "Fontanna" },
            { "Text.Editor.Rubbish_Sack_01.Name", "Worek na śmieci" },
            { "Text.Editor.Rubbish_Sack_02.Name", "Worek na śmieci (2)" },
            { "Text.Editor.Rubbish_Sack_03.Name", "Worek na śmieci (3)" },
            { "Text.Editor.Tree_01.Name", "Drzewo (1)" },
            { "Text.Editor.Tree_02.Name", "Drzewo (2)" },
            { "Text.Editor.GuardDesk_3x1_Right", "Stół strażnika (1)" },
            { "Text.Editor.GuardDesk_2x1", "Stół strażnika (2)" },
            { "Text.Editor.CrateStack_02.Name", "Stos skrzyń (2)" },
            { "Text.Editor.Cupboard_Wooden.Name", "Szafka drewniana" },
            { "Text.Editor.StairsUpwards.Name", "Schody (w górę)" },
            { "Text.Editor.StairsDownwards.Name", "Schody (w dół)" },
            { "Text.Editor.Cutlery.Name", "Szuflada na sztućce" },
            { "Text.Editor.GuardDesk.Name", "Biurko strażnika" },
            { "Text.Editor.Wardens_Desk.Name", "Biurko dyrektora" },
            { "Text.Editor.Bin.Desc", "Cóż, to kosz…" },
            { "Text.Editor.Bush_Large.Desc", "Nieco za duża roślinność." },
            { "Text.Editor.Coffee_Table.Desc", "Stolik do spotkań towarzyskich." },
            { "Text.Editor.Coffee_Table_01.Desc", "Ręce z stolika kawowego!" },
            { "Text.Editor.Coffee_Table_02.Desc", "Duży, solidny, ale nigdy schludny." },
            { "Text.Editor.Coffee_Table_03.Desc", "Pokryty brudem i kasetami." },
            { "Text.Editor.CrateLarge.Desc", "Duża drewniana skrzynia." },
            { "Text.Editor.CrateSingle.Desc", "Mała drewniana skrzynia." },
            { "Text.Editor.CrateStack.Desc", "Stos drewnianych skrzyń." },
            { "Text.Editor.Filing_Cabinet.Desc", "Szafka na dokumenty." },
            { "Text.Editor.InmateDesk.Desc", "Klasyczne biurko więźnia. Idealne do chowania rzeczy." },
            { "Text.Editor.Locker.Desc", "Jeśli nie chcesz być znaleziony. Daje miejsce do ukrycia się." },
            { "Text.Editor.MedicalBay_BedsideCupboard.Desc", "Dekoracyjna szafka, zwykle w infirmerii." },
            { "Text.Editor.MedicalBay_Trolly.Desc", "Dekoracyjny wózek, zwykle w infirmerii." },
            { "Text.Editor.MedicalBay_Table.Desc", "Biurko z komputerem i drobnym sprzętem medycznym." },
            { "Text.Editor.OfficeChair.Desc", "Zwykłe krzesło biurowe. Zwiększa regenerację Energii podczas siedzenia." },
            { "Text.Editor.Potted_Plant.Desc", "Ładna roślina w doniczce." },
            { "Text.Editor.Seat.Desc", "Trochę niewygodne, ale wystarczy. Usiądź, by odzyskać Energię." },
            { "Text.Editor.Shrub.Desc", "Jakiś krzak!" },
            { "Text.Editor.Sofa_2_Seater.Desc", "Sofa dla dwóch. Odpocznij i uzupełnij Energię." },
            { "Text.Editor.Sofa_3_SeaterChesterfield.Desc", "Sofa dla trzech. Nie wygodnicz się za bardzo, ale korzystaj z regeneracji Energii." },
            { "Text.Editor.Table.Desc", "To jest stół…" },
            { "Text.Editor.Table_CoffeeBooks.Desc", "Z kawą i książkami." },
            { "Text.Editor.Table_CoffeePhotos.Desc", "Z kawą i zdjęciami." },
            { "Text.Editor.Table_Donuts.Desc", "Ręce precz od moich pączków!" },
            { "Text.Editor.Table_PaintingStuff.Desc", "Nie gadaj, maluj… pozwól pędzlowi działać." },
            { "Text.Editor.Table_OfficeLampFolder.Desc", "Profesjonalnie wyglądające stanowisko." },
            { "Text.Editor.Table_OfficeLampPhone.Desc", "Styl ponad treścią." },
            { "Text.Editor.VentCover.Desc", "Przykrywa otwory wentylacyjne… Odkręć lub złam, aby dostać się do kanałów." },
            { "Text.Editor.VentFloor.Desc", "Wentylacja." },
            { "Text.Editor.WoodenBench.Desc", "Ręcznie wykonana drewniana ławka." },
            { "Text.Editor.Gym_Treadmill.Desc", "Użyj, aby poprawić kondycję." },
            { "Text.Editor.Gym_WeightBench.Desc", "Użyj, aby poprawić siłę." },
            { "Text.Editor.Bookcase_Down.Desc", "Czytaj książki, by zwiększyć intelekt." },
            { "Text.Editor.Wardens_Chair.Desc", "Eleganckie tapicerowane krzesło, zwiększa regenerację Energii więźnia." },
            { "Text.Editor.Sun_Lounger_Left.Desc", "Ciesz się słońcem i odzyskaj Energię leżąc na nim." },
            { "Text.Editor.BBQ_Down.Desc", "Służyłby do pieczenia mięsa, gdyby było jakieś." },
            { "Text.Editor.Patio_Table_2x2.Desc", "Dekoracyjny drewniany stół." },
            { "Text.Editor.Security_Light.Desc", "Te światła mają moc miliona (mikroskopijnych) świec." },
            { "Text.Editor.Bush_01.Desc", "To zielony krzak." },
            { "Text.Editor.Bush_02.Desc", "To krzak i jest zielony." },
            { "Text.Editor.Bush_03.Desc", "Jeśli wygląda jak zielony krzak, to pewnie nim jest." },
            { "Text.Editor.Bush_04.Desc", "Co jest zielone i krzaczaste? Krzak." },
            { "Text.Editor.Bush_05.Desc", "Krzak. To wszystko." },
            { "Text.Editor.CCTVCamera.Desc", "Wielki brat cię obserwuje. Powiadamia strażników o złym zachowaniu więźniów." },
            { "Text.Editor.Contraband.Desc", "Wykrywa kontrabandę. Prawdopodobnie zapewni wizytę w szpitalu, jeśli zostaniesz złapany." },
            { "Text.Editor.Fountain.Desc", "Miejsce rozwoju bakterii. Nie pij z niego." },
            { "Text.Editor.Rubbish_Sack_01.Desc", "Pozostawiając je, miejsce wygląda na bałagan." },
            { "Text.Editor.Rubbish_Sack_02.Desc", "Ktoś zapomniał wynieść śmieci?" },
            { "Text.Editor.Rubbish_Sack_03.Desc", "To miejsce zaczyna pachnieć jak stara skarpeta pokryta spalonymi włosami." },
            { "Text.Editor.Tree_01.Desc", "To duże drzewo." },
            { "Text.Editor.Tree_02.Desc", "To małe drzewo." },
            { "Text.Editor.GuardDesk_3x1_Right.Desc", "Duże biurko, ozdobione, by wyglądało na ważne." },
            { "Text.Editor.GuardDesk_2x1.Desc", "Małe biurko." },
            { "Text.Editor.CrateStack_02.Desc", "Stos drewnianych skrzyń." },
            { "Text.Editor.Cupboard_Wooden.Desc", "Szafka z drewna." },
            { "Text.Editor.StairsUpwards.Desc", "Schody prowadzące w górę…" },
            { "Text.Editor.StairsDownwards.Desc", "Schody prowadzące w dół…" },
            { "Text.Editor.Cutlery.Desc", "Plastikowe sztućce, można używać jako podstawowych narzędzi do drapania, cięcia i kopania." },
            { "Text.Editor.GuardDesk.Desc", "Biurko dla strażników." },
            { "Text.Editor.Wardens_Desk.Desc", "Tutaj rodzą się lub pękają marzenia." },
            { "Text.Editor.Room.Blacksmith_01.Name", "Ślusarnia" },
            { "Text.Editor.Room.Blacksmith_02.Name", "Ślusarnia (2)" },
            { "Text.Editor.Room.ContrabandRoom.Name", "Pokój kontrabandy" },
            { "Text.Editor.Room.ContrabandRoom_01.Name", "Pokój kontrabandy" },
            { "Text.Editor.Room.ControlRoom_01.Name", "Pokój kontroli więzienia" },
            { "Text.Editor.Room.GeneratorRoom_01.Name", "Generatorownia" },
            { "Text.Editor.Room.GuardQuarters_01.Name", "Kwatera strażników" },
            { "Text.Editor.Room.GuardQuarters_02.Name", "Kwatera strażników (2)" },
            { "Text.Editor.Room.GuardRoom_01.Name", "Cela strażników" },
            { "Text.Editor.Room.GuardRoom_02.Name", "Cela strażników (2)" },
            { "Text.Editor.Room.GuardRoom_03.Name", "Cela strażników (3)" },
            { "Text.Editor.Room.Gym_01.Name", "Siłownia" },
            { "Text.Editor.Room.Gym_02.Name", "Siłownia (2)" },
            { "Text.Editor.Room.Gym_03.Name", "Siłownia (3)" },
            { "Text.Editor.Room.Infirmary_01.Name", "Infirmeria" },
            { "Text.Editor.Room.Infirmary_02.Name", "Infirmeria (2)" },
            { "Text.Editor.Room.Infirmary_03.Name", "Infirmeria (3)" },
            { "Text.Editor.Room.InmateCell_01.Name", "Cela więźnia" },
            { "Text.Editor.Room.InmateCell_02.Name", "Cela więźnia (2)" },
            { "Text.Editor.Room.InmateCell_03.Name", "Cela więźnia (3)" },
            { "Text.Editor.Room.IRU_01.Name", "Infirmeria: Mała" },
            { "Text.Editor.Room.IRU_02.Name", "Infirmeria: Mała (2)" },
            { "Text.Editor.Room.JobOffice_01.Name", "Biuro pracy" },
            { "Text.Editor.Room.Kennels_01.Name", "Kojce" },
            { "Text.Editor.Room.Kennels_02.Name", "Kojce (2)" },
            { "Text.Editor.Room.Kitchen_01.Name", "Kuchnia" },
            { "Text.Editor.Room.Kitchen_02.Name", "Kuchnia (2)" },
            { "Text.Editor.Room.Library_01.Name", "Biblioteka" },
            { "Text.Editor.Room.Library_02.Name", "Biblioteka (2)" },
            { "Text.Editor.Room.MaintenanceRoom_01.Name", "Pomieszczenie konserwatora" },
            { "Text.Editor.Room.MaintenanceRoom_02.Name", "Pomieszczenie konserwatora (2)" },
            { "Text.Editor.Room.MealHall_01.Name", "Jadalnia" },
            { "Text.Editor.Room.MealHall_02.Name", "Jadalnia (2)" },
            { "Text.Editor.Room.MealHall_03.Name", "Jadalnia (3)" },
            { "Text.Editor.Room.RollCall_01.Name", "Apel" },
            { "Text.Editor.Room.Showers_01.Name", "Łaźnia" },
            { "Text.Editor.Room.Showers_02.Name", "Łaźnia (2)" },
            { "Text.Editor.Room.Showers_03.Name", "Łaźnia (3)" },
            { "Text.Editor.Room.SocialArea_01.Name", "Pokój socjalny" },
            { "Text.Editor.Room.SocialArea_02.Name", "Pokój socjalny (2)" },
            { "Text.Editor.Room.SocialArea_03.Name", "Pokój socjalny (3)" },
            { "Text.Editor.Room.SolitaryBlock_01.Name", "Blok izolacyjny" },
            { "Text.Editor.Room.WardenOffice_01.Name", "Biuro dyrektora" },
            { "Text.Editor.Room.Woodwork_01.Name", "Pracownia stolarska" },
            { "Text.Editor.Room.Woodwork_02.Name", "Pracownia stolarska (2)" },
            { "Text.Editor.Room.Blacksmith_01.Desc", "Pracuj tutaj, by zarobić trochę pieniędzy. Nie poparz się." },
            { "Text.Editor.Room.ContrabandRoom_01.Desc", "Towary skonfiskowane przez strażników przechowywane są w biurku w tym pokoju. To kopalnia złota." },
            { "Text.Editor.Room.ControlRoom_01.Desc", "Strażnicy obserwują całe więzienie z komfortu tego pokoju." },
            { "Text.Editor.Room.GeneratorRoom_01.Desc", "Generator zasila systemy elektroniczne. Nie wyłączaj go. Proszę, nie." },
            { "Text.Editor.Room.GuardQuarters_01.Desc", "Tutaj strażnicy spędzają czas z innymi strażnikami." },
            { "Text.Editor.Room.GuardQuarters_02.Desc", "Tutaj strażnicy spędzają czas z innymi strażnikami." },
            { "Text.Editor.Room.GuardRoom_01.Desc", "Strażnicy też potrzebują snu." },
            { "Text.Editor.Room.GuardRoom_02.Desc", "Strażnicy też potrzebują snu." },
            { "Text.Editor.Room.GuardRoom_03.Desc", "Strażnicy też potrzebują snu." },
            { "Text.Editor.Room.Gym_01.Desc", "Popraw siłę i kondycję. Czas się wzmocnić." },
            { "Text.Editor.Room.Gym_02.Desc", "Popraw siłę i kondycję. Czas się wzmocnić." },
            { "Text.Editor.Room.Gym_03.Desc", "Popraw siłę i kondycję. Czas się wzmocnić." },
            { "Text.Editor.Room.Infirmary_01.Desc", "Tu trafiasz po nokaucie." },
            { "Text.Editor.Room.Infirmary_02.Desc", "Tu trafiasz po nokaucie." },
            { "Text.Editor.Room.Infirmary_03.Desc", "Tu trafiasz po nokaucie." },
            { "Text.Editor.Room.InmateCell_01.Desc", "Skromne lokum przeciętnego więźnia." },
            { "Text.Editor.Room.InmateCell_02.Desc", "Skromne lokum przeciętnego więźnia." },
            { "Text.Editor.Room.InmateCell_03.Desc", "Skromne lokum przeciętnego więźnia." },
            { "Text.Editor.Room.IRU_01.Desc", "Tu trafiasz po nokaucie." },
            { "Text.Editor.Room.IRU_02.Desc", "Tu trafiasz po nokaucie." },
            { "Text.Editor.Room.JobOffice_01.Desc", "Chcesz dorobić? Zgłoś się w środku." },
            { "Text.Editor.Room.Kennels_01.Desc", "Tu są psy." },
            { "Text.Editor.Room.Kennels_02.Desc", "Tu są psy." },
            { "Text.Editor.Room.Kitchen_01.Desc", "Tu przygotowuje się więzienne jedzenie… znaczy gotuje."},
            { "Text.Editor.Room.Library_01.Desc", "Zwiększ intelekt, czytając książki." },
            { "Text.Editor.Room.Library_02.Desc", "Zwiększ intelekt, czytając książki." },
            { "Text.Editor.Room.MaintenanceRoom_01.Desc", "Tu mieszka więzienny majster." },
            { "Text.Editor.Room.MaintenanceRoom_02.Desc", "Tu mieszka więzienny majster." },
            { "Text.Editor.Room.MealHall_01.Desc", "Chwyć jedzenie i usiądź." },
            { "Text.Editor.Room.MealHall_02.Desc", "Chwyć jedzenie i usiądź." },
            { "Text.Editor.Room.MealHall_03.Desc", "Chwyć jedzenie i usiądź." },
            { "Text.Editor.Room.RollCall_01.Desc", "Bądź obecny lub trafisz do izolacji (przez infirmerię). Twój wybór." },
            { "Text.Editor.Room.Showers_01.Desc", "Nikt nie lubi śmierdzącego więźnia." },
            { "Text.Editor.Room.Showers_02.Desc", "Nikt nie lubi śmierdzącego więźnia." },
            { "Text.Editor.Room.Showers_03.Desc", "Nikt nie lubi śmierdzącego więźnia." },
            { "Text.Editor.Room.SocialArea_01.Desc", "Użyj tego miejsca, aby spotykać się i robić szemrane interesy." },
            { "Text.Editor.Room.SocialArea_02.Desc", "Użyj tego miejsca, aby spotykać się i robić szemrane interesy." },
            { "Text.Editor.Room.SocialArea_03.Desc", "Użyj tego miejsca, aby spotykać się i robić szemrane interesy." },
            { "Text.Editor.Room.SolitaryBlock_01.Desc", "Jeśli lubisz obierać ziemniaki, spróbuj tu spędzić trochę czasu." },
            { "Text.Editor.Room.WardenOffice_01.Desc", "Biuro głównego dyrektora." },
            { "Text.Editor.Room.Woodwork_01.Desc", "Miejsce pracy. Uważaj na drzazgi." },
            { "Text.Editor.Outside", "NA ZEWNĄTRZ" },
            { "Text.Editor.Inside", "WEWNĄTRZ" },
            { "Text.Editor.Rooms", "POKOJE" },
            { "Text.Editor.Objects", "OBIEKTY" },
            { "Text.Editor.Checklist", "LISTA KONTROLNA" },
            { "Text.Editor.FloorRoof", "Dach" },
            { "Text.Editor.FloorVents02", "Wentylacja 2" },
            { "Text.Editor.FloorVents01", "Wentylacja 1" },
            { "Text.Editor.Floor01", "Piętro 1" },
            { "Text.Editor.Floor02", "Piętro 2" },
            { "Text.Editor.PrisonName", "Nazwa więzienia" },
            { "Text.Editor.PrisonDescription", "Opis więzienia" },
            { "Text.Editor.PrisonImage", "Zdjęcie więzienia" },
            { "Text.Editor.PrisonDifficulty", "Trudność więzienia" },
            { "Text.Editor.ItemSpawn1", "Przedmioty na biurku 01" },
            { "Text.Editor.ItemSpawn2", "Przedmioty na biurku 02" },
            { "Text.Editor.ItemSpawn3", "Przedmioty na biurku 03" },
            { "Text.Editor.ItemSpawn4", "Przedmioty na biurku 04" },
            { "Text.Editor.ItemSpawn5", "Przedmioty na biurku 05" },
            { "Text.Editor.PrisonRoutine", "HARMONOGRAM WIĘZIENIA" },
            { "Text.Editor.PrisonSettings", "USTAWIENIA WIĘZIENIA" },
            { "Text.Editor.PrisonInfo", "INFO O WIĘZIENIU" },
            { "Text.Editor.PLP.Bin.Name", "Kosz" },
            { "Text.Editor.PLP.Computer.Name", "Komputer" },
            { "Text.Editor.PLP.Cup_01.Name", "Kubek" },
            { "Text.Editor.PLP.Cup_02.Name", "Kubek (2)" },
            { "Text.Editor.PLP.Cup_Spill.Name", "Rozlany kubek" },
            { "Text.Editor.PLP.DeskLamp_Modern.Name", "Lampka biurkowa" },
            { "Text.Editor.PLP.DeskLamp_Ornate.Name", "Lampka biurkowa (2)" },
            { "Text.Editor.PLP.DonutBox.Name", "Pudełko z pączkami" },
            { "Text.Editor.PLP.FireExtinguisher.Name", "Gaśnica" },
            { "Text.Editor.PLP.FloorToiletRoll_01.Name", "Papier toaletowy" },
            { "Text.Editor.PLP.FloorToiletRoll_02.Name", "Papier toaletowy (2)" },
            { "Text.Editor.PLP.Magazine_01.Name", "Magazyn" },
            { "Text.Editor.PLP.Magazine_02.Name", "Magazyn (2)" },
            { "Text.Editor.PLP.MopBucket.Name", "Mop i wiadro" },
            { "Text.Editor.PLP.PaintBrush_01.Name", "Pędzel" },
            { "Text.Editor.PLP.PaintBrush_02.Name", "Pędzel (2)" },
            { "Text.Editor.PLP.PaintBrush_03.Name", "Pędzel (3)" },
            { "Text.Editor.PLP.PaintPot_Large_01.Name", "Kubek z farbą" },
            { "Text.Editor.PLP.PaintPot_Large_02.Name", "Kubek z farbą (2)" },
            { "Text.Editor.PLP.Paperback_01.Name", "Książka kieszonkowa" },
            { "Text.Editor.PLP.Paperback_02.Name", "Książka kieszonkowa (2)" },
            { "Text.Editor.PLP.Polaroid_01.Name", "Polaroid" },
            { "Text.Editor.PLP.Radio.Name", "Radio" },
            { "Text.Editor.PLP.SheetMusic_01.Name", "Nuty" },
            { "Text.Editor.PLP.SheetMusic_02.Name", "Nuty (2)" },
            { "Text.Editor.PLP.SheetMusic_03.Name", "Nuty (3)" },
            { "Text.Editor.PLP.Trash_01.Name", "Śmieci" },
            { "Text.Editor.PLP.WastePaper_01.Name", "Makulatura" },
            { "Text.Editor.PLP.WastePaper_02.Name", "Makulatura (2)" },
            { "Text.Editor.PLP.WetFloorSign.Name", "Tablica: mokra podłoga" },
            { "Text.Editor.PLP.Bin.Desc", "Typowy kosz na makulaturę." },
            { "Text.Editor.PLP.Computer.Desc", "Komputer osobisty z słabym CPU i zintegrowaną grafiką." },
            { "Text.Editor.PLP.Cup_01.Desc", "Kubek. Wygląda dobrze na stole lub na podłodze." },
            { "Text.Editor.PLP.Cup_Spill.Desc", "Ktoś powinien to posprzątać." },
            { "Text.Editor.PLP.DeskLamp_Modern.Desc", "Zwykła lampka biurkowa." },
            { "Text.Editor.PLP.DeskLamp_Ornate.Desc", "Zwykła lampka biurkowa… z lat 30." },
            { "Text.Editor.PLP.DonutBox.Desc", "Pudełko pełne słodkości." },
            { "Text.Editor.PLP.FireExtinguisher.Desc", "Przepisy BHP w akcji." },
            { "Text.Editor.PLP.FloorToiletRoll_01.Desc", "Cóż, zawsze możesz użyć skarpet…" },
            { "Text.Editor.PLP.Magazine_01.Desc", "Magazyn 'Inmates Monthly'. Zawiera próbkę perfum do powąchania." },
            { "Text.Editor.PLP.MopBucket.Desc", "Super narzędzia do sprzątania. Powiedziano to ironicznie." },
            { "Text.Editor.PLP.PaintBrush_01.Desc", "Ooo, wygląda na to, że mamy tu Picassa w domu."},
            { "Text.Editor.PLP.PaintPot_Large_01.Desc", "Kubek krzykliwej farby." },
            { "Text.Editor.PLP.Paperback_01.Desc", "Okropna lektura." },
            { "Text.Editor.PLP.Polaroid_01.Desc", "Losowe zdjęcie czyjejś rodziny." },
            { "Text.Editor.PLP.Radio.Desc", "Budżetowy odtwarzacz muzyki. Wątpię, że działa." },
            { "Text.Editor.PLP.SheetMusic_01.Desc", "Wygląda jak fragment koncertu. Ktoś miał za dużo wolnego czasu." },
            { "Text.Editor.PLP.Trash_01.Desc", "Zwykły śmieć." },
            { "Text.Editor.PLP.WastePaper_01.Desc", "Pognieciony papier. Pewnie coś nieistotnego, jak papiery do przedterminowego zwolnienia."},
            { "Text.Editor.PLP.WetFloorSign.Desc", "Nikt nie zwraca uwagi na te znaki – dopóki nie skończy w infirmerii." },
            { "Text.Editor.Error.NotEnoughOfRoomType", "Nie masz wystarczającej liczby: %Object%" },
            { "Text.Editor.Error.RoomNotAccessible", "Nie można uzyskać dostępu do: %RoomName%" },
            { "Text.Editor.JobRoom.Name", "Pokój pracy" },
            { "Text.Editor.Guard.Name", "Strażnik więzienny" },
            { "Text.Editor.Inmate.Name", "Więzień" },
            { "Text.Editor.Dog.Name", "Pies" },
            { "Text.Editor.Maintenance.Name", "Konserwator" },
            { "Text.Editor.Medic.Name", "Pielęgniarz" },
            { "Text.Editor.RiotGuard.Name", "Oddział interwencyjny" },
            { "Text.Editor.JobRoom.Desc", "" },
            { "Text.Editor.Guard.Desc", "Strażnicy obserwują każdy twój ruch; jeśli tylko kichniesz, będą gotowi wytrzeć twój nos."},
            { "Text.Editor.Inmate.Desc", "Mieszkańcy więzienia." },
            { "Text.Editor.Dog.Desc", "Psy zostają spuszczone, gdy temperatura w więzieniu osiągnie maksimum. Nie chcesz tego."},
            { "Text.Editor.Maintenance.Desc", "Spuszczanie rzeczy w toalecie często powoduje zatory. Ten facet je naprawia." },
            { "Text.Editor.Medic.Desc", "" },
            { "Text.Editor.RiotGuard.Desc", "" },
            { "Text.Editor.Menu.Exit", "Wyjście" },
            { "Text.Editor.Menu.Help", "Pomoc" },
            { "Text.Editor.Menu.Play", "Graj poziom" },
            { "Text.Editor.Menu.Save", "Zapisz" },
            { "Text.Editor.Menu.Undo", "Cofnij" },
            { "Text.Editor.Menu.Redo", "Ponów" },
            { "Text.Editor.Menu.PrisonInfo", "Przejdź do informacji o więzieniu" },
            { "Text.Editor.Menu.PrisonSettings", "Przejdź do ustawień więzienia" },
            { "Text.Editor.PrisonSettings.Easy", "Łatwe" },
            { "Text.Editor.PrisonSettings.Medium", "Średnie" },
            { "Text.Editor.PrisonSettings.Hard", "Trudne" },
            { "Text.Editor.Reset", "RESETUJ POZIOM" },
            { "Text.Edit.OkToReset", "Czy na pewno chcesz zresetować poziom?" },
            { "Text.Editor.PublishAs", "Publikuj jako" },
            { "Text.Editor.Visibility", "Widoczność" },
            { "Text.Editor.ViewTerms", "PRZEGLĄDAJ WARUNKI" },
            { "Text.Editor.Publish", "PUBLIKUJ" },
            { "Text.Editor.PrisonImageDesc", "Zrób zdjęcie swojego więzienia, aby użyć go jako obraz podglądu. Ustaw kamerę w edytorze tam, skąd chcesz wykonać zdjęcie." },
            { "Text.Editor.PrisonDifficultyInfo", "Zmiana trudności więzienia wpływa na strażników, sprzedawców oraz opinię innych więźniów o tobie."},
            { "Text.Editor.ItemSpawnInfo", "Zmiana rozmieszczenia przedmiotów wpływa na ich typ i rzadkość." },
            { "Text.Editor.Escape.Name", "Strefa ucieczki" },
            { "Text.Editor.Escape.Ambulance.Name", "Ucieczka ambulans" },
            { "Text.Editor.Escape.Bike_01.Name", "Ucieczka motorem" },
            { "Text.Editor.Escape.BinTruck.Name", "Ucieczka śmieciarką" },
            { "Text.Editor.Escape.Boat_01.Name", "Ucieczka łodzią" },
            { "Text.Editor.Escape.Boat_02.Name", "Ucieczka łodzią (2)" },
            { "Text.Editor.Escape.Car_01.Name", "Ucieczka samochodem" },
            { "Text.Editor.Escape.Car_02.Name", "Ucieczka samochodem (2)" },
            { "Text.Editor.Escape.Car_03.Name", "Ucieczka samochodem (3)" },
            { "Text.Editor.Escape.Helicopter_01.Name", "Ucieczka helikopterem" },
            { "Text.Editor.Escape.Jeep.Name", "Ucieczka jeepem" },
            { "Text.Editor.Escape.Jetski.Name", "Ucieczka skuterem wodnym" },
            { "Text.Editor.Escape.MilitaryTruck.Name", "Ucieczka wojskową ciężarówką" },
            { "Text.Editor.Escape.PoliceCar.Name", "Ucieczka radiowozem" },
            { "Text.Editor.Escape.PoliceVan.Name", "Ucieczka furgonetką policyjną" },
            { "Text.Editor.LandEscapes.Name", "Ucieczki lądowe" },
            { "Text.Editor.WaterEscapes.Name", "Ucieczki wodne" },
            { "Text.Editor.AirEscapes.Name", "Ucieczki powietrzne" },
            { "Text.Editor.Escape.Desc", "Dotrzyj do tego pojazdu, jeśli chcesz uciec!" },
            { "Text.Editor.DefaultPrisonTitle.Name", "Moje Więzienie" },
            { "Text.Editor.Rules", "ZASADY" },
            { "Text.Editor.Controls", "STEROWANIE" },
            { "Text.Editor.Hints", "WSKAZÓWKI" },
            { "Text.Editor.Save", "ZAPISZ" },
            { "Text.Editor.SaveAs", "NOWY ZAPIS" },
            { "Text.Editor.Reload", "PRZEŁADUJ POZIOM" },
            { "Text.Editor.Common", "Pospolite" },
            { "Text.Editor.Uncommon", "Niepospolite" },
            { "Text.Editor.Rare", "Rzadkie" },
            { "Text.Editor.Weapons", "Broń" },
            { "Text.Editor.Tools", "Narzędzia" },
            { "Text.Editor.NoMoreBlocks", "Osiągnąłeś maksymalną ilość tego typu elementów na poziomie." },
            { "Text.Editor.NoPrisonsCreated", "Nie masz jeszcze żadnego własnego więzienia. Naciśnij przycisk 'Utwórz Więzienie' poniżej, aby zacząć." },
            { "Text.Editor.NoPrisonsSubscribed", "Nie subskrybujesz żadnych więzień. Odwiedź stronę Warsztatu Steam The Escapists 2, aby zobaczyć wszystkie dostępne więzienia." },
            { "Text.Editor.PrisonChecker", "KONTROLE BEZPIECZEŃSTWA WIĘZIENIA" },
            { "Text.Editor.Preview", "PODGLĄD WIĘZIENIA" },
            { "Text.Editor.CheckingPrison", "Skanowanie więzienia pod kątem luk w bezpieczeństwie …" },
            { "Text.Editor.Floor.Ground", "Parter" },
            { "Text.Editor.Floor.Vent", "Wentylacja" },
            { "Text.Editor.Floor.First", "Pierwsze piętro" },
            { "Text.Editor.Floor.Roof", "Dach" },
            { "Text.Editor.CheckerPassed", "Twoje więzienie przeszło wszystkie kontrole bezpieczeństwa. Mamy nadzieję, że pobyt będzie przyjemny."},
            { "Text.Editor.WelcomeTitle", "WITAJ W EDYTORZE WIĘZIENIA" },
            { "Text.Editor.WelcomeBody", "Witaj w Edytorze Więzienia The Escapists 2! \\n\\n - Bloki budowlane: Po lewej stronie wybieraj z kategorii wnętrza, zewnętrza, pokoje i obiekty, aby budować swoje więzienie. \\n\\n - Lista kontrolna: Sprawdź wymagania, aby więzienie było grywalne. Znajdziesz ją w panelu w prawym dolnym rogu. \\n\\n - Wybór piętra: Buduj na 2 piętrach, 2 warstwach wentylacji i dachu. Zmiana piętra jest tak prosta, jak kliknięcie wybranego piętra w prawym górnym panelu. \\n\\n - Narzędzia: Wyjście, Pomoc, Podgląd, Zarządzanie plikami, Cofnij i Ponów znajdziesz w lewym dolnym rogu. \\n\\n - Ustawienia więzienia: Ustaw nazwę, opis i obraz więzienia, wybierz harmonogram i przedmioty do rozmieszczenia. Kliknij dowolny z 3 przycisków w prawym dolnym rogu, aby uzyskać dostęp do tych funkcji."},
            { "Text.Editor.DontShowAgain", "Nie pokazuj ponownie tej wiadomości" },
            { "Text.Editor.Controls.Rotation", "TAB" },
            { "Text.Editor.DefaultPrisonDescription", "Wpisz tutaj opis swojego więzienia!" },
            { "Text.Editor.DefaultPrisonName", "Moje Więzienie $PrisonCount" },
            { "Text.Editor.ControlAction01", "Umieść blok" },
            { "Text.Editor.ControlAction02", "Usuń" },
            { "Text.Editor.ControlAction03", "Przesuń kamerę" },
            { "Text.Editor.ControlAction04", "Przybliż/Oddal" },
            { "Text.Editor.ControlAction05", "Obróć blok" },
            { "Text.Editor.ControlAction06", "Wyśrodkuj mapę" },
            { "Text.Editor.ControlAction07", "Piętro w górę" },
            { "Text.Editor.ControlAction08", "Piętro w dół" },
            { "Text.Editor.ControlAction09", "Piętro 1" },
            { "Text.Editor.ControlAction10", "Wentylacja 1" },
            { "Text.Editor.ControlAction11", "Piętro 2" },
            { "Text.Editor.ControlAction12", "Wentylacja 2" },
            { "Text.Editor.ControlAction13", "Dach" },
            { "Text.Editor.ControlAction14", "Zapisz" },
            { "Text.Editor.ControlAction15", "Cofnij" },
            { "Text.Editor.ControlAction16", "Ponów" },
            { "Text.Editor.ControlAction17", "Wyjdź" },
            { "Text.Editor.ControlAction18", "Odznacz blok" },
            { "Text.Editor.ControlAction19", "Pokaż/ukryj HUD" },
            { "Text.Editor.ControlAction20", "Pokaż/ukryj siatkę" },
            { "Text.Editor.Control01", "[LMB]" },
            { "Text.Editor.Control02", "[RMB]" },
            { "Text.Editor.Control03", "[MMB] [Strzałki] [W, A, S, D]" },
            { "Text.Editor.Control04", "[Kółko myszy] [+] [-]" },
            { "Text.Editor.Control05", "[TAB]" },
            { "Text.Editor.Control06", "[C]" },
            { "Text.Editor.Control07", "[PAGE UP]" },
            { "Text.Editor.Control08", "[PAGE DOWN]" },
            { "Text.Editor.Control09", "[F1]" },
            { "Text.Editor.Control10", "[F2]" },
            { "Text.Editor.Control11", "[F3]" },
            { "Text.Editor.Control12", "[F4]" },
            { "Text.Editor.Control13", "[F5]" },
            { "Text.Editor.Control14", "[CTRL + S]" },
            { "Text.Editor.Control15", "[CTRL + Z]" },
            { "Text.Editor.Control16", "[CTRL + Y]" },
            { "Text.Editor.Control17", "[ESC]" },
            { "Text.Editor.Control18", "[ESC]" },
            { "Text.Editor.Control19", "[SPACJA]" },
            { "Text.Editor.Control20", "[T]" },
            { "Text.Editor.RulesDesc", "- Masz siatkę 120 x 120 kafli do budowy więzienia.\\n\\n- Masz 2 piętra, 2 warstwy wentylacji i dach do budowy.\\n\\n- Więzienie dzieli się na obszary wewnętrzne i zewnętrzne. To określa, gdzie można budować kafle, pokoje i obiekty.\\n\\n- Aby budować na wyższym piętrze, musisz najpierw zbudować część wnętrza poniżej jako bazę.\\n\\n- Nie można dodawać ani usuwać obiektów w predefiniowanych pokojach.\\n\\n- Istnieje minimalna lista wymaganych pokojów, aby więzienie było funkcjonalne. Niektóre pokoje są wymagane tylko, jeśli istnieje dla nich harmonogram.\\n\\n- Wszystkie pokoje muszą mieć swobodny dostęp do miejsca apelowego.\\n\\n- Pokoje mogą dzielić ściany z innymi pokojami i korytarzami.\\n\\n- Wszystkie kafle, pokoje i obiekty mają maksymalną ilość, którą można umieścić.\\n\\n- Strefy ucieczki znajdują się wokół obwodu mapy.\\n\\n- Aby grać w najnowszą wersję więzienia, musisz rozpocząć nowy zapis. Starsze zapisy można odtwarzać w starszych wersjach więzień."},
            { "Text.Editor.HintsDesc", "\\n\\n- Upewnij się, że masz wystarczająco dużo czasu wolnego w harmonogramie.\\n\\n- Pierwsze 4 cele więźniów są zarezerwowane dla 4 graczy. Pozostałe cele wypełniają AI więźniowie.\\n\\n- Możesz zmieniać zawartość biurek więźniów i strażników w menu Ustawień.\\n\\n- Możesz zmienić podstawową trudność więzienia w menu Ustawień.\\n\\n- Kliknięcie pozycji w liście kontrolnej pozwala szybko zaznaczyć dany typ pokoju.\\n\\n- Pokoje mają wiele wariantów i rotacji.\\n\\n- Kliknięcie kafla, pokoju lub obiektu w świecie pozwala go przesunąć, usunąć lub skopiować."},
            { "Text.Editor.FileManagement", "ZARZĄDZANIE PLIKAMI" },
            { "Text.Editor.Block.Group.1", "A" },
            { "Text.Editor.Block.Group.2", "B" },
            { "Text.Editor.Block.Group.3", "C" },
            { "Text.Editor.Block.Group.4", "D" },
            { "Text.Editor.Visibility.Public", "Publiczne" },
            { "Text.Editor.Visibility.FriendsOnly", "Tylko dla znajomych" },
            { "Text.Editor.Visibility.Hidden", "Ukryte" },
            { "Text.Editor.PublishAsNew", "Publikuj jako nowe" },
            { "Text.Editor.InvalidTitle", "NIEPRAWIDŁOWA NAZWA" },
            { "Text.Edit.TitleIsInvalid", "Podana nazwa więzienia jest nieprawidłowa. Spróbuj inną." },
            { "Text.Editor.UploadingTitle", "WGRYWANIE" },
            { "Text.Editor.UploadingNotStarted", "Wgrywanie…" },
            { "Text.Editor.UploadFailedTitle", "BŁĄD WGRYWANIA" },
            { "Text.Edit.UploadFailed", "Nie udało się wgrać więzienia do Warsztatu Steam." },
            { "Text.Editor.UploadCompleteTitle", "WGRYWANIE ZAKOŃCZONE" },
            { "Text.Edit.UploadComplete", "Więzienie zostało pomyślnie wgrane do Warsztatu Steam." },
            { "Text.Editor.Uploading", "Wgrano $BytesProcessed z $BytesTotal" },
            { "Text.Editor.BlueprintInfo", "Centre Perks Prison Technologies. Specjalistyczne rozwiązania bezpieczeństwa. Trzymamy więźniów w środku od 2017 roku." },
            { "Text.Editor.BlueprintControls", "Lewy klik - Umieść\\n\\nPrawy klik - Usuń\\n\\nWASD - Kamera\\n\\nSpacja - Pokaż/Ukryj HUD\\n\\nT - Pokaż/Ukryj siatkę" },
            { "Text.Editor.ExitTooltip", "Wyjście" },
            { "Text.Editor.HelpTooltip", "Pomoc" },
            { "Text.Editor.CheckerTooltip", "Kontrola więzienia" },
            { "Text.Editor.FileManagementTooltip", "Zarządzanie plikami" },
            { "Text.Editor.UndoTooltip", "Cofnij" },
            { "Text.Editor.RedoTooltip", "Ponów" },
            { "Text.Editor.PrisonInfoTooltip", "Informacje" },
            { "Text.Editor.PrisonSettingsTooltip", "Ustawienia" },
            { "Text.Editor.PrisonRoutinesTooltip", "Harmonogram" },
            { "Text.Editor.Room.RollCall_02.Name", "Apel (2)" },
            { "Text.Editor.DeletePrison.Title", "USUŃ WIĘZIENIE" },
            { "Text.Editor.DeletePrison.Body", "Czy na pewno chcesz usunąć to więzienie?" },
            { "Text.Workshop.Desciption", "Twórz, udostępniaj i przeglądaj więzienia własne, offline lub online z przyjaciółmi. Testuj swoje zdolności ucieczki w stworzonych przez społeczność więzieniach lub importuj własne i wyzwij innych."},
            { "Text.Workshop.Title", "STWÓRZ WŁASNE WIĘZIENIA!" },
            { "Text.Editor.TakeSnapshot", "Zrób zdjęcie" },
            { "Text.Editor.Quit", "Czy na pewno chcesz wyjść? \\n(Wszelkie niezapisane postępy zostaną utracone)" },
            { "Text.Editor.ContrabandWide.Name", "Detektor kontrabandy (szeroki)" },
            { "Text.Editor.EscapePossible.Room", "UWAGA: To więzienie jest łatwe do ucieczki!" },
            { "Text.Editor.EscapePossible.Border", "UWAGA: Więźniowie mogą przejść prosto na zewnątrz!" },
            { "Text.Menu.QuitEditor", "Czy na pewno chcesz wyjść? Wszystkie niezapisane zmiany zostaną utracone." },
            { "Text.Editor.Unsubscribe", "ANULUJ SUBSKRYPCJĘ" },
            { "Text.Editor.UnsubscribeTitle", "ANULUJ SUBSKRYPCJĘ/USUŃ" },
            { "Text.Editor.UnsubscribeBody", "Czy na pewno? Nie będziesz mógł grać w to więzienie po anulowaniu subskrypcji." },
            { "EscapeMethods.Editor_LandEscape", "Ucieczka pojazdem" },
            { "EscapeMethods.Editor_SeaEscape", "Ucieczka wodna" },
            { "EscapeMethods.Editor_AirEscape", "Ucieczka powietrzna" },
            { "TBC", "Opis więzienia" },
            { "Text.Editor.Difficulty_Easy.Desc", "Łatwy - Bardziej wyrozumiałe doświadczenie. Biurka zawierają więcej przedmiotów. Zaczynasz z wyższymi statystykami, a strażnicy i więźniowie są słabsi i mają lepszą opinię o tobie."},
            { "Text.Editor.Difficulty_Normal.Desc", "Średni - Wyzwanie, ale uczciwe. Standardowe doświadczenie The Escapists." },
            { "Text.Editor.Difficulty_Hard.Desc", "Trudny - Ostateczna kara! Biurka zawierają mniej przedmiotów. Zaczynasz z niższymi statystykami, a strażnicy i więźniowie są silniejsi i mają gorszą opinię o tobie."},
            { "Text.Editor.Door_Purple_OneWay.Desc", "Staje się drzwiami jednokierunkowymi podczas ciszy nocnej. Wykończone w kolorze fioletowym więźnia." },
            { "Text.Editor.BrushError.Invalid", "To jest <color=#fdcd01>nieprawidłowa pozycja kafla</color>." },
            { "Text.Editor.BrushError.NoClearance", "Bliski przedmiot <color=#fdcd01>wymaga uprawnień</color>." },
            { "Text.Editor.BrushError.InsideRequired", "Ten przedmiot musi być umieszczony na kaflu <color=#fdcd01>wewnętrznym</color>." },
            { "Text.Editor.BrushError.InsideAboveRequired", "Kafel <color=#fdcd01>wewnętrzny</color> jest wymagany <color=#fdcd01>powyżej</color> tej pozycji." },
            { "Text.Editor.BrushError.InsideBelowRequired", "Kafel <color=#fdcd01>wewnętrzny</color> jest wymagany <color=#fdcd01>poniżej</color> tej pozycji." },
            { "Text.Editor.BrushError.OutsideRequired", "Ten przedmiot musi być umieszczony na kaflu <color=#fdcd01>zewnętrznym</color>." },
            { "Text.Editor.BrushError.OutsideAboveRequired", "Kafel <color=#fdcd01>zewnętrzny</color> jest wymagany <color=#fdcd01>powyżej</color> tej pozycji." },
            { "Text.Editor.BrushError.OutsideBelowRequired", "Kafel <color=#fdcd01>zewnętrzny</color> jest wymagany <color=#fdcd01>poniżej</color> tej pozycji." },
            { "Text.Editor.BrushError.Blocked", "Podświetlony kafel już zawiera obiekt." },
            { "Text.Editor.BrushError.BlockedBelow", "Obiekt <color=#fdcd01>lub pokój</color> na piętrze <color=#fdcd01>poniżej</color> blokuje umieszczenie tutaj." },
            { "Text.Editor.BrushError.BlockedAbove", "Obiekt <color=#fdcd01>lub pokój</color> na piętrze <color=#fdcd01>powyżej</color> blokuje umieszczenie tutaj." },
            { "Text.Editor.BrushError.RoomBlocked", "Podświetlony kafel już zawiera obiekt." },
            { "Text.Editor.BrushError.OutOfBounds", "Ta pozycja kafla jest <color=#fdcd01>poza granicami</color>." },
            { "Text.Editor.BrushError.OutOfStock", "Osiągnąłeś maksymalną ilość tego typu elementów na poziomie." },
            { "Text.Editor.BrushError.InvalidFloor", "Ten pokój nie może być umieszczony na wybranym piętrze." },
            { "Text.Editor.Copy", "KOPIUJ" },
            { "Text.Editor.Copy.Message", "Ustaw ten blok jako pędzel do rysowania." },
            { "Text.Editor.Delete.Message", "Usuń ten blok z poziomu." },
            { "Text.Editor.Move", "PRZENIEŚ" },
            { "Text.Editor.Move.Message", "Podnieś ten blok, aby go przesunąć." },
            { "Text.Escape.Submarine.ProximityDialogue", "Nie mogę samodzielnie odpłynąć!" },
            { "Text.HowToplayEditor.Title_01", "Podstawowe sterowanie" },
            { "Text.HowToplayEditor.Instruction_001", "[Lewy przycisk myszy] – Zaznacz / Umieść" },
            { "Text.HowToplayEditor.Instruction_002", "[Prawy przycisk myszy] – Usuń" },
            { "Text.HowToplayEditor.Instruction_003", "[Środkowy przycisk myszy] / [W, A, S, D] – Przesuń kamerę" },
            { "Text.HowToplayEditor.Instruction_004", "[TAB] – Wybierz różne rotacje lub warianty prawidłowych pokoi / obiektów" },
            { "Text.HowToplayEditor.Instruction_005", "[ESC] – Odznacz kafel" },
            { "Text.HowToplayEditor.Title_02", "Kafle pięter" },
            { "Text.HowToplayEditor.Instruction_006", "Menu “Inside” i “Outside” zawiera kafle, które można malować na każdym piętrze więzienia." },
            { "Text.HowToplayEditor.Instruction_007", "Kliknij i przeciągnij, aby utworzyć zaznaczenie pokazujące, gdzie kafel zostanie zastosowany. Puść przycisk myszy, aby zatwierdzić." },
            { "Text.HowToplayEditor.Instruction_008", "Aby budować na wyższych piętrach, podświetlona pozycja kafla musi zawierać kafel “Inside” na piętrze poniżej."},
            { "Text.HowToplayEditor.Title_03", "Pokoje" },
            { "Text.HowToplayEditor.Instruction_009", "Różne wstępnie zaprojektowane pokoje znajdują się w menu “Rooms”." },
            { "Text.HowToplayEditor.Instruction_010", "Pokoje umieszcza się w więzieniu, wybierając pokój z menu i klikając lewym przyciskiem myszy w wybranym miejscu." },
            { "Text.HowToplayEditor.Instruction_011", "Niektóre pokoje są obowiązkowe. Są one wymienione w menu “Checklist” (dolny prawy róg) i można je wybrać bezpośrednio z tego menu." },
            { "Text.HowToplayEditor.Instruction_012", "Uwaga: pokoje nie mogą być modyfikowane, a obiektów nie można dodawać do nich." },
            { "Text.HowToplayEditor.Title_04", "Obiekty" },
            { "Text.HowToplayEditor.Instruction_013", "Funkcjonalne i dekoracyjne obiekty znajdują się w menu “Objects”." },
            { "Text.HowToplayEditor.Instruction_014", "Obiekty umieszcza się w więzieniu, wybierając obiekt z menu i klikając lewym przyciskiem myszy w wybranym kaflu." },
            { "Text.HowToplayEditor.Instruction_015", "Każdy kafel może pomieścić tylko jeden obiekt." },
            { "Text.HowToplayEditor.Instruction_016", "Niektóre obiekty mogą zajmować kilka pięter (np. “Schody”)." },
            { "Text.HowToplayEditor.Title_05", "Ucieczki" },
            { "Text.HowToplayEditor.Instruction_017", "Gracze mogą uciec z obwodu więzienia." },
            { "Text.HowToplayEditor.Instruction_018", "Zablokuj ucieczki poprzez obwód, umieszczając “Wodę” wokół więzienia. Znajdziesz ją w menu “Outside”." },
            { "Text.HowToplayEditor.Instruction_019", "Pojazdy ucieczki można umieścić w więzieniu. Znajdują się one w menu “Rooms”." },
            { "Text.HowToplayEditor.Title_06", "Piętra" },
            { "Text.HowToplayEditor.Instruction_020", "Kliknij dowolny przycisk w menu pięter (prawy górny róg), aby rozpocząć edycję tego piętra." },
            { "Text.HowToplayEditor.Instruction_021", "Budowanie na “Piętrze 2” i “Dachu” jest możliwe tylko, jeśli pod piętrem znajdują się kafle “Inside” (nie wliczając warstw wentylacji między piętrami)." },
            { "Text.HowToplayEditor.Instruction_022", "Niektóre kafle/pokoje/obiekty można umieszczać tylko na określonych piętrach." },
            { "Text.HowToplayEditor.Title_07", "Wentylacja" },
            { "Text.HowToplayEditor.Instruction_023", "Warstwy “Vent” można wybrać z menu w prawym górnym rogu." },
            { "Text.HowToplayEditor.Instruction_024", "Utwórz wentylację, wybierając kafel “Vent” z menu “Inside”, a następnie rysując układ."},
            { "Text.HowToplayEditor.Instruction_025", "Pod wybranym kaflem musi znajdować się obszar “Inside”, aby można było umieścić kafel “Vent”." },
            { "Text.HowToplayEditor.Instruction_026", "Utwórz wejścia/wyjścia za pomocą obiektu “Vent Cover” z menu “Objects”. Osłony wentylacyjne wymagają miejsca pod nimi."},
            { "Text.HowToplayEditor.Title_08", "Schody" },
            { "Text.HowToplayEditor.Instruction_027", "“Schody” znajdują się w menu “Objects”." },
            { "Text.HowToplayEditor.Instruction_028", "W zależności od edytowanego piętra, możesz wybrać kierunek schodów (w górę lub w dół)."},
            { "Text.HowToplayEditor.Instruction_029", "Po wybraniu, naciśnięcie [TAB] pozwala wybrać rotację schodów."},
            { "Text.HowToplayEditor.Instruction_030", "Schody automatycznie tworzą klatkę schodową na obu piętrach, dlatego musi być miejsce na obu piętrach."},
            { "Text.HowToplayEditor.Title_09", "Harmonogram" },
            { "Text.HowToplayEditor.Instruction_031", "Możesz dostosować godzinny harmonogram więzienia w menu “Routine”." },
            { "Text.HowToplayEditor.Instruction_032", "Niektóre harmonogramy wymagają umieszczenia konkretnego “Pokoju” w więzieniu. Wymóg ten jest wskazany w menu “Checklist”." },
            { "Text.HowToplayEditor.Title_10", "Zestawy przedmiotów" },
            { "Text.HowToplayEditor.Instruction_033", "Niektóre pokoje (np. “Cela więźnia”) zawierają obiekt “Biurko”." },
            { "Text.HowToplayEditor.Instruction_034", "Możesz zmieniać zawartość biurek w menu “Settings”, wybierając różne grupy przedmiotów do rozmieszczenia." },
            { "Text.HowToplayEditor.Instruction_035", "Kategorie, które wybierzesz, wpłyną tylko na część całkowitej zawartości biurek." },
            { "Text.HowToplayEditor.Title_11", "Zapisywanie więzienia" },
            { "Text.HowToplayEditor.Instruction_036", "Kliknięcie przycisku “File Management” pozwoli Ci zapisać więzienie." },
            { "Text.HowToplayEditor.Instruction_037", "“Save” nadpisze istniejący plik zapisu (jeśli istnieje)." },
            { "Text.HowToplayEditor.Instruction_038", "“New Save” utworzy nowy plik zapisu dla Twojego więzienia." },
            { "Text.HowToplayEditor.Instruction_039", "Zmień nazwę, opis i obraz więzienia w menu “Info”." },
            { "Text.HowToplayEditor.Title_12", "Podgląd więzienia" },
            { "Text.HowToplayEditor.Instruction_040", "Kliknięcie przycisku “Prison Check” pozwoli Ci zagrać w więzienie w trybie podglądu (tylko dla jednego gracza)." },
            { "Text.HowToplayEditor.Instruction_041", "Zostaniesz ostrzeżony o wszelkich błędach w więzieniu. Niektóre z nich będą wymagały wprowadzenia zmian przed rozpoczęciem gry." },
            { "Text.HowToplayEditor.Title_13", "Publikowanie więzienia" },
            { "Text.HowToplayEditor.Instruction_042", "Kliknięcie przycisku “Prison Check” pozwoli Ci opublikować więzienie." },
            { "Text.HowToplayEditor.Instruction_043", "Zostaniesz ostrzeżony o wszelkich błędach w więzieniu. Niektóre z nich będą wymagały wprowadzenia zmian przed publikacją." },
            { "Text.HowToplayEditor.Instruction_044", "Dostosuj ustawienia publikacji i wybierz “Publish”." },
            { "Text.HowToplayEditor.Title_14", "Granie w niestandardowe więzienia" },
            { "Text.HowToplayEditor.Instruction_045", "Po opublikowaniu więzienia, można je zagrać z menu [Custom Prisons > My Prisons], samodzielnie lub z przyjaciółmi." },
            { "Text.HowToplayEditor.Instruction_046", "Subskrybuj więzienia społeczności na stronie Steam Workshop i uzyskaj do nich dostęp z menu [Custom Prisons > Subscribed]." },
            { "Text.HowToplayEditor.Instruction_047", "Przeglądaj i dołączaj do sesji niestandardowych więzień z menu [Custom Prisons > Browse Games]." },
            { "Text.HowToplayEditor.Instruction_008b", "Wieże strażnicze będą strzelać tylko do więźniów stojących na kaflach Outside."},
            { "Text.Editor.Menu.HelpUpper", "POMOC" },
            { "Text.Menu.NewAddOn", "Nowy dodatek dostępny" },
            { "Text.Menu.Editor.Welcome", "EDYTOR WIĘZIENIA" },
            { "Text.Editor.MyPrisonsInfo", "Twórz i graj w własne więzienia. Udostępniaj je i hostuj przez Steam Workshop, aby grać z innymi graczami." },
            { "Rattlesnake Spring Update", "" },
            { "Text.Editor.RS.Stone_01.Name", "Kamienie" },
            { "Text.Editor.RS.Cactus_01.Name", "Kaktus" },
            { "Text.Editor.RS.HayCart.Name", "Wóz z sianem" },
            { "Text.Editor.RS.HayBale.Name", "Belka siana" },
            { "Text.Editor.RS.HayPile.Name", "Stos siana" },
            { "Text.Editor.RS.WoodenChair.Name", "Drewniane krzesło" },
            { "Text.Editor.RS.Plant_Tall.Name", "Wysoka roślina" },
            { "Text.Editor.RS.HorseTieUp.Name", "Stojak do przywiązywania koni" },
            { "Text.Editor.RS.Barrel.Name", "Drewniana beczka" },
            { "Text.Editor.RS.Skull.Name", "Czaszka zwierzęca" },
            { "Text.Editor.RS.SignpostSkull.Name", "Tablica ostrzegawcza" },
            { "Text.Editor.RS.Trough.Name", "Koryto" },
            { "Text.Editor.RS.Dead_Bush.Name", "Uschnięty krzak" },
            { "Text.Editor.RS.DeadTree_01.Name", "Uschnięte drzewo" },
            { "Text.Editor.RS.GuardTowerTile.Name", "Drewniana wieża strażnicza" },
            { "Text.Editor.RS.Guard.Name", "Strażnik szeryfa" },
            { "Text.Editor.RS.Stone_01.Desc", "Przeszkoda dla niezdarnych." },
            { "Text.Editor.RS.Cactus_01.Desc", "Nie próbuj przytulać." },
            { "Text.Editor.RS.HayCart.Desc", "Wóz… pełen siana." },
            { "Text.Editor.RS.HayBale.Desc", "Bale siana." },
            { "Text.Editor.RS.HayPile.Desc", "Stos siana." },
            { "Text.Editor.RS.WoodenChair.Desc", "Mało wsparcia dla pleców. Usiądź, aby odzyskać energię." },
            { "Text.Editor.RS.Plant_Tall.Desc", "Piękna wysoka roślina." },
            { "Text.Editor.RS.HorseTieUp.Desc", "Idealny do przywiązania konia. Koń nie wchodzi w zestawie." },
            { "Text.Editor.RS.Barrel.Desc", "Jest pusty, zanim zapytasz." },
            { "Text.Editor.RS.Skull.Desc", "Nieznane szczątki zwierzęce." },
            { "Text.Editor.RS.SignpostSkull.Desc", "Zostałeś ostrzeżony!" },
            { "Text.Editor.RS.Trough.Desc", "Częściowo pojemnik na jedzenie, częściowo wanna." },
            { "Text.Editor.RS.Dead_Bush.Desc", "Strasznie złe miejsce na ukrycie." },
            { "Text.Editor.RS.DeadTree_01.Desc", "Ktoś o to nie zadbał." },
            { "Text.Editor.RS.GuardTowerTile.Desc", "Ci goście strzelają do niegrzecznych więźniów. Trzymaj się z dala od reflektorów w nocy." },
            { "Text.Editor.RS.Guard.Desc", "Nie biorą jeńców. Właściwie to dokładnie to robią."},
            { "Text.Editor.RS.WallTileWhite.Name", "Biały kamienny mur" },
            { "Text.Editor.RS.RoofTile.Name", "Biały dach" },
            { "Text.Editor.RS.DryLandLight.Name", "Suchy ląd (jasny)" },
            { "Text.Editor.RS.DryLandDark.Name", "Suchy ląd (ciemny)" },
            { "Text.Editor.RS.Sand.Name", "Piasek" },
            { "Text.Editor.RS.WhiteTile.Name", "Biała mozaika" },
            { "Text.Editor.RS.WoodenFloorLarge.Name", "Drewniany taras" },
            { "Text.Editor.RS.WallTileWhite.Desc", "Idealne do odbijania intensywnego słońca w południe. Może zostać uszkodzony przez narzędzia do łamania." },
            { "Text.Editor.RS.RoofTile.Desc", "Nie pozostanie tak czysty na długo." },
            { "Text.Editor.RS.DryLandLight.Desc", "Jasna, ale martwa ziemia." },
            { "Text.Editor.RS.DryLandDark.Desc", "Zakurzona, brudna i jałowa."},
            { "Text.Editor.RS.Sand.Desc", "Szorstki, chropowaty i irytujący." },
            { "Text.Editor.RS.WhiteTile.Desc", "Brud nie ma gdzie się schować." },
            { "Text.Editor.RS.WoodenFloorLarge.Desc", "Pełen drzazg." },
            { "Text.Editor.Filter.CenterPerks", "Center Perks" },
            { "Text.Editor.Filter.Rattlesnake", "Rattlesnake Springs" },
            { "Text.Editor.Filter.Theme", "Motyw" },
            { "Text.Editor.MusicTheme", "Ścieżka dźwiękowa więzienia" },
            { "Text.Editor.PrisonOutfits", "Stroje więzienne" },
            { "Text.Editor.UpsellHeader01", "Aktualizacja edytora więzienia" },
            { "Text.Editor.UpsellHeader02", "Pakiet Rattlesnake Springs" },
            { "Text.Editor.UpsellBody01", "Zafunduj więźniom zmianę otoczenia dzięki nowym obiektom, kaflom i pokojom Rattlesnake Springs! Mieszaj nowe i istniejące elementy, aby stworzyć własną unikalną mieszankę kar! Odśwież swoje więzienia lub zacznij od nowa."},
            { "Text.Editor.PrisonSoundtrackDesc", "Ustaw nastrój dzięki ścieżce dźwiękowej z ulubionego motywu więziennego." },
            { "Text.Editor.PrisonOutfitsDesc", "Ubierz więźniów i strażników w stroje z ulubionego motywu więziennego." },
            { "", "stół (2), Stanowisko pracy (1)" },
            { "Text.Editor.Zone.GymEquipment.Name", "Sprzęt siłowni" },
            { "Text.Editor.Zone.SecurityWorkstation.Name", "Stanowisko ochrony" },
            { "Text.Editor.Zone.HeartMonitor.Name", "Monitor serca" },
            { "Text.Editor.Zone.GuardBed.Name", "Łóżko strażnika" },
            { "Text.Editor.Zone.InmateBed.Name", "Łóżko więźnia" },
            { "Text.Editor.Zone.SolitaryBed.Name", "Łóżko w izolatce" },
            { "Text.Editor.Zone.InfirmaryBed.Name", "Łóżko w izbie chorych" },
            { "Text.Editor.Zone.GuardLocker.Name", "Szafka strażnika" },
            { "Text.Editor.Zone.MaintenanceDesk.Name", "Biurko konserwatora" },
            { "Text.Editor.Zone.DogKennel.Name", "Kojec dla psa" },
            { "Text.Editor.Zone.FeedingMat.Name", "Mata do karmienia" },
            { "Text.Editor.Zone.AlertStation.Name", "Stacja alarmowa" },
            { "Text.Editor.Zone.ContrabandDesk.Name", "Biurko kontrabandy" },
            { "Text.Editor.Zone.DrainageHole.Name", "Odpływ" },
            { "Text.Editor.Zone.Generator.Name", "Generator" },
            { "Text.Editor.Zone.FoodSmoker.Name", "Wędzarnia" },
            { "Text.Editor.Zone.Oven.Name", "Piekarnik" },
            { "Text.Editor.Zone.RangeCooker.Name", "Kuchenka" },
            { "Text.Editor.Zone.Sink.Name", "Zlew" },
            { "Text.Editor.Zone.LargeCabinet.Name", "Duża szafka" },
            { "Text.Editor.Zone.MedicDesk.Name", "Biurko medyka" },
            { "Text.Editor.Zone.KitchenWorksurface.Name", "Blat kuchenny" },
            { "Text.Editor.Zone.SmallWorksurface.Name", "Mały blat" },
            { "Text.Editor.Zone.Fridge.Name", "Lodówka" },
            { "Text.Editor.Zone.BlacksmithFinishedContainer.Name", "Pojemnik (Kowal)" },
            { "Text.Editor.Zone.BlacksmithMaterials.Name", "Materiały (Kowal)" },
            { "Text.Editor.Zone.BlacksmithMachine.Name", "Maszyna (Kowal)" },
            { "Text.Editor.Zone.WoodworkFinishedContainer.Name", "Pojemnik (Stolarz)" },
            { "Text.Editor.Zone.WoodworkMaterials.Name", "Materiały (Stolarz)" },
            { "Text.Editor.Zone.WoodworkMachine.Name", "Maszyna (Stolarz)" },
            { "Text.Editor.Zone.RedArrowMarkings.Name", "Czerwone oznaczenia strzałek" },
            { "Text.Editor.Zone.FloorCrack.Name", "Szczelina w podłodze" },
            { "Text.Editor.Zone.WhiteFloorMarkings.Name", "Białe oznaczenia podłogi" },
            { "Text.Editor.Zone.WaterPatch.Name", "Plama brudu" },
            { "Text.Editor.Zone.WaterSpill.Name", "Rozlana woda" },
            { "Text.Editor.Zone.LogPile.Name", "Stos drewna" },
            { "Text.Editor.Zone.MotorbikeEscape.Name", "Ucieczka (Motocykl)" },
            { "Text.Editor.Zone.CarEscape.Name", "Ucieczka (Samochód)" },
            { "Text.Editor.Zone.VanEscape.Name", "Ucieczka (Van)" },
            { "Text.Editor.Zone.BoatEscape.Name", "Ucieczka (Łódź)" },
            { "Text.Editor.Zone.SpeedboatEscape.Name", "Ucieczka (Skuter wodny)" },
            { "Text.Editor.Zone.HelicopterEscape.Name", "Ucieczka (Helikopter)" },
            { "Text.Editor.Zone.Shower.Name", "Prysznic" },
            { "Text.Editor.Zone.JobNoticeBoard.Name", "Tablica ogłoszeń" },
            { "Text.Editor.Zone.BlacksmithTutorialBoard.Name", "Tablica instrukcji kowalstwa" },
            { "Text.Editor.Zone.WoodworkTutorialBoard.Name", "Tablica instrukcji stolarstwa" },
            { "Text.Editor.Zone.GeneratorSwitch.Name", "Wyłącznik generatora" },
            { "Text.Editor.Zone.RollCallPosition.Name", "Pozycja apelu" },
            { "Text.Editor.Zone.RollCallPositionX1.Name", "Pozycja apelu (x1)" },
            { "Text.Editor.Zone.RollCallPositionX6.Name", "Pozycja apelu (x6)" },
            { "Text.Editor.Zone.JobOfficeCounter.Name", "Recepcja biura pracy" },
            { "Text.Editor.Zone.CellBars.Name", "Krata celowa" },
            { "Text.Editor.Zone.GymEquipment.Desc", "Użyj, aby poprawić swoją Siłę i Kondycję." },
            { "Text.Editor.Zone.SecurityWorkstation.Desc", "Silnie chronione hasłem. Głównie do grania w Pasjansa." },
            { "Text.Editor.Zone.HeartMonitor.Desc", "Przydatne, jeśli któryś z więźniów miałby serce!" },
            { "Text.Editor.Zone.GuardBed.Desc", "Z pościelą prosto z pralni. Połóż się, aby odzyskać energię." },
            { "Text.Editor.Zone.InmateBed.Desc", "Świetny sposób na zabicie czasu. Połóż się, aby odzyskać energię." },
            { "Text.Editor.Zone.SolitaryBed.Desc", "Ledwo nadaje się do spania. Połóż się, aby odzyskać energię." },
            { "Text.Editor.Zone.InfirmaryBed.Desc", "Komfort prawie wart tego, by dać się pobić. Połóż się, aby odzyskać energię." },
            { "Text.Editor.Zone.GuardLocker.Desc", "Bo strażnicy mają życie poza więzieniem." },
            { "Text.Editor.Zone.MaintenanceDesk.Desc", "Nigdy nie możesz znaleźć potrzebnego narzędzia!" },
            { "Text.Editor.Zone.DogKennel.Desc", "Miejsce, gdzie psy śpią." },
            { "Text.Editor.Zone.FeedingMat.Desc", "Ulubione miejsce psa!" },
            { "Text.Editor.Zone.AlertStation.Desc", "Trzymaj strażników z dala, jeśli chcesz, by Twoje kopanie pozostało niezgłoszone." },
            { "Text.Editor.Zone.ContrabandDesk.Desc", "Najlepiej trzymać z dala od więźniów! Zawiera skonfiskowane przedmioty." },
            { "Text.Editor.Zone.DrainageHole.Desc", "Zatkane włosami." },
            { "Text.Editor.Zone.Generator.Desc", "Połącz z pobliskim Wyłącznikiem Generatora. Niezbędny do zasilania sprzętu ochrony więzienia." },
            { "Text.Editor.Zone.FoodSmoker.Desc", "Dodaje smaku nawet najbardziej zwykłym potrawom!" },
            { "Text.Editor.Zone.Oven.Desc", "Produkuje niezwykle przeciętne jedzenie!" },
            { "Text.Editor.Zone.RangeCooker.Desc", "Drogi sprzęt, by kucharze wyglądali profesjonalnie!" },
            { "Text.Editor.Zone.Sink.Desc", "Czyja kolej na mycie naczyń?" },
            { "Text.Editor.Zone.LargeCabinet.Desc", "Przesadnie duża i nic ważnego w niej nie ma." },
            { "Text.Editor.Zone.MedicDesk.Desc", "Zestaw medyczny na wynos!" },
            { "Text.Editor.Zone.KitchenWorksurface.Desc", "Nowoczesna powierzchnia do przygotowywania jedzenia." },
            { "Text.Editor.Zone.SmallWorksurface.Desc", "Pasuje nawet do najmniejszych przestrzeni roboczych." },
            { "Text.Editor.Zone.Fridge.Desc", "Nigdy nie wypełniona dobrej jakości produktami." },
            { "Text.Editor.Zone.BlacksmithFinishedContainer.Desc", "Przechowuje pamiątkowe talerze. Używane w pracy Kowala." },
            { "Text.Editor.Zone.BlacksmithMaterials.Desc", "Zawiera arkusze metalu. Używane w pracy Kowala." },
            { "Text.Editor.Zone.BlacksmithMachine.Desc", "Maszyna do hartowania. Używana w pracy Kowala." },
            { "Text.Editor.Zone.WoodworkFinishedContainer.Desc", "Przechowuje meble. Używane w pracy Stolarza." },
            { "Text.Editor.Zone.WoodworkMaterials.Desc", "Zawiera materiały do mebli. Używane w pracy Stolarza." },
            { "Text.Editor.Zone.WoodworkMachine.Desc", "Maszyna wykończeniowa. Używana w pracy Stolarza." },
            { "Text.Editor.Zone.RedArrowMarkings.Desc", "Oznaczenia na podłodze wskazujące kierunek." },
            { "Text.Editor.Zone.FloorCrack.Desc", "Ktoś powinien to zasypać." },
            { "Text.Editor.Zone.WhiteFloorMarkings.Desc", "Czasem lepiej narysować linię." },
            { "Text.Editor.Zone.WaterPatch.Desc", "Co za bałagan!" },
            { "Text.Editor.Zone.WaterSpill.Desc", "Ktoś naprawdę powinien to posprzątać!" },
            { "Text.Editor.Zone.LogPile.Desc", "Starannie ułożony stos świeżo ściętych kłód." },
            { "Text.Editor.Zone.MotorbikeEscape.Desc", "Ucieknij w stylu! Użyj, aby opuścić więzienie." },
            { "Text.Editor.Zone.CarEscape.Desc", "Twój bilet wyjścia! Użyj, aby opuścić więzienie." },
            { "Text.Editor.Zone.VanEscape.Desc", "Duży, ale niezawodny! Użyj, aby opuścić więzienie." },
            { "Text.Editor.Zone.BoatEscape.Desc", "Odpłyń ku zachodzącemu słońcu! Użyj, aby opuścić więzienie." },
            { "Text.Editor.Zone.SpeedboatEscape.Desc", "Prawie jak Delfin! Użyj, aby opuścić więzienie." },
            { "Text.Editor.Zone.HelicopterEscape.Desc", "Stylowa ucieczka! Użyj, aby opuścić więzienie." },
            { "Text.Editor.Zone.Shower.Desc", "W dobry dzień woda nie jest nawet zimna! Użyj, aby odzyskać energię." },
            { "Text.Editor.Zone.JobNoticeBoard.Desc", "Lista prac więziennych i osób odpowiedzialnych za nie." },
            { "Text.Editor.Zone.BlacksmithTutorialBoard.Desc", "Zawiera instrukcje wykonywania pracy Kowala." },
            { "Text.Editor.Zone.WoodworkTutorialBoard.Desc", "Zawiera instrukcje wykonywania pracy Stolarza." },
            { "Text.Editor.Zone.GeneratorSwitch.Desc", "Wyłącza pobliski Generator. Użyj, aby odciąć zasilanie sprzętu ochrony więzienia." },
            { "Text.Editor.Zone.RollCallPosition.Desc", "Więźniowie będą ustawieni w tych pozycjach podczas apelu." },
            { "Text.Editor.Zone.JobOfficeCounter.Desc", "Zarabiaj, siedząc i rozmawiając. Łatwiejsze niż praca!" },
            { "Text.Editor.Zone.CellBars.Desc", "Stalowe kraty odporne na więźniów." },
            { "Text.Editor.Zone.Error.IncorrectQuantity", "Nieprawidłowa ilość jednego lub więcej wymaganych obiektów." },
            { "Text.Editor.Zone.Error.InsideOutside", "Kafle podłogowe w tej Strefie muszą być tego samego typu (Inside lub Outside)." },
            { "Text.Editor.Zone.Error.BlockedObject", "Wymagany obiekt nie jest osiągalny z Strefy Apelu." },
            { "Text.Editor.Zone.Error.HalfInAndOut", "Wymagane obiekty nie mogą przekraczać granicy Strefy." },
            { "Text.Editor.Zone.Error.IslandsNotAllowed", "Strefy muszą składać się z jednej, ciągłej powierzchni." },
            { "Text.Editor.Zone.Error.HolesNotAllowed", "Strefy nie mogą mieć luk w środku." },
            { "Text.Editor.Zone.Error.BrushOverZone", "Strefa w tym pokoju nie może nadpisać innej strefy." },
            { "Text.Editor.Zone.Error.OverEmptySpace", "Strefy mogą być tworzone tylko tam, gdzie są kafle podłogowe (Inside lub Outside)." },
            { "Text.Editor.Zone.Error.OverZone", "Strefy nie mogą nachodzić na siebie." },
            { "Text.Editor.Error.TooManyRoomType", "Masz za dużo: %Object%" },
            { "Text.Editor.StopEditing.Message", "Zakończ edycję tej strefy. Możesz ją edytować później." },
            { "Text.Editor.StopEditing", "Zakończ edycję" },
            { "Text.Editor.Zones", "STREFY" },
            { "Text.Editor.Structural", "KONSTRUKCYJNE" },
            { "Text.Editor.Zone.EditZone", "Edytuj Strefę" },
            { "Text.Editor.Zone.DeleteZone", "Usuń Strefę" },
            { "Text.Editor.Zone.EditZone.Desc", "Edytuj kształt tej strefy. Strefy muszą być jedną, ciągłą powierzchnią bez luk w środku." },
            { "Text.Editor.Zone.DeleteZone.Desc", "Usuń tę strefę. Zawartość strefy nie zostanie usunięta." },
            { "Text.Editor.Zone.SetAsActiveZone", "Wybierz tę strefę." },
            { "Text.Editor.Zone.DeselectZone", "Odznacz tę strefę." },
            { "Text.Editor.Zone.InsideDesc", "Kafle podłogowe Inside pozwalają budować na piętrze powyżej." },
            { "Text.Editor.Zone.OutsideDesc", "Więźniowie na kaflach Outside mogą być wykryci przez reflektory Wieży Strażniczej po Lights Out. Nie można budować na piętrze nad kaflem Outside." },
            { "Text.Editor.Zone.CreateNewZone", "Utwórz nową strefę" },
            { "Text.Editor.Zone.CurrentlySelected", "AKTUALNY WYBÓR" },
            { "Text.Editor.Zone.InvalidZoneDesc", "Ta strefa jest nieprawidłowa. Popraw następujące problemy:" },
            { "Text.Editor.Zone.ValidZoneDesc", "Ta strefa spełnia wszystkie wymagania!" },
            { "Text.Editor.Zone.NoZoneSelected", "Nie wybrano strefy" },
            { "Text.Editor.Zone.SelectAZone", "Aby wybrać strefę, kliknij ikonę strefy lub użyj Środkowego Przycisku Myszy podczas zaznaczenia strefy." },
            { "Text.Editor.Zone.RequiredObjects", "WYMAGANE" },
            { "Text.Editor.Zone.Recommended", "ZALECANE" },
            { "Text.Editor.Zone.RequiredDesc", "Musisz spełnić wymagania obiektów strefy, aby była ona prawidłowa." },
            { "Text.Editor.Zone.Boundaries", "GRANICE" },
            { "Text.Editor.Zone.Inside", "INSIDE" },
            { "Text.Editor.Zone.Outside", "OUTSIDE" },
            { "Text.SelectZoneToCreate", "Wybierz strefę" },
            { "Text.Editor.Zone.ObjectFamily01", "PODSTAWY" },
            { "Text.Editor.Zone.ObjectFamily02", "BIURKA" },
            { "Text.Editor.Zone.ObjectFamily03", "DRZWI" },
            { "Text.Editor.Zone.ObjectFamily04", "ŁÓŻKA" },
            { "Text.Editor.Zone.ObjectFamily05", "OCHRONA" },
            { "Text.Editor.Zone.ObjectFamily06", "UCIECZKI" },
            { "Text.Editor.Zone.ObjectFamily07", "PRACA" },
            { "Text.Editor.Zone.ObjectFamily08", "STOŁY" },
            { "Text.Editor.Zone.ObjectFamily09", "SIEDZENIA" },
            { "Text.Editor.Zone.ObjectFamily10", "ROŚLINY" },
            { "Text.Editor.Zone.ObjectFamily11", "DEKORACJE" },
            { "Text.Editor.Zone.ObjectFamily12", "DEKORACJE PODŁOGI" },
            { "Text.Editor.Zone.ObjectFamily13", "NAWIGACJA" },
            { "Text.Editor.Zone.Help.01", "Większość Pokoi zawiera Strefę. Strefy pozwalają określić funkcjonalność części więzienia." },
            { "Text.Editor.Zone.Help.02", "Strefy pozwalają określić funkcjonalność części więzienia." },
            { "Text.Editor.Zone.Help.03", "Aby utworzyć Strefę, umieść pokój lub wybierz przycisk Utwórz nową strefę w menu Strefy." },
            { "Text.Editor.Zone.Help.04", "Ikona i kolor obramowania Strefy wskazują, czy jest prawidłowa (niebieska) czy nieprawidłowa (czerwona). Wybrane Strefy mają żółte obramowanie." },
            { "Text.Editor.Zone.Help.05", "Kliknij ikonę Strefy lub użyj Środkowego Przycisku Myszy, aby ją wybrać. Umożliwi to przeglądanie wymagań i aktualnych błędów Stref w menu Strefy." },
            { "Text.Editor.Zone.Help.06", "Najedź na ikonę Strefy, aby uzyskać dostęp do przycisków Edytuj Strefę i Usuń Strefę." },
            { "Text.Editor.ZoneFE.01", "Teraz możesz tworzyć własne Pokoje lub edytować istniejące za pomocą nowej funkcji Strefy. Użyj Stref, aby określić funkcjonalność części więzienia." },
            { "Text.Editor.ZoneFE.02", "Aktualizacja Strefy" },
            { "Text.Editor.Floor.VentsFamily", "WENTYLACJA" },
            { "Text.Editor.Zone.CreationInProgress", "Tworzenie Strefy w toku…" },
            { "Text.Editor.Zone.Legend.Delete", "Usuń" },
            { "Text.Editor.Zone.Legend.DrawMarquee", "Rysuj" },
            { "Text.Editor.Zone.Legend.Deselect", "Odznacz" },
            { "Text.Editor.Zone.Legend.ZoneAdd", "Dodaj do obszaru Strefy" },
            { "Text.Editor.Zone.Legend.ZoneDelete", "Usuń obszar Strefy" },
            { "Text.Editor.Zone.Legend.ZoneSelectDeselect", "Wybierz / Odznacz Strefę" },
            { "Text.Editor.Zone.Legend.ZoneDeselect", "Odznacz Strefę" },
            { "Text.Editor.Zone.Legend.Place", "Umieść" },
            { "Text.Editor.Zone.Legend.DrawZone", "Rysuj Strefę" },
            { "Text.Editor.Zone.Legend.Select", "Wybierz" },
            { "Text.Editor.Zone.Legend.PanCameraHold", "Przesuwaj Kamerę (przytrzymaj)" },
            { "Text.Editor.Zone.Legend.DeleteArea", "Usuń obszar" },
            { "Text.Editor.Zone.Legend.DrawDrag", "Rysuj obszar" },
            { "Text.Editor.Zone.Legend.Cancel", "Anuluj" },
            { "Text.Editor.Zone.Legend.ChooseVariation", "Następna wariacja" },
            { "Text.Editor.Zone.Legend.Rotate", "Obróć" },
            { "Text.Editor.Zone.Legend.ZoomScroll", "Zoom (Scroll)" },
            { "Text.Editor.Zone.Help.07", "Menu Konstrukcyjne zawiera kafle podłogowe Inside i Outside." },
            { "Text.Editor.Zone.Help.08", "Kliknij ikonę Strefy lub użyj Środkowego Przycisku Myszy, aby wybrać Strefę." },
            { "Text.Editor.Zone.Help.09", "Zabezpiecz więzienie przed ucieczką, umieszczając Wodę wokół więzienia. Opcja dostępna w menu Konstrukcyjne." },
            { "Text.Editor.Zone.Help.10", "Utwórz wentyl, wybierając kafel Vent w menu Konstrukcyjne, a następnie narysuj jego układ." },
            { "Text.Editor.Zone.Help.11", "Niektóre Strefy są obowiązkowe. Zostały wymienione w menu Checklist (prawy dolny róg)." },
            { "Text.Editor.Zone.ErrorPreview.01", "Nieprawidłowa ilość Stref: %Object%" },
            { "Text.Error.CantBeReached", "Nie można dotrzeć do Strefy: %Object%" },
            { "Text.Error.Invalid", "Nieprawidłowa Strefa: %Object%" },
            { "Text.Error.Zone.ShowErrors", "Kliknij, aby zobaczyć błędy Strefy." },
            { "Text.Editor.Zone.InOutError_01", "Ta Strefa będzie oświetlona światłem Inside ponieważ zawiera więcej kafli Inside niż Outside." },
            { "Text.Editor.Zone.InOutError_02", "Ta Strefa będzie oświetlona światłem Outside ponieważ zawiera więcej kafli Outside niż Inside." },
            { "Text.Editor.Zone.InOutWarning", "Ostrzeżenie" },
            { "Text.Editor.Toilet.Name", "Toaleta" },
            { "Text.Editor.Toilet.Desc", "Spuszczanie rzeczy w toalecie często powoduje zatory." },
            { "Text.Editor.Solitary_Potatoes.Name", "Samotne Ziemniaki" },
            { "Text.Editor.Solitary_Potatoes.Desc", "Jeden ziemniak, dwa ziemniaki, trzy ziemniaki, cztery…" },
            { "Text.Editor.Zone.InOutError_03", "Oświetlenie Inside - Ta Strefa zawiera więcej kafli Inside niż Outside." },
            { "Text.Editor.Zone.InOutError_04", "Oświetlenie Outside - Ta Strefa zawiera więcej kafli Outside niż Inside." },
            { "Text.Editor.Zone.ClickSelectZone", "Kliknij, aby wybrać Strefę." },
            { "Text.Editor.Zone.ClickDeselectZone", "Kliknij, aby odznaczyć Strefę." },
            { "Text.Editor.ZonesLowerCase", "strefy" }
        };
    }
}
