using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TE2PolishLocalizationNamespace
{
    public static class EscapeMethods
    {
        public static readonly Dictionary<string, string> Data = new Dictionary<string, string>
        {
            { "EscapeMethods.TakeControlOfShip", "Przejmij kontrolę nad statkiem" },
            { "EscapeMethods.Crate", "Ostatni post" },
            { "EscapeMethods.Dictator_StolenHelicopter", "Wsiadaj do śmigłowca!" },
            { "EscapeMethods.DisconnectGuardsCar", "Odłącz wagon strażników" },
            { "EscapeMethods.Documentary", "Poznaj załogę" },
            { "EscapeMethods.Dolphin", "Pływanie z delfinami" },
            { "EscapeMethods.EscapePod", "Groszek w strąku" },
            { "EscapeMethods.FeignDeath", "Sprawa nierozwiązana" },
            { "EscapeMethods.ForceEmergencyLanding", "Paszport do wolności" },
            { "EscapeMethods.Glider", "Szybowanie do zwycięstwa" },
            { "EscapeMethods.GrappleGantry", "Uzależniony od ciebie" },
            { "EscapeMethods.HorseEscape", "Mój mały szelma" },
            { "EscapeMethods.HumanDisguise", "Jestem tylko człowiekiem" },
            { "EscapeMethods.Jetpack", "Wyścig z kosmosu" },
            { "EscapeMethods.Raft", "Spłyń na wolność" },
            { "EscapeMethods.Motocykl", "Prędki McQueen" },
            { "EscapeMethods.MultiplayerTrashBag", "Wynieś śmieci" },
            { "EscapeMethods.NothingSpecial", "Ucieczka z obwodu" },
            { "EscapeMethods.Parachute", "Samolotowy szał" },
            { "EscapeMethods.ScubaGear", "Scuba Doo" },
            { "EscapeMethods.Sewers", "Rock-Hammer Hard Place" },
            { "EscapeMethods.SingleplayerTrashBag", "Trash Talk" },
            { "EscapeMethods.StolenJeep", "Zabawa z Jeepami" },
            { "EscapeMethods.StolenJetski", "Pomachaj na pożegnanie!" },
            { "EscapeMethods.Submarine", "Złe intencje" },
            { "EscapeMethods.TakeControlLocomotive", "Przejmij lokomotywę" },
            { "EscapeMethods.TakeControlPlane", "Odzyskaj kontrolę" },
            { "EscapeMethods.Boat_StolenHelicopter", "Mistrzowie iluzji" },
            { "EscapeMethods.UFO", "Obca technologia…" },
            { "EscapeMethods.Unknown", "Świetna robota!" },
            { "EscapeMethods.Zipline", "Zapnij pasy" },
            { "EscapeMethods.DLC02_Single", "Sprawa grobowa" },
            { "EscapeMethods.DLC02_MultiPlayer", "Potworny Mix" },
            { "EscapeMethods.DLC03_Single", "Na szczycie listy niegrzecznych" },
            { "EscapeMethods.DLC03_Multi", "Za tobą!" },
            { "EscapeMethods.DLC04_Single", "To długa droga" },
            { "EscapeMethods.DLC04_Multi", "Sprytny Kupiec" },
            { "EscapeMethods.DLC05_Single", "Tylko zadrapanie" },
            { "EscapeMethods.DLC05_Multi", "Zdobyć Dzień" },
            { "EscapeMethods.DLC06_Single", "To nie zabawka, to kolekcjonerski egzemplarz" },
            { "EscapeMethods.DLC06_Multi", "Baterie nie dołączone" },

            { "Text.Milestone.Area17.Escape1", "Przerwanie Obwodu" },
            { "Text.Milestone.Area17.Escape2", "Jestem tylko człowiekiem" },
            { "Text.Milestone.Area17.Escape3", "Technologia Obcych…" },
            { "Text.Milestone.Boat.Escape1", "Nurkowanie Doo" },
            { "Text.Milestone.Boat.Escape2", "Pożegnanie falą!" },
            { "Text.Milestone.Boat.Escape3", "Mistrzowie Iluzji" },
            { "Text.Milestone.Boat.Escape4", "Odzyskiwanie kontroli" },
            { "Text.Milestone.CenterPerks.Escape1", "Przerwanie Obwodu" },
            { "Text.Milestone.CenterPerks.Escape2", "Poznaj załogę" },
            { "Text.Milestone.CenterPerks.Escape3", "Ostatni Post" },
            { "Text.Milestone.Gulag.Escape1", "Przerwanie Obwodu" },
            { "Text.Milestone.Gulag.Escape2", "Młot skalny w trudnym miejscu" },
            { "Text.Milestone.Gulag.Escape3", "Zabawa z Jeepami" },
            { "Text.Milestone.OilRig.Escape1", "Przerwanie Obwodu" },
            { "Text.Milestone.OilRig.Escape2", "Gadaj śmieciami" },
            { "Text.Milestone.OilRig.Escape3", "Złe intencje" },
            { "Text.Milestone.OilRig.Escape4", "Pływanie z delfinami" },
            { "Text.Milestone.Plane.Escape1", "Paszport do wolności" },
            { "Text.Milestone.Plane.Escape2", "Samolotowe szaleństwo" },
            { "Text.Milestone.Plane.Escape3", "Odzyskaj kontrolę" },
            { "Text.Milestone.Plane.Escape4", "Płynna podróż samolotem" },
            { "Text.Milestone.POW.Escape1", "Przerwanie Obwodu" },
            { "Text.Milestone.POW.Escape2", "Speed McQueen" },
            { "Text.Milestone.POW.Escape3", "Ślizg do zwycięstwa" },
            { "Text.Milestone.Space.Escape1", "Przerwanie Obwodu" },
            { "Text.Milestone.Space.Escape2", "Wyścig z kosmosu" },
            { "Text.Milestone.Space.Escape3", "Groszek w strąku" },
            { "Text.Milestone.Train.Escape1", "Mój mały oszust" },
            { "Text.Milestone.Train.Escape2", "Złapany na haczyk" },
            { "Text.Milestone.Train.Escape3", "Zrób Lokomotywę" },
            { "Text.Milestone.Train.Escape4", "Luźny Wagon" },
            { "Text.Milestone.WildWest.Escape1", "Przerwanie Obwodu" },
            { "Text.Milestone.WildWest.Escape2", "Zapinanie linki!" },
            { "Text.Milestone.WildWest.Escape3", "Wyrzuć śmieci" },

            { "Text.InmateHint.Perks.Title", "Wiadomość od przyjaciela…" },
            { "Text.InmateHint.Perks.A", "To dobre miejsce do kopania, strażnicy tu nigdy nie wchodzą (chyba że zostaniesz tu ścigany!) Nie zapomnij ukryć wejść do tunelu, stawiając na nich biurka…\\n\\nDo kopania używaj narzędzi takich jak łopata, kilof i kielnia." },
            { "Text.InmateHint.Perks.B", "Nigdy nie widziałem, aby strażnik tu wszedł, to tylko magazyn, który nigdy nie jest używany. Może być dobrym miejscem do kopania? Do tego przyda się solidna łopata. Sprawdź w menu rzemiosła mocniejsze wersje narzędzi!" },
            { "Text.InmateHint.Perks.C", "Za podwójnymi drzwiami jest salon, gdzie ekipa kamerowa odpoczywa, gdy nie nagrywa. Mogli zostawić sprzęt, który można 'pożyczyć'…" },
            { "Text.InmateHint.Perks.D", "Za tą ścianą wysyłają wielkie palety z więźniowskimi butami… duże, ludzkie palety. Potrzebna będzie pomoc, bo ciężkie drzwi żaluzjowe są za ciężkie, aby jedna osoba je otworzyła." },
            { "Text.InmateHint.Perks.E", "To idealne miejsce, aby wykopać się z więzienia! Możesz stworzyć fałszywy blok ściany lub plakat, aby ukryć ściany, które wykopałeś - szczególnie przydatne w celi.\\n\\nDo kucia używaj kilofa, łopaty i łomu." },
            { "Text.InmateHint.Perks.F", "Strażnicy nie patrolują przy tym ogrodzeniu… to doskonałe miejsce do cięcia. Uważaj jednak, strażnicze wieże będą obserwować wszelkie manipulacje przy ogrodzeniach w ciągu dnia.\\n\\nDo cięcia używaj nożyc, pilnika i nici tnącej." },
            { "Text.InmateHint.Rattlesnake.Title", "Trochę pomocy dla was..." },
            { "Text.InmateHint.Rattlesnake.A", "Nie widziałem, aby ktokolwiek z personelu tu zaglądał! To może być dobre miejsce do kopania w kierunku kopalni…" },
            { "Text.InmateHint.Rattlesnake.C", "Nie zapomnij użyć mapy, aby szukać miejsc do wykorzystania… są małe budynki poza więzieniem, ale wciąż w obrębie ogrodzenia. Nikt tam nie wchodził, mogą być dobrym przystankiem dla kopiących tunel." },
            { "Text.InmateHint.POW.Title", "Dziennik…" },
            { "Text.InmateHint.POW.A", "Obserwuję to miejsce od kilku dni. Jeszcze nie zauważyłem strażnika wchodzącego. Zaznaczam jako możliwe miejsce do kopania." },
            { "Text.InmateHint.POW.C", "Duży magazyn. Blisko generatora. Strażnicy jeszcze tu nie wchodzili." },
            { "Text.InmateHint.Offshore.Title", "Zaginiony na morzu?" },
            { "Text.InmateHint.Offshore.A", "Na południowo-wschodnim końcu bazy przycumowana jest łódź, ale za elektrycznym ogrodzeniem… Potrzebujesz narzędzi do cięcia, klucza, aby tam się dostać, i przełączyć generator, aby wyłączyć ogrodzenie!" },
            { "Text.InmateHint.Offshore.C", "Na dole schodów jest gantry do mniejszej platformy, gdzie mieszkają strażnicy. Mają całkiem dobre życie, w tym przycumowaną łódź! Ryzykowne, ale jeśli stworzysz klucze do kwater strażników i wejdziesz w głąb platformy, prawdopodobnie znajdziesz sposób, aby dostać się do łodzi…" },
            { "Text.InmateHint.Tundra.Title", "Spójrzcie, towarzysze…" },
            { "Text.InmateHint.Tundra.A", "Ktoś z nas dostał się do kuchni, okazuje się, że jest blisko zewnętrznego ogrodzenia! Zdobądź zielony klucz i wejście do kuchni będzie dziecinnie proste, personel kuchni zarabia za mało, aby się przejmować. To dobre miejsce do kopania…" },
            { "Text.InmateHint.Tundra.B", "Nie widzieliśmy strażników wchodzących tutaj, prawdopodobnie bo nie jest tu cieplej niż na zewnątrz… mimo to, to dobre miejsce do kopania z dala od ciekawskich oczu!" },
            { "Text.InmateHint.A17.Title", "Tylko dla nieziemskich oczu!" },
            { "Text.InmateHint.A17.A", "Nie zauważono jeszcze ludzi wchodzących w to miejsce, przydatne będą narzędzia do przesuwania ziemi." },
            { "Text.InmateHint.Anomaly.Title", "RAPORT SYMULACJI" },
            { "Text.InmateHint.Anomaly.A", "TEST – SYMULACJA UCIECZKI 105.B – Lądowisko 2 \\n\\n WYKRYTO WYKORZYSTANIE: Ogrodzenie i kontenery blokują patrole strażników do lądowiska. Nie można w pełni patrolować ani skanować całego obszaru." },
            { "Text.InmateHint.Anomaly.B", "TEST – SYMULACJA UCIECZKI 23.A – Lądowisko 1 \\n\\n Drzwi zamknięte. Aktywne detektory kontrabandy. Stan ogrodzenia: nominalny. \\n\\nObszar zabezpieczony. Patrole strażników nie są konieczne." },
        };
    }
}
