using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TE2PolishLocalizationNamespace
{
    public static class Interface
    {
        public static readonly Dictionary<string, string> Data = new Dictionary<string, string>
        {
            { "Text.Interact.Kennel", "Ukryj" },
            { "Text.Interact.PeelPotatoes", "Obierz ziemniaki" },
            { "Text.Interact.Read", "Ucz się" },
            { "Text.Visitor.AreaBanterJoin", "Jeszcze jedno…" },
            { "HUD.Interact.Job.BlacksmithStepA", "Arkusze metalu" },
            { "HUD.Interact.Job.BlacksmithStepB", "Maszyna do hartowania" },
            { "HUD.Interact.Job.BlacksmithStepC", "Gotowe talerze" },
            { "HUD.Interact.Job.DogBowl", "Miska dla psa" },
            { "HUD.Interact.Job.DogFood", "Karma dla psa" },
            { "HUD.Interact.Job.EngineeringStepA", "Lutownica i okulary ochronne" },
            { "HUD.Interact.Job.FarmingStepA", "Kielnie" },
            { "HUD.Interact.Job.FarmingStepB", "Nasiona" },
            { "HUD.Interact.Job.FarmingStepC", "Uprawy" },
            { "HUD.Interact.Job.GlovesMask", "Rękawiczki i maska" },
            { "HUD.Interact.Job.HeavyDutyProtectors", "Wytrzymałe ochraniacze" },
            { "HUD.Interact.Job.KennelsStepA", "Miski dla psa" },
            { "HUD.Interact.Job.KennelsStepB", "Karma dla psa" },
            { "HUD.Interact.Job.KitchenStepA", "Składniki jedzenia" },
            { "HUD.Interact.Job.KitchenStepB", "Piekarnik" },
            { "HUD.Interact.Job.KitchenStepC", "Gotowe jedzenie" },
            { "HUD.Interact.Job.MailSortingStepA", "Worki pocztowe" },
            { "HUD.Interact.Job.MailSortingStepB", "Maszyna sortująca" },
            { "HUD.Interact.Job.MailSortingStepC", "Posortowane listy" },
            { "HUD.Interact.Job.MiningA", "Wytrzymałe ochraniacze" },
            { "HUD.Interact.Job.PaintingStepA", "Pędzel i farba" },
            { "HUD.Interact.Job.PlumbingStepA", "Tłoki" },
            { "HUD.Interact.Job.ShoemakerStepA", "Podeszwy i ramy" },
            { "HUD.Interact.Job.ShoemakerStepB", "Prasa do butów" },
            { "HUD.Interact.Job.ShoemakerStepC", "Gotowe pary butów" },
            { "HUD.Interact.Job.WasteDisposalStepA", "Maska i rękawice" },
            { "HUD.Interact.Job.WasteDisposalStepB", "Odpady" },
            { "HUD.Interact.Job.WasteDisposalStepC", "Utylizator odpadów" },
            { "HUD.Interact.Job.WoodworkStepA", "Materiały meblowe" },
            { "HUD.Interact.Job.WoodworkStepB", "Maszyna wykończeniowa" },
            { "HUD.Interact.Job.WoodworkStepC", "Meble" },
            { "HUD.Routine.Breakfast", "Czas na śniadanie" },
            { "HUD.Routine.Dinner", "Czas na kolację" },
            { "HUD.Routine.DinnerTime", "Czas kolacji" },
            { "HUD.Routine.Exercise", "Czas na ćwiczenia" },
            { "HUD.Routine.FreeTime", "Czas wolny" },
            { "HUD.Routine.Job", "Czas pracy" },
            { "HUD.Routine.LightsOut", "Gaszenie świateł" },
            { "HUD.Routine.Lockdown", "BLOKADA" },
            { "HUD.Routine.LockdownGrace", "WRÓĆ DO CELI" },
            { "HUD.Routine.LunchTime", "Czas na obiad" },
            { "HUD.Routine.Name", "*Potrzebna nazwa*" },
            { "HUD.Routine.RollCall", "Apel" },
            { "HUD.Routine.Shower", "Czas na prysznic" },
            { "HUD.TransportPrison.TimeLeft", "POZOSTAŁY CZAS" },
            { "Text.Autosave", "Gra zapisuje się automatycznie. Nie wyłączaj gry, gdy widzisz wskaźnik zapisu." },
            { "Text.BLANK", "" },
            { "Text.Calendar.DaysToRelease", "Dni do zwolnienia" },
            { "Text.Calendar.Month", "Miesiąc" },
            { "Text.Cutlery.CulteryDrawer", "Szuflada ze sztućcami" },
            { "Text.Desk.Contents", "Zawartość Biurka" },
            { "Text.Desk.ContrabandDesk", "Biurko Kontrabandy" },
            { "Text.Desk.GuardsDesk", "Biurko Strażnika" },
            { "Text.Desk.HiddenCompartment", "Ukryta Skrytka" },
            { "Text.Desk.MaintenanceDesk", "Biurko Obsługi Technicznej" },
            { "Text.Desk.MedicDesk", "Biurko Medyka" },
            { "Text.Desk.UnownedDesk", "Biurko" },
            { "Text.Dialog.LeaderboardWarning", "OSTRZEŻENIE!" },
            { "Text.Dialog.LeaderboardWarning.Body", "Zmiana trybu gry z Offline na Online spowoduje, że nie będziesz już publikować wyników w rankingach dla pojedynczego gracza. Wyniki będą publikowane w rankingach Multiplayer." },
            { "Text.Dialog.LobbyFull", "OSTRZEŻENIE!" },
            { "Text.Dialog.LobbyFull.Body", "Nie możesz dołączyć do gry, ponieważ sesja jest pełna." },
            { "Text.Dialog.Net.JoinRoom.FailedBody", "Nie możesz dołączyć do gry, ponieważ sesja jest pełna." },
            { "Text.Dialog.Net.JoinRoom.FailedBodyB", "Gra jest zamknięta." },
            { "Text.Dialog.Net.JoinRoom.FailedBodyC", "Nie udało się dołączyć do gry." },
            { "Text.Dialog.Net.JoinRoom.GameFull", "Nie możesz dołączyć do gry, ponieważ sesja jest pełna." },
            { "Text.Dialog.Net.JoinRoom.GameUnavailableBody", "Ta sesja nie jest już dostępna." },
            { "Text.Dialog.NetworkDisconnect.PhotonGame.Body", "Zostałeś rozłączony z usługami online." },
            { "Text.Dialog.NetworkTimeOutDuringLoad", "Nie można dołączyć do sesji. Sprawdź połączenie i spróbuj ponownie." },
            { "Text.Dialog.NotOurQuestItem", "To nie dla mnie!" },
            { "Text.Dialog.Prompt.Cancel", "ANULUJ" },
            { "Text.Dialog.Prompt.No", "NIE" },
            { "Text.Dialog.Prompt.Ok", "OK" },
            { "Text.Dialog.Prompt.Retry", "PONÓW" },
            { "Text.Dialog.Prompt.Yes", "TAK" },

            { "Text.OnlineState.Ingame", "W grze" },
            { "Text.HUD.DeskSearchMessage", "Biurko $CharacterName zostanie przeszukane!" },
            { "Text.Milestone.Dictator.Name", "Chwalebny Reżim" },
            { "Text.Milestone.Dictator.Escape1", "Przebicie się przez granicę" },
            { "Text.Milestone.Dictator.Escape2", "Zamrożona sprawa" },
            { "Text.Milestone.Dictator.Escape3", "Dostań się do helikoptera!" },
            { "Text.Milestone.Halloween.Name", "Przerażający Oddział" },
            { "Text.Milestone.Halloween.Escape1", "Przebicie się przez granicę" },
            { "Text.Milestone.Halloween.Escape2", "Groźna sprawa" },
            { "Text.Milestone.Halloween.Escape3", "Monster Mash" },
            { "Text.PrisonAlert.Contraband.Container", "ponieważ znaleziono kontrabandę w biurku." },
            { "Text.PrisonAlert.Contraband.Person", "ponieważ znaleziono kontrabandę przy więźniu." },
            { "Text.Player.Interactions.OnlyUsableDuringJobtime", "Mogę tego użyć tylko podczas pracy!" },
            { "Text.UI.RussiaRegion", "Azja-2" },
            { "Text.InmateHint.Interaction", "Notatka więźnia" },
            { "Text.InmateHint.Anomaly.Interaction", "Raport bezpieczeństwa" },
            { "Text.Saving.ManualTitle", "RĘCZNY ZAPIS" },
            { "Text.Saving.ManualBody", "Zapisywanie jest obecnie ustawione na RĘCZNE.\\n\\nAby zapisać, użyj łóżka w swojej celi. Tylko własne łóżko można użyć do zapisu. Niezapisane dane zostaną utracone po wyjściu z gry." },
            { "Text.Saving.AutoTitle", "AUTOMATYCZNY ZAPIS" },
            { "Text.Saving.AutoBody", "Zapisywanie jest obecnie ustawione na AUTOMATYCZNE.\\n\\nGra zapisuje się automatycznie na początku każdej rutyny i przy wychodzeniu z więzienia z menu pauzy." },
            { "Text.UI.BedInteraction.Body", "Czy chcesz zapisać aktualny postęp?" },
            { "Text.UI.BedInteraction.Header", "ZAPISZ GRĘ" },
            { "Text.UI.SaveExplanation.Header", "USTAWIENIA ZAPISU" },
            { "Text.Saving.OffBody", "Jako gość w trybie multiplayer online, zapis gry jest domyślnie WYŁĄCZONY. \\n\\nPo włączeniu zapisu wybierz slot zapisu, aby móc kontynuować postęp później, grając samodzielnie lub rozpoczynając nową sesję multiplayer. " },
            { "Text.Saving.OffTitle", "ZAPIS WYŁĄCZONY" },
            { "Text.Difficulty.Easy", "ŁATWY" },
            { "Text.Difficulty.Medium", "ŚREDNI" },
            { "Text.Difficulty.Hard", "TRUDNY" },
            { "Text.FE.KeysRemaining", "Wykonaj jeszcze $keys unikalnych ucieczek, aby odblokować to więzienie!" },
            { "Text.FE.KeyRemaining", "Wykonaj jeszcze $keys unikalną ucieczkę, aby odblokować to więzienie!" },
            { "Text.ItemTooltip.Armour", "Pancerz" },
            { "Text.ItemTooltip.Weapon", "Broń" },
            { "Text.ItemTooltip.Tool", "Narzędzie" },
            { "Text.ItemTooltip.Component", "Komponent" },
            { "Text.ItemTooltip.Consumable", "Zdatne do Spożycia" },
            { "Text.ItemTooltip.Con_AddEnergy", "Zwiększa Energii" },
            { "Text.ItemTooltip.Con_AddHealth", "Zwiększa Zdrowie" },
            { "Text.ItemTooltip.Outfit", "Strój" },
            { "Text.EquipmentStat.N/A", "N/D" },
            { "Text.EquipmentStat.Damage.Low", "Niski" },
            { "Text.EquipmentStat.Damage.Medium", "Średni" },
            { "Text.EquipmentStat.Damage.High", "Wysoki" },
            { "Text.EquipmentStat.AttackSpeed.Low", "Niska" },
            { "Text.EquipmentStat.AttackSpeed.Medium", "Średnia" },
            { "Text.EquipmentStat.AttackSpeed.High", "Wysoka" },
            { "Text.EquipmentStat.Range.Low", "Niski" },
            { "Text.EquipmentStat.Range.Medium", "Średni" },
            { "Text.EquipmentStat.Range.High", "Wysoki" },
            { "Text.EquipmentStat.OutfitType.None", "Brak" },
            { "Text.EquipmentStat.OutfitType.Guard", "Strażnik" },
            { "Text.EquipmentStat.OutfitType.Inmate", "Więzień" },
            { "Text.EquipmentStat.OutfitType.Medic", "Lekarz" },
            { "Text.EquipmentStat.OutfitType.Warden", "Strażnik" },
            { "Text.EquipmentStat.DamageReduction.Unassigned", "N/D" },
            { "Text.EquipmentStat.DamageReduction.Low", "Niskie" },
            { "Text.EquipmentStat.DamageReduction.Medium", "Średnie" },
            { "Text.EquipmentStat.DamageReduction.High", "Wysokie" },
            { "Text.EquipmentStat.Damage.Highest", "Najwyższe" },
            { "Text.CombatObjective.BreakfastTime", "Śniadanie" },
            { "Text.CombatObjective.DinnerTime", "Obiad" },
            { "Text.CombatObjective.ExerciseTime", "Ćwiczenia" },
            { "Text.CombatObjective.LunchTime", "Przerwa obiadowa" },
            { "Text.CombatObjective.ShowerTime", "Prysznic" },
            { "Text.Objective.LostProbe.FirstObjective", "Zlokalizuj $ItemToGet z $ItemSpawnLocation" },
            { "Text.Objective.LostProbe.SecondObjective", "Zdobyć $ItemToGet1 i wrócić do $QuestGiver" },
            { "Text.QuestRoutine.BreakfastTime", "Śniadanie" },
            { "Text.QuestRoutine.DinnerTime", "Obiad" },
            { "Text.QuestRoutine.EveningRollCall", "Apel Wieczorny" },
            { "Text.QuestRoutine.ExcerciseTime", "Czas Ćwiczeń" },
            { "Text.QuestRoutine.LunchTime", "Lunch" },
            { "Text.QuestRoutine.MidDayRollCall", "Apel Południowy" },
            { "Text.QuestRoutine.MorningRollCall", "Apel Poranny" },
            { "Text.QuestRoutine.ShowerTime", "Czas Prysznica" },
            { "Text.UI.FavourFailed", "Nie udało ci się wykonać tej przysługi!" },
        };
    }
}
