using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TE2PolishLocalizationNamespace
{
    public static class Items
    {
        public static readonly Dictionary<string, string> Data = new Dictionary<string, string>
        {
            { "Text.Item.RiotGuardOutfit", "Strój Oddziału Interwencyjnego" },
            { "Text.Item.TubeOfArtPaintsB", "Rurka Farb Plastycznych" },
            { "Text.Item.Payphone", "Telefon publiczny" },
            { "Text.Item.JobInstructionBoard", "Instrukcje pracy" },
            { "Text.Item.AdrenalineShot", "Strzał adrenaliny" },
            { "Text.Item.Aftershave", "Płyn po goleniu" },
            { "Text.Item.OldBox", "Stare pudełko" },
            { "Text.Item.Foil", "Rolka folii" },
            { "Text.Item.BalsaWood", "Drzewo balso" },
            { "Text.Item.MedicalMesh", "Siatka medyczna" },
            { "Text.Item.Baseball", "Piłka baseballowa" },
            { "Text.Item.BaseballMitt", "Rękawica baseballowa" },
            { "Text.Item.Battery", "Bateria" },
            { "Text.Item.Mug", "Kubek" },
            { "Text.Item.PaintedBox", "Pomalowane pudełko" },
            { "Text.Item.Broom", "Miotła" },
            { "Text.Item.BroomHandle", "Uchwyt miotły" },
            { "Text.Item.BedSheet", "Prześcieradło" },
            { "Text.Item.Sheet", "Prześcieradło" },
            { "Text.Item.Paper", "Arkusz papieru" },
            { "Text.Item.SheetOfMetal", "Płyta metalowa" },
            { "Text.Item.Bleach", "Wybielacz" },
            { "Text.Item.Bolts", "Śruba" },
            { "Text.Item.Bongos", "Bongo" },
            { "Text.Item.Crowbar", "Łom" },
            { "Text.Item.Letter", "List" },
            { "Text.Item.Book", "Książka" },
            { "Text.Item.PaperClip", "Spinacz papierowy" },
            { "Text.Item.TinOfPaint", "Puszka farby" },
            { "Text.Item.Soda", "Soda" },
            { "Text.Item.Wire", "Kabel" },
            { "Text.Item.Dowel", "Kieł" },
            { "Text.Item.IcePack", "Pakunek lodu" },
            { "Text.Item.IronBar", "Sztabka żelaza" },
            { "Text.Item.Stungun", "Paralizator" },
            { "Text.Item.EnergyDrink", "Napój energetyczny" },
            { "Text.Item.Dirt", "Brud" },
            { "Text.Item.Soil", "Gleba" },
            { "Text.Item.HandFan", "Wiatrak ręczny" },
            { "Text.Item.FamilyPhoto", "Zdjęcie rodzinne" },
            { "Text.Item.PaintBrush", "Pędzel malarski" },
            { "Text.Item.Feather", "Pióro" },
            { "Text.Item.File", "Plik" },
            { "Text.Item.Lighter", "Zapalniczka" },
            { "Text.Item.BottleOfMedicine", "Butelka leków" },
            { "Text.Item.Medicine", "Butelka leków" },
            { "Text.Item.BottleOfSleepingPills", "Butelka środków nasennych" },
            { "Text.Item.FlyingDisc", "Dysk latający" },
            { "Text.Item.Fruit", "Banan" },
            { "Text.Item.RadioReceiver", "Odbiornik radiowy" },
            { "Text.Item.SheetOfMetalFinished", "Płytka pamiątkowa" },
            { "Text.Item.PrisonMovieDVD", "DVD z filmem więziennym" },
            { "Text.Item.CookedFood", "Podawany posiłek" },
            { "Text.Item.CarvedSoapAnimals", "Wykutana mydła zwierzęta" },
            { "Text.Item.FaceMask", "Maska na twarz" },
            { "Text.Item.Guitar", "Gitara" },
            { "Text.Item.GlassShard", "Odłamek szkła" },
            { "Text.Item.LuckyPants", "Szczęśliwe spodnie" },
            { "Text.Item.GolfBall", "Piłka golfowa" },
            { "Text.Item.GreenColouredPen", "Zielony długopis" },
            { "Text.Item.InmateOutfit", "Strój więźnia" },
            { "Text.Item.Bracket", "Kątownik" },
            { "Text.Item.Hammer", "Młotek" },
            { "Text.Item.HandCream", "Krem do rąk" },
            { "Text.Item.Trowel", "Łopatka" },
            { "Text.Item.CookedPie", "Upieczona tarta" },
            { "Text.Item.Timber", "Drewno" },
            { "Text.Item.DogFood", "Puszka jedzenia dla psa" },
            { "Text.Item.Dogtag", "Etykieta psa" },
            { "Text.Item.DogBowl", "Miska psia" },
            { "Text.Item.JugglerBall", "Piłka do żonglowania" },
            { "Text.Item.Comb", "Grzebień" },
            { "Text.Item.Cookie", "Ciastko" },
            { "Text.Item.Pillow", "Poduszka" },
            { "Text.Item.PillowCase", "Poszwa" },
            { "Text.Item.CrateBase", "Podstawa skrzyni" },
            { "Text.Item.DuctTape", "Rolka taśmy klejącej" },
            { "Text.Item.Glue", "Tubka kleju" },
            { "Text.Item.ToiletPaper", "Rolka papieru toaletowego" },
            { "Text.Item.LumpOfCoal", "Kawałek węgla" },
            { "Text.Item.FoodCan", "Puszka jedzeniowa" },
            { "Text.Item.DoubleBass", "Bas podwójny" },
            { "Text.Item.InfirmaryOveralls", "Strój szpitalny" },
            { "Text.Item.ArtPaints", "Puszka farb artystycznych" },
            { "Text.Item.ArtBrush", "Pędzel finezyjny" },
            { "Text.Item.Copper", "Sztabka miedzi" },
            { "Text.Item.EmptyCannister", "Pusta puszka" },
            { "Text.Item.BlankSecurityPass", "Pusty pasek bezpieczeństwa" },
            { "Text.Item.CircuitBoard", "Płytka drukowana" },
            { "Text.Item.SolderingIron", "Lutownica" },
            { "Text.Item.Magazine", "Magazyn" },
            { "Text.Item.WallBlock", "Cegła" },
            { "Text.Item.Medikit", "Apteczka" },
            { "Text.Item.MetalBaton", "Metalowa pała" },
            { "Text.Item.Milk", "Butelka mleka" },
            { "Text.Item.SugarMint", "Słodka mięta" },
            { "Text.Item.StaffKey", "Klucz do służby" },
            { "Text.Item.Mop", "Mop" },
            { "Text.Item.TrashBag", "Worki na śmieci" },
            { "Text.Item.Nails", "Gwoździe" },
            { "Text.Item.NailPolish", "Lakier do paznokci" },
            { "Text.Item.OrangeColouredPen", "Pomarańczowy długopis" },
            { "Text.Item.PieFilling", "Nadzienie tartowe" },
            { "Text.Item.BeadedSnake", "Ozdobna wąż z koralików" },
            { "Text.Item.PilotsFood", "Jedzenie pilotów" },
            { "Text.Item.PlasticFork", "Sztućce plastikowe" },
            { "Text.Item.RubberGloves", "Para rękawic gumowych" },
            { "Text.Item.PlasticSpoon", "Łyżka plastikowa" },
            { "Text.Item.PlasticKnife", "Nóż plastikowy" },
            { "Text.Item.Plunger", "Przepychacz" },
            { "Text.Item.MailSack", "Worki pocztowe" },
            { "Text.Item.JetPack", "Plecak odrzutowy" },
            { "Text.Item.RazerBlade", "Ostrze do golarki" },
            { "Text.Item.Rations", "Zasoby żywnościowe" },
            { "Text.Item.Purifier", "Oczyszczacz" },
            { "Text.Item.UncookedFood", "Niesmażone jedzenie" },
            { "Text.Item.RedHerb", "Czerwona zieleń" },
            { "Text.Item.Seeds", "Ziarna" },
            { "Text.Item.OxygenTank", "Butla tlenowa" },
            { "Text.Item.Baton", "Pała" },
            { "Text.Item.Tubing", "Rura" },
            { "Text.Item.Key", "Klucz" },
            { "Text.Item.KeyCard", "Karta" },
            { "Text.Item.Chocolate", "Czekolada" },
            { "Text.Item.Screwdriver", "Śrubokręt" },
            { "Text.Item.ShoeFrame", "Rama buta" },
            { "Text.Item.ShoeSole", "Podeszwa buta" },
            { "Text.Item.HeavyDutyProtectors", "Para ochronnych osłon" },
            { "Text.Item.Soap", "Mydło" },
            { "Text.Item.SheriffsBadge", "Odznaka szeryfa" },
            { "Text.Item.SafetyGoggles", "Para gogli ochronnych" },
            { "Text.Item.Sock", "Skarpeta" },
            { "Text.Item.Spurs", "Kopytka" },
            { "Text.Item.Spittoon", "Pojemnik na ślina" },
            { "Text.Item.String", "Sznurek" },
            { "Text.Item.Rope", "Lina" },
            { "Text.Item.Sugar", "Cukier" },
            { "Text.Item.DinnerTray", "Talerz obiadowy" },
            { "Text.Item.Handkerchief", "Chusteczka" },
            { "Text.Item.Cup", "Kubek" },
            { "Text.Item.TeaBag", "Paczka herbaty" },
            { "Text.Item.JarOfInk", "Słoik z atramentem" },
            { "Text.Item.PastryCase", "Schowek na ciasto" },
            { "Text.Item.DeadRat", "Martwy szczur" },
            { "Text.Item.Drums", "Bęben" },
            { "Text.Item.TalcumPowder", "Takl kosmetyczny" },
            { "Text.Item.UnidentifiedSkull", "Nieokreślona czaszka" },
            { "Text.Item.UngluedFurniture", "Niezłączone meble" },
            { "Text.Item.BurntPie", "Przypalone ciasto" },
            { "Text.Item.BurntFood", "Przypalone jedzenie" },
            { "Text.Item.Wax", "Wosk" },
            { "Text.Item.WalkieTalkie", "Walkietalkie" },
            { "Text.Item.GuardOutfit", "Ubranie strażnika" },
            { "Text.Item.Washboard", "Tara muzyczna" },
            { "Text.Item.PreciousMineral", "Cenny minerał" },
            { "Text.Item.Toothbrush", "Pasta do zębów" },
            { "Text.Item.Toothpaste", "Tubka pasty do zębów" },
            { "Text.Item.DentalFloss", "Nitka dentystyczna" },
            { "Text.Item.CellKey", "Klucz do celi" },
            { "Text.Item.CivilianClothes", "Ubranie cywilne" },
            { "Text.EquipmentStat.OutfitType.Civilian", "Cywilne" },
            { "Text.Item.BaseballIdle", "Bezczynny w baseballu" },
            { "Text.Item.CombShiv", "Grzebieniowy nóż" },
            { "Text.Item.CounterWeight", "Przeciwwaga" },
            { "Text.Item.CupOfTea", "Kubek herbaty" },
            { "Text.Item.GliderSkin", "Powłoka lotni" },
            { "Text.Item.JugglingIdle", "Bezczynny w żonglowaniu" },
            { "Text.Item.LaxativeMix", "Mieszanka przeczyszczająca" },
            { "Text.Item.MakeshiftHarness", "Domowej roboty uprząż" },
            { "Text.Item.ManicureKit", "Zestaw do manicure" },
            { "Text.Item.Parachute", "Spadochron" },
            { "Text.Item.Poster", "Plakat" },
            { "Text.Item.PostalAddress", "Adres pocztowy" },
            { "Text.Item.PottedPlant", "Roślina w doniczce" },
            { "Text.Item.PretendCarrot", "Udawana marchewka" },
            { "Text.Item.PretendFlower", "Udawany kwiat" },
            { "Text.Item.ReadiedPaintBrush", "Pędzel z farbą" },
            { "Text.Item.SheetRope", "Lina z prześcieradeł" },
            { "Text.Item.TimberBrace", "Belka drewniana" },
            { "Text.Item.ToothbrushShiv", "Nóż z szczoteczki" },
            { "Text.Item.VisitorsKit", "Zestaw gości" },
            { "Text.Item.BaseballBat", "Kij baseballowy" },
            { "Text.Item.BedDummy", "Manekin" },
            { "Text.Item.BreathingMask", "Maska oddechowa" },
            { "Text.Item.Candle", "Świeca" },
            { "Text.Item.CombBlade", "Grzebień-nóż" },
            { "Text.Item.CushionedInmateOutfit", "Wygładzona odzież więźnia" },
            { "Text.Item.CuttingFloss", "Nitka do cięcia" },
            { "Text.Item.FakeWallBlock", "Fałszywa cegła" },
            { "Text.Item.FlimsyCutters", "Liche obcążki" },
            { "Text.Item.FlimsyPickaxe", "Słaby kilof" },
            { "Text.Item.FlimsyShovel", "Licha łopata" },
            { "Text.Item.FakeVentCover", "Fałszywa osłona wentylacyjna" },
            { "Text.Item.FramedPhoto", "Fotografia w ramce" },
            { "Text.Item.GlassShank", "Szklany patyk" },
            { "Text.Item.GlueReadiedFurniture", "Meble przygotowane klejem" },
            { "Text.Item.MakeshiftCosh", "Domowej roboty pałka" },
            { "Text.Item.MakeshiftRocketThruster", "Domowej roboty silnik odrzutowy" },
            { "Text.Item.MoltenPlastic", "Rozpuszczony plastik" },
            { "Text.Item.MusicWashboard", "Muzyczna Tara" },
            { "Text.Item.PaperMache", "Papierowe narzędzie" },
            { "Text.Item.Sling", "Slinga" },
            { "Text.Item.SockMace", "Maca skarpetowa" },
            { "Text.Item.ToolHandle", "Rączka narzędzia" },
            { "Text.Item.FinishedFurniture", "Wykończone meble" },
            { "Text.Item.WadOfPutty", "Kit" },
            { "Text.Item.ZipLine", "Linia zjazdowa" },
            { "Text.Item.BreathableTrashbag", "Oddychający worek na śmieci" },
            { "Text.Item.Cake", "Ciasto" },
            { "Text.Item.CrateCasing", "Obudowa skrzyni" },
            { "Text.Item.CrateTop", "Góra skrzyni" },
            { "Text.Item.CrossbowBody", "Tułów kuszy" },
            { "Text.Item.CrossbowLathe", "Wiertnica kuszy" },
            { "Text.Item.FakeAudioEquipment", "Fałszywy sprzęt audio" },
            { "Text.Item.FakeFence", "Fałszywe ogrodzenie" },
            { "Text.Item.GrappleHead", "Głowa haka" },
            { "Text.Item.GunMakerKit", "Zestaw do tworzenia broni" },
            { "Text.Item.HalfFrameOfGlider", "Połowa kadłuba lotni" },
            { "Text.Item.HalfSlingshotTrebuchetSupportFrame", "Połowa ramienia trebuchetu" },
            { "Text.Item.HeartRateSlower", "Spowolnienie tętna" },
            { "Text.Item.HiddenCompartment", "Ukryta przegroda" },
            { "Text.Item.KeycardCopy", "Skopiowana karta" },
            { "Text.Item.KeyMould", "Formy klucza" },
            { "Text.Item.KnuckleDuster", "Kasket" },
            { "Text.Item.LightweightCutters", "Lekke obcążki" },
            { "Text.Item.LightweightPickaxe", "Lekki kilof" },
            { "Text.Item.LightweightShovel", "Lekka łopata" },
            { "Text.Item.MakeshiftDoubleBass", "Domowej roboty podwójny bas" },
            { "Text.Item.MakeshiftRobotGuardOutfit", "Domowej roboty ubranie robotycznego strażnika" },
            { "Text.Item.MoltenChoc", "Kubek gorącej czekolady" },
            { "Text.Item.PaddedInmateOutfit", "Wypełniona odzież więźnia" },
            { "Text.Item.SleepingGas", "Gaz usypiący" },
            { "Text.Item.UncookedPie", "Niesmażone ciasto" },
            { "Text.Item.WhiteGloves", "Para białych rękawiczek" },
            { "Text.Item.BeautifulPainting", "Piękny obraz" },
            { "Text.Item.CompleteFrameOfGlider", "Kompletna rama zlejsza" },
            { "Text.Item.ContrabandPouch", "Skórzana torba przemycana" },
            { "Text.Item.EnergyModule", "Moduł energetyczny" },
            { "Text.Item.EscapistsFigurine", "Figurka uciekinierów" },
            { "Text.Item.FakeKeycard", "Fałszywa karta" },
            { "Text.Item.FullTrebuchetFrame", "Cała rama trebuchetu" },
            { "Text.Item.MachineReadyShoe", "But gotowy do maszyny" },
            { "Text.Item.MakeshiftBreathingApparatus", "Domowej roboty aparat oddechowy" },
            { "Text.Item.MakeshiftRaft", "Tymczasowa tratwa" },
            { "Text.Item.MakeshiftSledgehammer", "Domowej roboty młot" },
            { "Text.Item.MakeshiftSpear", "Domowej roboty Dzida" },
            { "Text.Item.MakeshiftStungun", "Domowej roboty Paralizator" },
            { "Text.Item.MouldedGun", "Wytłoczona Broń" },
            { "Text.Item.Nunchuck", "Nunchuck" },
            { "Text.Item.PlasticKey", "Plastikowy Klucz" },
            { "Text.Item.PlatedInmateOutfit", "Pancerny Strój Więźnia" },
            { "Text.Item.RaftBase", "Podstawa Łodzi" },
            { "Text.Item.Sail", "Żagiel" },
            { "Text.Item.SecurityPass", "Bilet Bezpieczeństwa" },
            { "Text.Item.SleepingGasCannister", "Kanister Gazu Sennego" },
            { "Text.Item.SturdyCutters", "Mocne Kąbinerki" },
            { "Text.Item.SturdyPickaxe", "Mocny Kilof" },
            { "Text.Item.SturdyShovel", "Mocna Łopata" },
            { "Text.Item.SuperKnuckleDuster", "Super kastet" },
            { "Text.Item.SuperSockMace", "Super Maca skarpetowa" },
            { "Text.Item.Whip", "Bicz" },
            { "Text.Item.ZiplineHook", "Końcówka Liny" },
            { "Text.Item.BreakdanceIdle", "Breakdance Idle" },
            { "Text.Item.CattleProd", "Włóczka do Krowy" },
            { "Text.Item.CompleteCrossbow", "Kąpletna kusza" },
            { "Text.Item.CompleteTrebuchet", "Komplet Trebuszatu" },
            { "Text.Item.DurableContrabandPouch", "Trwała Torba z Nielegalnym Towarem" },
            { "Text.Item.EnergySword", "Miecz Świetlny" },
            { "Text.Item.FakeGun", "Fałszywa Broń" },
            { "Text.Item.GrapplingHook", "Końcówka Wieszaka" },
            { "Text.Item.MakeshiftGasMask", "Domowej roboty Maski Gazowa" },
            { "Text.Item.MimeIdle", "Mime Idle" },
            { "Text.Item.Multitool", "Narzędzie Wielofunkcyjne" },
            { "Text.Item.SkinnedGlider", "Powlekana lotnia" },
            { "Text.Item.SuperBaseballBat", "Super Kij Baseballowy" },
            { "Text.Item.SuperMetalBaton", "Super Metalowa Pała" },
            { "Text.Item.SuperWhip", "Super Bicz" },
            { "Text.Item.MakeshiftLadder", "Domowej roboty Drabina" },
            { "Text.Item.RedKey", "Czerwony Klucz" },
            { "Text.Item.PurpleKey", "Purpurowy Klucz" },
            { "Text.Item.YellowKey", "Żółty Klucz" },
            { "Text.Item.CyanKey", "Cyjanowy Klucz" },
            { "Text.Item.GreenKey", "Zielony Klucz" },
            { "Text.Item.PlasticRedKey", "Plastikowy Czerwony Klucz" },
            { "Text.Item.PlasticPurpleKey", "Plastikowy Purpurowy Klucz" },
            { "Text.Item.PlasticYellowKey", "Plastikowy Żółty Klucz" },
            { "Text.Item.PlasticCyanKey", "Plastikowy Cyjanowy Klucz" },
            { "Text.Item.PlasticGreenKey", "Plastikowy Zielony Klucz" },
            { "Text.Item.RedKeyCard", "Czerwona karta" },
            { "Text.Item.PurpleKeyCard", "Purpurowa Karta" },
            { "Text.Item.YellowKeyCard", "Żółta Karta" },
            { "Text.Item.CyanKeyCard", "Cyjanowa Karta" },
            { "Text.Item.GreenKeyCard", "Zielona Karta" },
            { "Text.Item.RedKeyCardCopy", "Formowanie Czerwonej Karty" },
            { "Text.Item.PurpleKeyCardCopy", "Formowanie Purpurowej Karty" },
            { "Text.Item.YellowKeyCardCopy", "Formowanie Żółtej Karty" },
            { "Text.Item.CyanKeyCardCopy", "Formowanie Cyjanowej Karty" },
            { "Text.Item.GreenKeyCardCopy", "Formowanie Zielonej Karty" },
            { "Text.Item.KeyMouldRed", "Wytłoczony Czerwony Klucz" },
            { "Text.Item.KeyMouldPurple", "Wytłoczony Purpurowy Klucz" },
            { "Text.Item.KeyMouldYellow", "Wytłoczony Żółty Klucz" },
            { "Text.Item.KeyMouldCyan", "Wytłoczony Cyjanowy Klucz" },
            { "Text.Item.FakeRedKeyCard", "Fałszywa Czerwona Karta" },
            { "Text.Item.FakePurpleKeyCard", "Fałszywa Purpurowa Karta" },
            { "Text.Item.FakeYellowKeyCard", "Fałszywa Żółta Karta" },
            { "Text.Item.FakeCyanKeyCard", "Fałszywa Cyjanowa Karta" },
            { "Text.Item.FakeGreenKeyCard", "Fałszywa Zielona Karta" },
            { "Text.Item.VentCover", "Pokrycie Wentylacji" },
            { "Text.Item.DummiesGuide", "Instrukcja Lotu" },
            { "Text.Item.RockHammer", "Młot Skalny" },
            { "Text.Item.MedicOutfit", "Strój Lekarza" },
            { "Text.Item.JuicyWorm", "Sokowaty Robak" },
            { "Text.Item.HardHat", "Kask Twardy" },
            { "Text.Item.Salmon", "Łosoś" },
            { "Text.Item.FishingRod", "Wędka" },
            { "Text.Item.ReadiedFishingRod", "Gotowa Wędka" },
            { "Text.Item.Pearls", "Perły" },
            { "Text.Item.DolphinTooth", "Ząb Delfina" },
            { "Text.Item.SeaSicknessBand", "Opaska Morska" },
            { "Text.Item.CompleteShoe", "Komplet Buta" },
            { "Text.Item.PairOfShoes", "Para Butów" },
            { "Text.Item.MailbagBlue", "Niebieski Pojemnik na Listy" },
            { "Text.Item.MailbagGreen", "Zielony Pojemnik na Listy" },
            { "Text.Item.MailbagRed", "Czerwony Pojemnik na Listy" },
            { "Text.Item.WeakBaton", "Paliwo Baton" },
            { "Text.Item.ColouredBox", "Kolorowy Kubek" },
            { "Text.Item.Harmonica", "Harmonijka" },
            { "Text.Item.InflatableAlien", "Powietrzny Obcy" },
            { "Text.Item.KeyMouldGreen", "Wytłoczony Zielony Klucz" },
            { "Text.Item.Microchip", "Microchip" },
            { "Text.Item.MissileKeyring", "Kluczyk Rakietowy" },
            { "Text.Item.ThePeoplesFlag", "Flaga Ludowa" },
            { "Text.Item.Probe", "Zbiórnik" },
            { "Text.Item.DolphinBook", "Książka Jak Mówić Delfinem" },
            { "Text.Item.BookOfHappiness", "Książka Szczęścia" },
            { "Text.Item.Flour", "Paczka mąki" },
            { "Text.Item.RobotOfficerOutfit", "Ubranie Strażnika" },
            { "Text.Item.POWOutfit", "Ubranie Uwięzionego" },
            { "Text.Item.TutorialPickaxe", "Kilof Robinsona" },
            { "Text.Item.TutorialShovel", "Łopata Robinsona" },
            { "Text.Item.TutorialCutters", "Nożyce Robinsona" },
            { "Text.Item.ZombieHand", "Ręka Zombie" },
            { "Text.Item.MonsterArm", "Ramię Potwora" },
            { "Text.Item.MonsterLeg", "Noga Potwora" },
            { "Text.Item.Eyeball", "Gałka Oczna" },
            { "Text.Item.EmptyGiftBag", "Pusty Worek" },
            { "Text.Item.Candy", "Cukierek" },
            { "Text.Item.Pumpkin", "Dynia" },
            { "Text.Item.CarvedPumpkin", "Wydrążona Dynia" },
            { "Text.Item.DirtyVampireRobes", "Brudne Szaty Wampira" },
            { "Text.Item.VampireRobes", "Szaty Wampira" },
            { "Text.Item.CreatureFood", "Eksperymentalna Karma" },
            { "Text.Item.CreatureFoodBowl", "Miska z Karmą" },
            { "Text.Item.SecretPassageKey", "Klucz do Sekretnego Przejścia" },
            { "Text.Item.Weathervane", "Wiatrowskaz" },
            { "Text.Item.WoodenStake", "Drewniany Kołek" },
            { "Text.Item.AxeHead", "Głowica Siekiery" },
            { "Text.Item.ZombieGuardOutfit", "Strój Zombie Strażnika" },
            { "Text.Item.TreatBag", "Worek z Niespodzianką" },
            { "Text.Item.TrickBag", "Worek Psikusów" },
            { "Text.Item.LightningConductor", "Piorunochron" },
            { "Text.Item.Axe", "Siekiera" },
            { "Text.Item.ChristmasList", "Lista Świąteczna" },
            { "Text.Item.PantomimeScript", "Scenariusz Pantomimy" },
            { "Text.Item.JarOfMince", "Słoik farszu" },
            { "Text.Item.WoodenSoldier", "Drewniany Żołnierz" },
            { "Text.Item.TreeDecorations", "Ozdoby na drzewo" },
            { "Text.Item.Fabric", "Tkanina" },
            { "Text.Item.Holly", "Gałązka ostrokrzewu" },
            { "Text.Item.WrappingPaper", "Papier do pakowania" },
            { "Text.Item.LetterToSanta", "List do Świętego Mikołaja" },
            { "Text.Item.PantoHorseFront", "Koń pantomimiczny (przód)" },
            { "Text.Item.PantoHorseRear", "Koń pantomimiczny (tył)" },
            { "Text.Item.MincePie", "Placek mięsny" },
            { "Text.Item.PaintedWoodenSoldier", "Pomalowany drewniany żołnierz" },
            { "Text.Item.Christmace", "Świąteczny Mace" },
            { "Text.Item.Balloon", "Balon" },
            { "Text.Item.BowTie", "Muszka" },
            { "Text.Item.Horn", "Róg" },
            { "Text.Item.ChatteringTeeth", "Gadające Zęby" },
            { "Text.Item.RubberChicken", "Gumowy Kurczak" },
            { "Text.Item.FacePaints", "Farby do Twarzy" },
            { "Text.Item.Steak", "Stek" },
            { "Text.Item.CircusPoster", "Plakat Cyrkowy" },
            { "Text.Item.SquirtyFlower", "Kwiat na Spryskanie" },
            { "Text.Item.CanOfCustard", "Puszka Budyniu" },
            { "Text.Item.Coconut", "Kokos" },
            { "Text.Item.Spring", "Sprężyna" },
            { "Text.Item.Keys", "Klucze do Wybiegu" },
            { "Text.Item.SuperRubberChicken", "Super Gumowy Kurczak" },
            { "Text.Item.BalloonAnimal", "Balonowe Zwierzątko" },
            { "Text.Item.WindUpMouse", "Nakręcana Myszka" },
            { "Text.Item.CustardPie", "Placek z Budyniem" },
            { "Text.Item.MakeshiftHelmet", "Improwizowany Hełm" },
            { "Text.Item.MakeshiftLauncher", "Improwizowany Wyrzutnik" },
            { "Text.Item.GlueReadiedPoster", "Plakat Gotowy z Klejem" },
            { "Text.Item.Gemstone", "Kamień Szlachetny" },
            { "Text.Item.MoltenMetal", "Roztopiony Metal" },
            { "Text.Item.ReplicaLute", "Replika Lutni" },
            { "Text.Item.TorchFuel", "Paliwo do pochodni" },
            { "Text.Item.MetalIngot", "Sztabka Metalu" },
            { "Text.Item.Horseshoe", "Podkowa" },
            { "Text.Item.Rivets", "Nity" },
            { "Text.Item.WoodenPeg", "Drewniany Kołek" },
            { "Text.Item.LeatherStrap", "Skórzany Pasek" },
            { "Text.Item.StoneTablet", "Kamienna Tablica" },
            { "Text.Item.PlasticChalice", "Tani Plastikowy Kielich" },
            { "Text.Item.MedievalHalbard", "Improwizowana Halabarda" },
            { "Text.Item.MedievalStaff", "Improwizowany Kij" },
            { "Text.Item.MedievalSword", "Improwizowany Miecz" },
            { "Text.Item.MedievalHelmet", "Improwizowany Hełm Rycerski" },
            { "Text.Item.MedievalChestPlate", "Improwizowana Napierśnik" },
            { "Text.Item.MedievalGreaves", "Improwizowane Nagolenniki" },
            { "Text.Item.MedievalGauntlets", "Improwizowane Rękawice" },
            { "Text.Item.MedievalHalfCatapultFrame", "Połowa Ramy Katapulty" },
            { "Text.Item.MedievalCatapultBeam", "Belka Katapulty" },
            { "Text.Item.MedievalCatapultBucket", "Wiadro Katapulty" },
            { "Text.Item.MedievalWoodenOar", "Drewniane Wiosło" },
            { "Text.Item.MedievalCatapultCounterWeight", "Przeciwwaga Katapulty" },
            { "Text.Item.Cardboard", "Karton" },
            { "Text.Item.BluePaint", "Niebieska Farba" },
            { "Text.Item.RedPaint", "Czerwona Farba" },
            { "Text.Item.YellowPaint", "Żółta Farba" },
            { "Text.Item.LaptopPassword", "Hasło do Laptopa" },
            { "Text.Item.SleighChipset", "Chipset Sanek" },
            { "Text.Item.ReindeerFood", "Pokarm dla Reniferów" },
            { "Text.Item.DicedVegetables", "Pokrojone Warzywa" },
            { "Text.Item.OilCan", "Pojemnik z Olejem" },
            { "Text.Item.USBStick", "Pendrive" },
            { "Text.Item.CandyCane", "Laska Cukrowa" },
            { "Text.Item.AIModule", "Moduł AI" },
            { "Text.Item.CardboardBox", "Pudełko Kartonowe" },
            { "Text.Item.CandyPain", "Cukrowy Ból" }
        };
    }
}
