using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TE2PolishLocalizationNamespace
{
    public static class Map
    {
        public static readonly Dictionary<string, string> Data = new Dictionary<string, string>
        {
            { "Text.Map.CarPark", "Parking" },
            { "Text.Map.CharacterHome", "Cela $NAME" },
            { "Text.Map.ContrabandRoom", "Pokój Kontrabandy" },
            { "Text.Map.ControlRoom", "Centrum Kontroli" },
            { "Text.Map.FoodHall", "Stołówka" },
            { "Text.Map.GuardRoom", "Pokój Strażnika" },
            { "Text.Map.GuardTower", "Wieża Strażnicza" },
            { "Text.Map.Gym", "Siłownia" },
            { "Text.Map.Infirmary", "Infirmarium" },
            { "Text.Map.InmateCell", "Cela" },
            { "Text.Map.JobOffice", "Biuro Pracy" },
            { "Text.Map.JobRoom", "Pokój Pracy" },
            { "Text.Map.Kennels", "Kojce" },
            { "Text.Map.Key.Dogs", "Psy" },
            { "Text.Map.Key.Doors", "Drzwi" },
            { "Text.Map.Key.DoubleDoors", "Podwójne Drzwi" },
            { "Text.Map.Key.FavourObjective", "Cel Przysługi" },
            { "Text.Map.Key.Favours", "Przysługi" },
            { "Text.Map.Key.Generator", "Generator" },
            { "Text.Map.Key.Guards", "Strażnicy" },
            { "Text.Map.Key.Home", "Dom" },
            { "Text.Map.Key.Inmates", "Więźniowie" },
            { "Text.Map.Key.Maintenance", "Obsługa Techniczna" },
            { "Text.Map.Key.Medics", "Medycy" },
            { "Text.Map.Key.Players", "Gracze" },
            { "Text.Map.Key.Shops", "Sklepy" },
            { "Text.Map.Key.SlidingDoors", "Drzwi Przesuwne" },
            { "Text.Map.Key.Vents", "Kanały Wentylacyjne" },
            { "Text.Map.KeyTitle", "LEGENDA" },
            { "Text.Map.Library", "Biblioteka" },
            { "Text.Map.Maintenance", "Obsługa Techniczna" },
            { "Text.Map.RollCall", "Apel" },
            { "Text.Map.Showers", "Prysznice" },
            { "Text.Map.Social", "Strefa Socjalna" },
            { "Text.Map.Solitary", "Izolacja" },
            { "Text.Map.Tag.Player01", "Oznaczone Miejsce" },
            { "Text.Map.Tag.Player02", "Oznaczone Miejsce" },
            { "Text.Map.Tag.Player03", "Oznaczone Miejsce" },
            { "Text.Map.Tag.Player04", "Oznaczone Miejsce" },
            { "Text.Map.VisitorsRoom", "Pokój Gości" },
            { "text.Map.WardenOffice", "Biuro Dyrektora" },
            { "Text.Map.WasteCollection", "Zbiórka Odpadów" },
            { "Text.MapFilter.All", "Wszystko" },
            { "Text.MapFilter.Characters", "Postacie" },
            { "Text.MapFilter.Favours", "Przysługi" },
            { "Text.MapFilter.Objectives", "Cele" },
            { "Text.MapFilter.Shops", "Sklepy" },
            { "Text.MapFilter.Tags", "Tagi" },
            { "Text.MapFloorname.Floor_Prison0", "Piętro 0" },
            { "Text.MapFloorname.Floor_Prison1", "Piętro 1" },
            { "Text.MapFloorname.Floor_Prison-1", "Poziom Podziemny" },
            { "Text.MapFloorname.Floor_Prison10", "Piętro 10" },
            { "Text.MapFloorname.Floor_Prison2", "Piętro 2" },
            { "Text.MapFloorname.Floor_Prison3", "Piętro 3" },
            { "Text.MapFloorname.Floor_Prison4", "Piętro 4" },
            { "Text.MapFloorname.Floor_Prison5", "Piętro 5" },
            { "Text.MapFloorname.Floor_Prison6", "Piętro 6" },
            { "Text.MapFloorname.Floor_Prison7", "Piętro 7" },
            { "Text.MapFloorname.Floor_Prison8", "Piętro 8" },
            { "Text.MapFloorname.Floor_Prison9", "Piętro 9" },
            { "Text.MapFloorname.Floor_Roof1", "Dach 1" },
            { "Text.MapFloorname.Floor_Roof2", "Dach 2" },
            { "Text.MapFloorname.Floor_Roof3", "Dach 3" },
            { "Text.MapFloorname.Floor_Roof4", "Dach 4" },
            { "Text.MapFloorname.Floor_Roof5", "Dach 5" },
            { "Text.MapFloorname.Floor_UnderGround0", "Poziom Podziemny" },
            { "Text.MapFloorname.Floor_UnderGround-1", "Poziom Podziemny" },
            { "Text.MapFloorname.Floor_Vent1", "Kanał Wentylacyjny 1" },
            { "Text.MapFloorname.Floor_Vent10", "Kanał Wentylacyjny 10" },
            { "Text.MapFloorname.Floor_Vent2", "Kanał Wentylacyjny 2" },
            { "Text.MapFloorname.Floor_Vent3", "Kanał Wentylacyjny 3" },
            { "Text.MapFloorname.Floor_Vent4", "Kanał Wentylacyjny 4" },
            { "Text.MapFloorname.Floor_Vent5", "Kanał Wentylacyjny 5" },
            { "Text.MapFloorname.Floor_Vent6", "Kanał Wentylacyjny 6" },
            { "Text.MapFloorname.Floor_Vent7", "Kanał Wentylacyjny 7" },
            { "Text.MapFloorname.Floor_Vent8", "Kanał Wentylacyjny 8" },
            { "Text.MapFloorname.Floor_Vent9", "Kanał Wentylacyjny 9" }
        };
    }
}
