using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TE2PolishLocalizationNamespace
{
    public static class Menu
    {
        public static readonly Dictionary<string, string> Data = new Dictionary<string, string>
        {
            { "Text.Menu.Apply", "ZASTOSUJ" },
            { "Text.Menu.BrowseGames", "PRZEGLĄDAJ GRY" },
            { "Text.Menu.BuyRecipe", "Kup Przepis Rzemieślniczy:" },
            { "Text.Menu.Campaign", "GRAJ" },
            { "Text.Menu.Cancel", "ANULUJ" },
            { "Text.Menu.Collectables", "KOLEKCJONERSKIE" },
            { "Text.Menu.Confirm", "POTWIERDŹ" },
            { "Text.Menu.Continue", "KONTYNUUJ" },
            { "Text.Menu.CoopGoal", "Uciekaj z więzienia samemu lub z innymi graczami!" },
            { "Text.Menu.CraftingTitle", "RZEMIOSŁO" },
            { "Text.Menu.Credits", "TWÓRCY" },
            { "Text.Menu.CriminalRecord", "REKORD KRYMINALNY" },
            { "Text.Menu.CriminalRecord.Completion", "Ukończenie" },
            { "Text.Menu.CriminalRecord.Escapes", "Ucieczki" },
            { "Text.Menu.CriminalRecord.Header", "Rekord Kryminalny" },
            { "Text.Menu.CriminalRecord.TimeServed", "Odbyty Czas" },
            { "Text.Menu.CriminalRecord.Title", "Departament Sprawiedliwości" },
            { "Text.Menu.CriminalRecord.Unlocks", "Odblokowania" },
            { "Text.Menu.CriminalRecordTitle.Title", "Tytuł" },
            { "Text.Menu.Customisation", "MOJE POSTACIE" },
            { "Text.Menu.Customisation.CancelDialog.Message", "Masz niezapisane zmiany. Na pewno chcesz opuścić ekran? Wszystkie zmiany zostaną utracone." },
            { "Text.Menu.Customisation.CancelDialog.Title", "OSTRZEŻENIE!" },
            { "Text.Menu.Customise", "DOSTOSUJ WIĘŹNIÓW I STRAŻNIKÓW" },
            { "Text.Menu.CutlreyDrawerTitle", "SZTUĆCE" },
            { "Text.Menu.Day", "DZIEŃ" },
            { "Text.Menu.Defaults", "DOMYŚLNE" },
            { "Text.Menu.DeskTitle", "BIURKO" },
            { "Text.Menu.FaceType", "TYP TWARZY" },
            { "Text.Menu.FavourTitle", "PRZYSŁUGA" },
            { "Text.Menu.Filters", "FILTRY" },
            { "Text.Menu.FindGames", "SZUKAJ GRY" },
            { "Text.Menu.Full", "Pełny" },
            { "Text.Menu.GameTitle", "THE ESCAPISTS 2" },
            { "Text.Menu.Gender", "PŁEĆ" },
            { "Text.Menu.GiftingTitle", "DAROWANIE" },
            { "Text.Menu.Hat", "CZAPKA" },
            { "Text.Menu.HelpAndOptions", "POMOC I OPCJE" },
            { "Text.Menu.Info", "INFO" },
            { "Text.Menu.InmateAccessory", "DOLNA CZĘŚĆ TWARZY" },
            { "Text.Menu.InmateFace", "GÓRNA CZĘŚĆ TWARZY" },
            { "Text.Menu.InmateHair", "WŁOSY" },
            { "Text.Menu.InmateHead", "GŁOWA" },
            { "Text.Menu.InmateInfo", "INFO" },
            { "Text.Menu.InmateInfoTitle", "PROFIL" },
            { "Text.Menu.InmateSelection", "WYBIERZ POSTAĆ" },
            { "Text.Menu.Join", "DOŁĄCZ" },
            { "Text.Menu.JournalTitle", "DZIENNIK" },
            { "Text.Menu.Leaderboards", "TABLICE WYNIKÓW" },
            { "Text.Menu.LeaderboardTime", "CZAS" },
            { "Text.Menu.LevelName", "Nazwa Poziomu" },
            { "Text.Menu.Load", "WCZYTAJ" },
            { "Text.Menu.LoadSaveDialog", "MIEJSCA ZAPISU" },
            { "Text.Menu.Local", "LOKALNIE" },
            { "Text.Menu.LocalVersus", "LOKALNY VERSUS" },
            { "Text.Menu.LootingTitle", "GRABIEŻ" },
            { "Text.Menu.LowerFace", "DOLNA CZĘŚĆ TWARZY" },
            { "Text.Menu.Matchmaking.SearchingForBody", "Wyszukiwanie gier $PLAYLIST_NAME…" },
            { "Text.Menu.Mode", "Tryb" },
            { "Text.Menu.Name", "IMIĘ" },
            { "Text.Menu.NewGame", "NOWA GRA" },
            { "Text.Menu.NoEntries", "Brak wpisów dla tej tablicy wyników" },
            { "Text.Menu.OkToExit", "Na pewno chcesz wyjść?" },
            { "Text.Menu.OnlineLobbyPrivate", "PRYWATNY VERSUS" },
            { "Text.Menu.OnlineLobbyPublic", "PUBLICZNY VERSUS" },
            { "Text.Menu.OnlinePrisoners", "Więźniowie Online" },
            { "Text.Menu.Open", "OTWÓRZ" },
            { "Text.Menu.Options", "OPCJE" },
            { "Text.Menu.Options.Controls", "STEROWANIE" },
            { "Text.Menu.Options.HowToPlay", "JAK GRAĆ" },
            { "Text.Menu.Options.VideoAudio", "OPCJE" },
            { "Text.Menu.PageTitle", "STRONA" },
            { "Text.Menu.PanelTitle", "Tytuł Panelu" },
            { "Text.Menu.Perk", "PERK" },
            { "Text.Menu.Platform", "Platforma" },
            { "Text.Menu.Player1", "GRACZ 1" },
            { "Text.Menu.Player2", "GRACZ 2" },
            { "Text.Menu.Player3", "GRACZ 3" },
            { "Text.Menu.Player4", "GRACZ 4" },
            { "Text.Menu.PlayerCount", "Liczba Graczy" },
            { "Text.Menu.Players", "GRACZE" },
            { "Text.Menu.PlayMode", "TRYB GRY" },
            { "Text.Menu.Prison", "WIĘZIENIE" },
            { "Text.Menu.PrisonName", "WIĘZIENIE" },
            { "Text.Menu.PrisonSelect", "WYBÓR WIĘZIENIA" },
            { "Text.Menu.PrisonSetup", "USTAWIENIA WIĘZIENIA" },
            { "Text.Menu.Private", "PRYWATNY" },
            { "Text.Menu.PrivateVersus", "PRYWATNY VERSUS" },
            { "Text.Menu.ProfileTitle", "PROFIL" },
            { "Text.Menu.Progress", "REKORD KRYMINALNY" },
            { "Text.Menu.Public", "PUBLICZNY" },
            { "Text.Menu.PublicVersus", "PUBLICZNY VERSUS" },
            { "Text.Menu.Quit", "WYJŚCIE" },
            { "Text.Menu.Randomise", "LOSUJ" },
            { "Text.Menu.Rank", "RANGA" },
            { "Text.Menu.RegionInfo", "Dobierasz się tylko z graczami w swoim regionie. Zaproszenia mogą być użyte, aby grać z przyjaciółmi w dowolnym regionie." },
            { "Text.Menu.Resume", "WZNÓW" },
            { "Text.Menu.RoomName", "Nazwa Pokoju" },
            { "Text.Menu.SaveChangesBody", "Masz niezapisane zmiany. Chcesz je zapisać teraz?" },
            { "Text.Menu.SaveChangesTitle", "ZAPISZ ZMIANY" },
            { "Text.Menu.Score", "WYNIK" },
            { "Text.Menu.Searching", "WYSZUKIWANIE…" },
            { "Text.Menu.Settings", "POMOC I OPCJE" },
            { "Text.Menu.Shop.WillSell", "$vendor sprzeda ci, ponieważ ma o tobie dobre zdanie." },
            { "Text.Menu.Shop.WontSell", "$vendor nie sprzeda ci, ponieważ ma o tobie złe zdanie." },
            { "Text.Menu.ShopTitle", "SKLEP" },
            { "Text.Menu.SkinColour", "KOLOR SKÓRY" },
            { "Text.Menu.SoloGoal", "Tutorial tylko dla jednego gracza." },
            { "Text.Menu.Start", "START" },
            { "Text.Menu.StartGame", "ROZPOCZNIJ GRĘ" },
            { "Text.Menu.SwagBagTitle", "TORBA" },
            { "Text.Menu.TierLevel", "Poziom" },
            { "Text.Menu.ToiletTitle", "TOALETA" },
            { "Text.Menu.User", "UŻYTKOWNIK" },
            { "Text.Menu.Versus", "GRA PRZECIWKO" },
            { "Text.Menu.Versus.InvitePlayer", "Zaproś Gracza" },
            { "Text.Menu.Versus.Public.WaitingForPlayerSlot", "Wyszukiwanie gracza…" },
            { "Text.Menu.VersusGoal", "Pierwszy gracz, który ucieknie, wygrywa!" },
            { "Text.Menu.VersusGoalNew", "Pierwszy gracz, który ucieknie w wyznaczonym czasie, wygrywa!" },
            { "Text.Menu.Visible", "Widoczny" },
            { "Text.PauseMenu.PlayerManagement", "ZARZĄDZANIE GRACZAMI" },
            { "Text.PauseMenu.Quit", "WYJDŹ" },
            { "Text.PauseMenu.Resume", "WZNÓW" },
            { "Text.PauseMenu.SessionMode", "TRYB GRY" },
            { "Text.PauseMenu.Settings", "USTAWIENIA" },
            { "Text.PauseMenu.Title", "ZARZĄDZANIE GRĄ" },
            { "Text.Menu.Autosave", "AUTOMATYCZNY ZAPIS" },
            { "Text.Menu.PIPMedic", "Medycyna wdrożona" },
            { "Text.Menu.PIPMaintenance", "Uszkodzenia naprawione" },
            { "Text.Menu.PIPContraband", "Kontrabanda znaleziona" },
            { "Text.Menu.PIPDamage", "Uszkodzenia wykryte" },
            { "Text.Menu.PIPVisitor", "Odwiedzający" },
            { "Text.Menu.PIPSearch", "Przeszukanie biurka" },
            { "Text.Menu.LevelsUnlocked", "Odblokowano nowe więzienia" },
            { "Text.Menu.LevelsUnlockedSpace", "Odblokowano nowe więzienie" },
            { "Text.Menu.UnlockDescription1", "Głęboko za liniami wroga, obóz ‘K.A.P.O.W’ wymaga planowania ucieczki z militarną precyzją.\\n\\nJeśli tęsknisz za świeżym powietrzem morza, wybierz mini-wakacje na H.M.S Orca, najmniej romantycznym i luksusowym statku, na jakim kiedykolwiek stąpisz.\\n\\nZ nowymi umiejętnościami morskimi staw czoła H.M.P Offshore, dawnej platformie wiertniczej przekształconej w więzienie o wysokim stopniu bezpieczeństwa!" },
            { "Text.Menu.UnlockDescription2", "Poczuj świeże subarktyczne powietrze Fort Tundra, gdzie chłód wiatru dorównuje chłodnym spojrzeniom strażników.\\n\\nWolisz cieplejszy klimat? Udaj się na pustynię, gdzie znajduje się tajemniczy Area 17 i jego nieziemscy więźniowie.\\n\\nJeśli lubisz wysokości, wybierz lot Air Force Con… już nigdy nie będziesz narzekać na tanie linie lotnicze!" },
            { "Text.Menu.UnlockDescription3", "Mały krok dla więźnia, wielki skok dla zakładu karnego… Aby dojść tak daleko, naprawdę jesteś wykwalifikowanym uciekinierem, ale teraz czas zmierzyć się z ostatecznym wyzwaniem. Przygotuj się na więzienie dosłownie poza tym światem…" },
            { "Text.Menu.GuestWarning", "Jako gość, Twoje statystyki i pieniądze nie zostaną zapisane po opuszczeniu sesji. Twoje przedmioty zostaną pozostawione w torbie Swag Bag." },
            { "Text.Menu.Streamers", "Streamerzy (naciśnij RANDOMISE, aby zastosować)" },
            { "Text.Menu.GameTypeExplained.Public", "Każdy może zobaczyć i dołączyć do Twojej gry." },
            { "Text.Menu.GameTypeExplained.Private", "Twoja gra nie będzie widoczna publicznie. Masz kontrolę nad tym, kogo zapraszasz i pozwalasz grać." },
            { "Text.Menu.GameTypeExplained.Local", "Gra tylko w trybie podzielonego ekranu. Gra nie będzie widoczna publicznie ani dla znajomych online." },
            { "Text.Menu.OkToExitNoSave", "Czy na pewno chcesz wyjść? Niezapisany postęp zostanie utracony" },
            { "Text.Menu.NewUnlockPopUp.Title", "Witaj z powrotem, Uciekinierze! " },
            { "Text.Menu.NewUnlockPopUp.Body", "Dodano funkcję ręcznego zapisu! Włącz ją w menu opcji. \\n\\nWięzienia w podstawowej grze są teraz odblokowywane na podstawie liczby unikalnych ucieczek, zastępując poprzedni system 'kluczy' w rejestrze przestępstw." },
            { "Text.Menu.NewUnlockPopUp.Important", "Ważne!" },
            { "Text.Menu.NewUnlockPopUp.Features", "Ręczny zapis i zmiany w odblokowywaniu" },
            { "Text.Menu.RobinsonAvailable.Title", "Powrót Robinsona" },
            { "Text.Menu.RobinsonAvailable.Body", "Robinson, gwiazda samouczka Więzienie Precinct 17, został teraz zamknięty w Center Perks 2.0. Odwiedź go, aby nauczyć się wszystkiego o ucieczkach z perymetru! Pokaże Ci, jak kopać, kuć i ciąć drogę do wolności!" },
            { "Text.Menu.Escapes", "UCIECZKI" },
            { "Console.Menu.SplitScreenAvilable", "Dodatkowi lokalni gracze naciśnij [IN=UI_Submit], aby dołączyć…" },
            { "Console.Menu.SplitScreenAvilablePauseScreen", "Wznów grę, a następnie dodatkowi lokalni gracze naciśnij [IN=UI_Submit], aby dołączyć…" },
            { "Text.Menu.SplitScreenAvilablePauseScreenAlt", "Dodatkowi lokalni gracze naciśnij [IN=UI_Submit] w grze, aby dołączyć…" },
            { "Text.Menu.ConsolodatedDLCDescription", "Sprawdź swoje umiejętności ucieczki w ekscytującej dodatkowej zawartości do The Escapists 2! Od cyrku po reżim dyktatora – nowe ucieczki, przedmioty i personalizacje!" },
            { "Text.Menu.PasswordDialogTitle", "Wymagane hasło" },
            { "Text.Menu.PasswordDialogBody", "Wprowadź hasło do lobby:" },
            { "Text.Menu.PasswordDialogPlaceholder", "Hasło" },
            { "Text.Menu.PasswordPlaceholder", "Hasło (opcjonalnie)" },
            { "Text.Menu.GameTypeExplained.Public_PC", "Bez hasła każdy może oglądać i dołączyć do gry, w przeciwnym razie potrzebne będzie hasło." },
            { "Text.Menu.WrongPasswordTitle", "Wprowadzone błędne hasło" },
            { "Text.Menu.WrongPasswordBody", "Hasło było nieprawidłowe, spróbuj ponownie." },
            { "Text.Menu.PasswordDialog", "Wymagane hasło" },
            { "Text.Menu.LevelEditorDescription", "Twórz i graj w swoje własne więzienia. Udostępniaj je i hostuj przez Steam Workshop, aby grać z innymi graczami." },
            { "Text.Menu.Campaign.SetupOnlinePrisonFailed", "Nie udało się połączyć online. Czy chcesz wczytać zapis offline?" },
            { "Text.Menu.Legend01", "[IN=UI_Submit] WYBIERZ" },
            { "Text.Menu.Legend02", "[IN=UI_Submit] WYBIERZ [IN=UI_Cancel] WSTECZ" },
            { "Text.Menu.Legend03", "[IN=UI_Submit] WYBIERZ [IN=UI_Cancel] WSTECZ [IN=UI_CycleLeft] [IN=UI_CycleRight] ZMIEŃ WIĘZIENIE" },
            { "Text.Menu.Legend04", "[IN=UI_Submit] WYBIERZ [IN=UI_Cancel] WSTECZ [IN=UI_PrevPage] [IN=UI_NextPage] STRONA W GÓRĘ/STRONA W DÓŁ" },
            { "Text.Menu.Legend05", "[IN=UI_Submit] WYBIERZ [IN=UI_Cancel] WSTECZ [IN=UI_CycleLeft] [IN=UI_CycleRight] ZMIEŃ ZAKŁADKĘ" },
            { "Text.Menu.Legend02_PC", "[IN=UI_Cancel] WSTECZ [IN=UI_Submit] WYBIERZ" },
            { "Text.Menu.Legend03_PC", "[IN=UI_Cancel] WSTECZ [IN=UI_Submit] WYBIERZ [IN=UI_CycleRight] ZMIEŃ WIĘZIENIE" },
            { "Text.Menu.Legend04_PC", "[IN=UI_Cancel] WSTECZ [IN=UI_Submit] WYBIERZ [IN=UI_PrevPage] [IN=UI_NextPage] STRONA W GÓRĘ/STRONA W DÓŁ" },
            { "Text.Menu.Legend05_PC", "[IN=UI_Cancel] WSTECZ [IN=UI_Submit] WYBIERZ [IN=UI_CycleRight] ZMIEŃ ZAKŁADKĘ" },
            { "Text.Menu.Legend06", "[IN=Skip] POMIŃ" },
            { "Text.Menu.Legend07", "[IN=UI_Submit] KONTYNUUJ" },
            { "Text.Menu.Legend08_PC", "[IN=UI_Cancel] WSTECZ [IN=UI_CycleLeft] [IN=UI_CycleRight] PRZEŁĄCZ KLUCZ [IN=UI_PrevPage] [IN=UI_NextPage] RUCH PIĘTRO GÓRA/DÓŁ" },
            { "Text.Menu.Legend08", "[IN=UI_Cancel] WSTECZ [IN=UI_CycleLeft] [IN=UI_CycleRight] PRZEŁĄCZ KLUCZ [IN=UI_PrevPage] [IN=UI_NextPage] ZBLIŻ/ODDALI" },
            { "Text.Menu.Legend09", "[IN=Pause] KONTYNUUJ" },
            { "Text.Menu.Legend10", "[IN=UI_Submit] WYBIERZ" },
            { "Text.Menu.Legend11", "[IN=UI_Cancel] WSTECZ [IN=UI_Submit] WYBIERZ [IN=SecondaryInteraction] POTWIERDŹ [IN=UI_CycleLeft] [IN=UI_CycleRight] ZMIEŃ ZAKŁADKĘ" },
            { "Text.Menu.PressStart", "Naciśnij spację, aby rozpocząć" },
            { "Text.Menu.HoldToCraft", "Przytrzymaj [IN=UI_Submit]" },
            { "Text.Menu.Legend12_PC", "[IN=UI_Cancel] WYJDŹ [IN=UI_Submit] WYBIERZ" },
            { "Text.Menu.Legend12", "[IN=UI_Submit] WYBIERZ [IN=UI_Cancel] WYJDŹ" },
            { "Text.Menu.NoGamesAvailable", "Obecnie brak dostępnych gier" },
            { "Text.Menu.ProfanityFilter", "Filtr wulgaryzmów" },
            { "Text.Menu.ControlInputHelpTitle", "USTAWIENIA STEROWANIA GRACZA 1" },
            { "Text.Menu.ControlInputHelpBody", "Jeżeli wybrano ‘Mysz, Klawiatura i Kontroler’, Gracz 1 może korzystać z myszy, klawiatury i podłączonego kontrolera.\\n\\nJeżeli wybrano ‘Tylko Mysz i Klawiatura’, Gracz 1 będzie ograniczony do myszy i klawiatury. Naciśnięcie przycisku na kontrolerze doda drugiego lokalnego gracza, który będzie korzystał z tego kontrolera." },
            { "Text.Menu.DLC", "DLC" },
            { "Text.Menu.NewDLC", "Nowe DLC dostępne" },
            { "Text.Menu.DLCName01", "The Glorious Regime" },
            { "Text.Menu.DLCDescription01", "Obszerna kampania propagandowa Wspaniałego Przywódcy zmanipulowała mieszkańców tej niegdyś szczęśliwej i wolnej miejscowości, aby uwierzyli, że żyją w największym i najbardziej dostatnim kraju na świecie. Ale ty wiesz swoje…" },
            { "Text.Menu.DLCName02", "Wicked Ward" },
            { "Text.Menu.DLCDescription02", "Niegdyś miejsce odpoczynku, te mury teraz mieszczą laboratoria i przerażające eksperymenty. Idealne miejsce, by eksperymentować na więźniach! Uwaga… nieumarli pracownicy pilnują porządku, a duchy wędrują korytarzami…" },
            { "Text.Menu.GoToStore", "PRZEJDŹ DO SKLEPU" },
            { "Text.Menu.PrisonDLC", "WIĘZIENIA" },
            { "Text.Menu.SeasonPassName", "Karnet Sezonowy" },
            { "Text.Menu.SeasonPassDescription", "Uzyskaj dostęp do dodatkowej zawartości w The Escapists 2 dzięki karnetowi sezonowemu. Sprawdź swoje umiejętności w ucieczce z trzech ekscytujących więzień z nowymi przedmiotami, personalizacjami i sposobami ucieczki!" },
            { "Text.Menu.Legend02A", "[IN=UI_Submit] WYBIERZ [IN=UI_Cancel] WSTECZ" },
            { "Text.Menu.SplitScreenAvilable", "Dodatkowi gracze lokalni naciśnij [TICON=A_Icon], aby dołączyć…" },
            { "Text.Menu.SplitScreenAvilablePauseScreen", "Wznów grę, następnie dodatkowi gracze lokalni naciśnij [TICON=A_Icon], aby dołączyć…" },
            { "Text.Menu.SecurityBoardTitle", "Poziom Bezpieczeństwa" },
            { "Text.Menu.SecurityBoardBody1", "Poziom bezpieczeństwa jest wyświetlany pod mini-mapą. Wzrasta, jeśli więzień opuści rutynę lub jeśli strażnik znajdzie uszkodzenia w więzieniu i zgłosi je do pokoju strażników. Poziom bezpieczeństwa obniża się na początku każdego dnia." },
            { "Text.Menu.SecurityBoardBody2", "Z każdą gwiazdką więcej strażników i psów patroluje więzienie. Przy pięciu gwiazdkach więzienie przechodzi w Lockdown, a wypuszczany jest zespół SWAT. Lockdown następuje również natychmiast, jeśli więzień opuści apel lub zostanie złapany na niszczeniu więzienia." },
            { "Text.Menu.DLCName03", "Świąteczna Inwigilacja" },
            { "Text.Menu.DLCDescription03", "To nowoczesne, czyste więzienie ma wszystko: najnowocześniejszy sprzęt, zaawansowane środki bezpieczeństwa… i dyrektora teatralnego bardziej zainteresowanego pantomimą niż dobrem więźniów. Przeocz tandetne dekoracje, a może pojawi się okazja do ucieczki!" },
            { "Text.Menu.DLCName04", "Wielki Cyrkowy Ucieczka" },
            { "Text.Menu.DLCDescription04", "Zapraszamy! Ten wędrowny cyrk jest wyjątkowy, więźniowie występują dla twojej rozrywki! Przyjdź i podziwiaj egzotyczne zwierzęta, sztuczki magiczne i pokaz więźniów próbujących jeździć na monocyklu! Bez obaw, bezpieczeństwo jest priorytetem! Ci klauni nie uciekną!" },
            { "Text.Menu.DLCName05", "Lochy i Taśma" },
            { "Text.Menu.DLCDescription05", "Po setkach lat trzymania armii z daleka, ten przebudowany zamek teraz trzyma dzisiejszych seryjnych uciekinierów! Kto powiedział, że rycerstwo umarło… miał rację. Unikaj ciężko opancerzonych strażników jak zarazy i uważaj na więźniów, którzy szukają okazji, by sięgnąć po średniowieczne metody!" },
            { "Text.Menu.DLCName06", "Śnieżna Ucieczka" },
            { "Text.Menu.DLCDescription06", "Porzucając listę niegrzecznych dzieci na rzecz listy bogaczy, Mikołaj otworzył swój własny, dochodowy sklep online, wysyłający produkty na cały świat! Lepiej zachowuj się grzecznie – kawałek węgla w biurku to najmniejszy z twoich problemów!" }
        };
    }
}
