using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TE2PolishLocalizationNamespace
{
    public static class Tutorial
    {
        public static readonly Dictionary<string, string> Data = new Dictionary<string, string>
        {
            { "Text.Tutorial.A", "Pewnego ranka wstałem i pomyślałem sobie: dość tego. Chcę stąd wyjść. Czas opuścić to miejsce." },
            { "Text.Tutorial.B", "Otworzyłem biurko za pomocą [IN=Open] i zabrałem wszystko, co było w środku używając [IN=UI_Submit], bo wiedziałem, że będę potrzebować tych przedmiotów później, żeby się stąd wydostać…" },
            { "Text.Tutorial.C", "Stworzyłem broń, naciskając [IN=Open Ingame Menu], aby sprawdzić, jakie przedmioty są potrzebne do jej wykonania. Zaznaczyłem je i połączyłem dwa przedmioty za pomocą [IN=UI_Submit]." },
            { "Text.Tutorial.C_PC", "Stworzyłem broń, naciskając [IN=Hotkey_CraftingMenu], aby sprawdzić, jakie przedmioty są potrzebne do jej wykonania. Zaznaczyłem je i połączyłem dwa przedmioty za pomocą [IN=UI_Submit]." },
            { "Text.Tutorial.D", "Podczas wykonywania skomplikowanego planu ucieczki kluczem do sukcesu jest nie przyciągać uwagi. Skorzystałem z Żółtej Strzałki, która prowadziła mnie do następnej rutyny: Apelu!" },
            { "Text.Tutorial.E", "Na Apelu, starając się zachować spokój, zastanawiałem się… Czy wiedzą, że coś kombinuję? Że mam plan? Oddech mi się wyrównał, próbując uspokoić się w tej napiętej sytuacji…" },
            { "Text.Tutorial.F", "Odrzucając strach, tak jak robiłem to przez całe życie, zauważyłem więźnia o imieniu Chuck! Miałem przeczucie, że Zielona Strzałka przy schodach próbuje mi coś powiedzieć…" },
            { "Text.Tutorial.G", "Nikt nie patrzył, więc wyposażyłem Mace w Skarpetkę używając [IN=UI_CycleLeft] lub [IN=UI_CycleRight]. Napędzany chęcią ucieczki użyłem [IN=CombatTargetting], aby zablokować cel, a następnie zaatakowałem [IN=Attack], próbując go ogłuszyć!" },
            { "Text.Tutorial.H", "Gdy Chuck był nieprzytomny, zabrałem mu klucz używając [IN=Open], aby dostać się do jego kieszeni i wziąć go przyciskiem [IN=UI_Submit]. Następnie szybko udałem się do Pracowni Dowodów naprzeciw, używając klucza…" },
            { "Text.Tutorial.I", "Otwierając biurko za pomocą [IN=Open] ukradłem narzędzia wewnątrz, zaznaczając je i biorąc przyciskiem [IN=UI_Submit]. Wszystko szło po mojej myśli… Czy to nie było zbyt piękne, by było prawdziwe?! Miałem wrażenie, że szczęście mi sprzyja!" },
            { "Text.Tutorial.J", "Daj mi chwilę, muszę nałożyć krem do opalania: piekę się tutaj! W każdym razie, wiedziałem dokładnie, gdzie użyć moich narzędzi! Ponownie użyłem Zielonej Strzałki, aby się kierować…" },
            { "Text.Tutorial.K", "Aby ukryć swoje działania, podniosłem Prześcieradło trzymając [IN=PrimaryInteraction] stojąc obok niego. Wyposażyłem je używając [IN=UI_CycleLeft] lub [IN=UI_CycleRight], a następnie powiesiłem je na kratkach celi obok drzwi naciskając [IN=Use]." },
            { "Text.Tutorial.L", "Znasz powiedzenie 'co z oczu, to z serca'? Na tej zasadzie: z Kilofem w ręku, odkopywałem ścianę celi używając [IN=SecondaryInteraction]." },
            { "Text.Tutorial.L_PC", "Znasz powiedzenie 'co z oczu, to z serca'? Na tej zasadzie: z Kilofem w ręku, odkopywałem ścianę celi używając [IN=Use]." },
            { "Text.Tutorial.M", "Gdy moja Energia była niska, na szczęście była pora posiłku. Korzystając z Zielonej Strzałki udałem się do stołówki, wziąłem tacę z pożywnym jedzeniem używając [IN=Open] i usiadłem używając [IN=UI_Submit]." },
            { "Text.Tutorial.N", "Przerażony zdołałem zjeść, co przywróciło moją Energii, i utrzymałem w sobie 'jedzenie'… Ten dziwny zapach, który z niego wydobywał się, nadal mnie prześladuje…" },
            { "Text.Tutorial.O", "Po uzupełnieniu energii i mając wolność jako cel, udało mi się utrzymać w sobie 'jedzenie', wziąłem głęboki oddech i kontynuowałem podążanie za Zieloną Strzałką… Co było bardzo pomocne!" },
            { "Text.Tutorial.P", "…Odpychając obrzydliwe posmaki i niestrawność na bok – czas wrócić do pracy i kontynuować odkopywanie ściany celi. Z Kilofem w ręku, wznowiłem plan naciskając [IN=SecondaryInteraction]." },
            { "Text.Tutorial.P_PC", "…Odpychając obrzydliwe posmaki i niestrawność na bok – czas wrócić do pracy i kontynuować odkopywanie ściany celi. Z Kilofem w ręku, wznowiłem plan naciskając [IN=Use]." },
            { "Text.Tutorial.Q", "Ooh! Podasz mi krem do opalania, proszę, kumplu?\\n\\nWszystko wyglądało dobrze… Ze ścianą już odkrytą, przeszedłem do następnego pomieszczenia." },
            { "Text.Tutorial.R", "Z dala od ciekawskich oczu, otworzyłem biurko używając [IN=Open] i zabrałem wszystko w nim, zaznaczając każdy przedmiot po kolei i dodając je do mojego ekwipunku przyciskiem [IN=UI_Submit]." },
            { "Text.Tutorial.S", "Trzymając [IN=PrimaryInteraction] podniosłem biurko i umieściłem je pod wentylacją w oznaczonym miejscu naciskając [IN=HUD_Drop]." },
            { "Text.Tutorial.T", "Gdy zaznaczyłem Moje Zastrzyki Adrenaliny i użyłem ich przyciskiem [IN=Use], popchnąłem biurko, wspiąłem się na nie, wyposażyłem nożyce i nacisnąłem [IN=Use], aby przeciąć pokrywę wentylacyjną nad sobą." },
            { "Text.Tutorial.U", "Więcej kremu do opalania, proszę, ta gorącość jest okrutna!\\n\\nNastępnie wspiąłem się do wentylacji z biurka używając [IN=PrimaryInteraction] i poszedłem w prawo." },
            { "Text.Tutorial.V", "To błogość! Złote plaże, pluskające fale…\\n\\nPo dotarciu w prawo, wyposażyłem nożyce i przeciąłem zamkniętą pokrywę wentylacyjną używając [IN=Use], aby móc zejść na dół."},
            { "Text.Tutorial.W", "Dlaczego, o dlaczego, nie wziąłem okularów przeciwsłonecznych?!\\n\\nPo przecięciu pokrywy wentylacyjnej, zszedłem w dół otworu używając [IN=PrimaryInteraction]." },
            { "Text.Tutorial.X", "A POTEM BUM! Wszystkie światła zaczęły migać! Jeden ze strażników musiał zauważyć, że mnie brakuje! Wpadłem w panikę… Ale jak obiecano, czekał na mnie Łopata, którą podniosłem używając [IN=Pickup]." },
            { "Text.Tutorial.Y", "Pocąc się jak po walce z wozem strażackim, wyposażyłem Łopatę używając [IN=UI_CycleLeft] lub [IN=UI_CycleRight] i gorączkowo zacząłem kopać używając [IN=Use] – tuż przed drzwiami!" },
            { "Text.Tutorial.Z", "Masz może wachlarz, którym mógłbyś mnie ochłodzić? Aaaah, dzięki! W każdym razie, gdy dziura była już całkowicie wykopana, zszedłem do niej używając [IN=PrimaryInteraction]." },
            { "Text.Tutorial.AA", "Wykorzystując moją Łopatę, kontynuowałem kopanie przed siebie, używając [IN=Use] w pośpiechu, ale precyzyjnie…" },
            { "Text.Tutorial.AB", "Oczyściłem dwie podziemne przestrzenie przed sobą, wykopałem w drugiej otwartej przestrzeni przed sobą używając [IN=Use], co pozwoliło mi wyjść po drugiej stronie na parking – jeśli moje obliczenia były poprawne!" },
            { "Text.Tutorial.AC", "To był słodki moment… Widziałem światło dzienne, prawie już byłem! Wchodząc do pustego miejsca i naciskając [IN=PrimaryInteraction], wyszedłem z podziemia przez dziurę…" },
            { "Text.Tutorial.AD", "Na parkingu zobaczyłem coś, co wyglądało na przydatne… Gdy słońce paliło w moje oczy po ciemności, przechodząc przez parking, podniosłem lśniący przedmiot przyciemniony słońcem naciskając [IN=Pickup]." },
            { "Text.Tutorial.AE", "PERFEKT! Zdobyłem nożyce. Udałem się do ogrodzenia, wyposażyłem nożyce i zacząłem przeskakiwać ostatnią przeszkodę, naciskając [IN=Use] aby rozpocząć cięcie…" },
            { "Text.Tutorial.AF", "Wyszedłem... Wreszcie wyszedłem!\\n\\nAle pomijając historie… Takie jest życie, co nie? O to w tym chodzi…" },
            { "Tutorial.Intro.A", "Więc… Chcesz posłuchać, jak ja, Niesamowity Robinson uciekłem, co nie?" },
            { "Tutorial.Intro.AA", "Tak, jeśli chcesz…" },
            { "Tutorial.Intro.B", "Postaw się na moim miejscu przez chwilę, a opowiem ci, jak to było…" },
            { "Tutorial.Intro.BA", "Więc tak to się potoczyło…" },
            { "Tutorial.Outro.Player", "Cóż, to FASCYNUJĄCE rzeczy Robinson… Naprawdę…" },
            { "Tutorial.Outro.RobinsonA", "Dzięki…! Jestem zaskoczony, że jeszcze mnie nie złapano…" },
            { "Tutorial.Outro.RobinsonB", "…Wątpię, żeby mnie teraz kiedykolwiek złapali!" },
            { "Tutorial.Outro.A", "STAN! ROBINSON!" },
            { "Tutorial.Outro.B", "Cóż wtedy…" },
            { "Tutorial.Outro.C", "Dlaczego tak długo ci to zajęło?!" },
            { "Text.Tutorial.ObjectiveA", "Zabierz przedmioty z biurka" },
            { "Text.Tutorial.ObjectiveB", "Stwórz Mace w Skarpetce" },
            { "Text.Tutorial.ObjectiveC", "Weź udział w Apelu" },
            { "Text.Tutorial.ObjectiveD", "Czekaj na dalsze instrukcje" },
            { "Text.Tutorial.ObjectiveE", "Zlokalizuj 'Chucka'" },
            { "Text.Tutorial.ObjectiveF", "Ogłusz więźnia 'Chucka'" },
            { "Text.Tutorial.ObjectiveG", "Zdobądź Plastikowy Cyjanowy Klucz" },
            { "Text.Tutorial.ObjectiveH", "Udaj się do Pracowni Dowodów" },
            { "Text.Tutorial.ObjectiveI", "Zabierz przedmioty z biurka" },
            { "Text.Tutorial.ObjectiveJ", "Zejdź na dół do oznaczonej celi" },
            { "Text.Tutorial.ObjectiveK", "Zdejmij prześcieradło" },
            { "Text.Tutorial.ObjectiveL", "Powieś prześcieradło na kratkach" },
            { "Text.Tutorial.ObjectiveM", "Odkop ścianę celi" },
            { "Text.Tutorial.ObjectiveN", "Kontynuuj odkopywanie ściany" },
            { "Text.Tutorial.ObjectiveO", "Podnieś tacę w stołówce" },
            { "Text.Tutorial.ObjectiveP", "Usiądź na swoim zwykłym miejscu" },
            { "Text.Tutorial.ObjectiveQ", "Ciesz się pysznym 'posiłkiem'" },
            { "Text.Tutorial.ObjectiveR", "Wróć do oznaczonej celi" },
            { "Text.Tutorial.ObjectiveS", "Przebij się do sąsiedniego pomieszczenia" },
            { "Text.Tutorial.ObjectiveT", "Zabierz przedmioty z biurka" },
            { "Text.Tutorial.ObjectiveTA", "Postaw biurko w oznaczonym miejscu" },
            { "Text.Tutorial.ObjectiveU", "Przetnij wentyl z góry biurka" },
            { "Text.Tutorial.ObjectiveUA", "Kontynuuj przecinanie wentylu…" },
            { "Text.Tutorial.ObjectiveV", "Wspinaj się do wentylu" },
            { "Text.Tutorial.ObjectiveW", "Przetnij kolejną pokrywę wentylacyjną" },
            { "Text.Tutorial.ObjectiveX", "Kontynuuj przecinanie pokrywy wentylu…" },
            { "Text.Tutorial.ObjectiveY", "Wyjdź z wentylu" },
            { "Text.Tutorial.ObjectiveZ", "Podnieś łopatę" },
            { "Text.Tutorial.ObjectiveAA", "Kop w dół do podziemi" },
            { "Text.Tutorial.ObjectiveAB", "Kontynuuj kopanie w dół do podziemi…" },
            { "Text.Tutorial.ObjectiveAC", "Ześlizgnij się do podziemi" },
            { "Text.Tutorial.ObjectiveAD", "Kop przed siebie w podziemiach" },
            { "Text.Tutorial.ObjectiveAE", "Kontynuuj kopanie przed siebie w podziemiach…" },
            { "Text.Tutorial.ObjectiveAF", "Kontynuuj kopanie przed siebie w podziemiach…" },
            { "Text.Tutorial.ObjectiveAG", "Kontynuuj kopanie przed siebie w podziemiach…" },
            { "Text.Tutorial.ObjectiveAH", "Kop w górę w pustej przestrzeni" },
            { "Text.Tutorial.ObjectiveAI", "Kontynuuj kopanie w górę w pustej przestrzeni…" },
            { "Text.Tutorial.ObjectiveAJ", "Opuszcz podziemia przez dziurę" },
            { "Text.Tutorial.ObjectiveAK", "Podnieś nożyce" },
            { "Text.Tutorial.ObjectiveAL", "Przetnij ogrodzenie" },
            { "Text.Tutorial.ObjectiveAM", "Kontynuuj przecinanie ogrodzenia…" },
            { "Text.Tutorial.ObjectiveAN", "UCIEKNIJ!" },

            { "Text.Tutorial.A_PC", "Pewnego ranka wstałem i pomyślałem: dość tego. Chcę stąd wyjść. Wstałem z łóżka i pobiegłem do biurka używając [IN=Move_Vertical+], [IN=Move_Horizontal+], [IN=Move_Vertical-], [IN=Move_Horizontal-]." },
            { "Text.Tutorial.G_PC", "Bez niczyjej uwagi, wyposażyłem Mace w skarpetę używając [IN=UI_CycleLeft] lub [IN=UI_CycleRight]. Chcąc uciec, użyłem [IN=CombatTargetting] aby zablokować cel, a następnie zaatakowałem przyciskiem [IN=Attack] by go ogłuszyć!" },
            { "Text.Tutorial.K_PC", "Aby ukryć swoje działania, podniosłem Prześcieradło przytrzymując [IN=PrimaryInteraction] stojąc obok niego. Wyposażyłem je używając [IN=UI_CycleRight], a następnie zawiesiłem na kratkach przy drzwiach celi naciskając [IN=Use]." },
            { "Text.Tutorial.M_PC", "Mając niską energię, na szczęście była pora posiłku. Kierując się Zieloną Strzałką, udałem się do stołówki, wziąłem tacę z jedzeniem używając [IN=Open], a następnie usiadłem na swoim miejscu przyciskiem [IN=PrimaryInteraction]." },
            { "Text.Tutorial.S_PC", "Przytrzymując [IN=PrimaryInteraction], podniosłem biurko i postawiłem je pod wentylacją w oznaczonym miejscu naciskając [IN=PrimaryInteraction]." },
            { "Text.Tutorial.Y_PC", "Pocąc się jak po walce z wozem strażackim, wyposażyłem Łopatę przy [IN=UI_CycleRight], i gorączkowo zacząłem kopać przy użyciu [IN=Use] - tuż przed drzwiami!" },

            { "HUD.Tutorial.Combat", "WALKA" },
            { "HUD.Tutorial.Attack", "Atak" },
            { "HUD.Tutorial.Block", "Blok" },
            { "HUD.Tutorial.TargetLock", "Włącz blokadę celu" },
            { "HUD.Tutorial.CycleTarget", "Zmiana zablokowanych celów" },
            { "HUD.Tutorial.Routine", "ROUTINE" },
            { "HUD.Tutorial.RoutineInfo", "Podążaj za żółtą strzałką do następnego obowiązku. Trzymaj się rutyny, by nie wzbudzać podejrzeń strażników." },
            { "HUD.Tutorial.Alertness", "POZIOM BEZPIECZEŃSTWA" },
            { "HUD.Tutorial.AlertnessInfo", "Poziom bezpieczeństwa rośnie, gdy strażnicy odkryją uszkodzenia więzienia, pominięte rutyny lub kontrabandę. Wysoki poziom bezpieczeństwa zwiększa liczbę patroli i uruchamia psy."},
            { "HUD.Tutorial.Status", "STATUS" },
            { "HUD.Tutorial.StatusInfo", "Zdrowie, Wytrzymałość i Podejrzenia stanowią aktualny status postaci. Podejrzane działania zwiększają twoje podejrzenia wobec strażników."},
            { "HUD.Tutorial.UseItemHeader", "UŻYJ przedmiotu" },
            { "HUD.Tutorial.UseItem", "Użyj przedmiotu" },
            { "HUD.Tutorial.UseItemInfo", "Aby użyć przedmiotu, musisz go wyposażyć. Różne przedmioty mają różne zastosowania." },
            { "HUD.Tutorial.UseInventoryHeader", "Ekwipunek" },
            { "HUD.Tutorial.UseInventory", "Użyj ekwipunku" },
            { "HUD.Tutorial.UseInventoryInfo", "Wybierz przedmiot do wyposażenia. Wyposażone przedmioty można używać lub wyrzucać." },
            { "HUD.Tutorial.TakeItemHeader", "PODNIEŚ przedmiot" },
            { "HUD.Tutorial.TakeItem", "Podnieś przedmiot" },
            { "HUD.Tutorial.TakeItemInfo", "Przedmioty można podnieść tylko jeśli masz miejsce w ekwipunku." },
            { "HUD.Tutorial.DiscardItemHeader", "ODRZUĆ przedmiot" },
            { "HUD.Tutorial.DiscardItem", "Odrzuć przedmiot" },
            { "HUD.Tutorial.DiscardItemInfo", "Przedmioty można upuścić z ekwipunku na podłogę." },
            { "HUD.Tutorial.TaggingHeader", "OZNAZACZANIE" },
            { "HUD.Tutorial.Tagging", "Oznacz lokalizację" },
            { "HUD.Tutorial.TaggingInfo", "Możesz oznaczać lokalizacje w więzieniu, aby każdy gracz widział je na mapie."},
            { "HUD.Tutorial.PickUpLootHeader", "PODNIEŚ/OGRAB" },
            { "HUD.Tutorial.Looting", "Ograć ciało" },
            { "HUD.Tutorial.PickUp", "Podnieś ciało" },
            { "HUD.Tutorial.PickUpLootInfo", "Nieprzytomne postacie można ograbić, podnieść i związać."},
            { "HUD.Tutorial.DesksHeader", "BIURKA" },
            { "HUD.Tutorial.DeskOpen", "Otwórz biurko" },
            { "HUD.Tutorial.DeskPickUp", "Podnieś biurko" },
            { "HUD.Tutorial.DeskClimb", "Na biurka można wejść, idąc w ich stronę." },
            { "HUD.Tutorial.PutDownHeader", "ODŁÓŻ" },
            { "HUD.Tutorial.PutDown", "Odłóż" },
            { "HUD.Tutorial.PutDownInfo", "Postacie i biurka, które podniosłeś, można odłożyć." },
            { "HUD.Tutorial.EmoteHeader", "EMOCJE" },
            { "HUD.Tutorial.Emote", "Emocja" },
            { "HUD.Tutorial.EmoteInfo", "Emocje mogą być używane do komunikacji z innymi graczami podczas gry online." },
            { "HUD.Tutorial.GymHeader", "SIŁOWNIA" },
            { "HUD.Tutorial.GymInfo", "Ćwiczenie na różnych przyrządach zwiększa Siłę lub Kondycję, kosztem części Wytrzymałości." },
            { "HUD.Tutorial.NPCsHeader", "POSTACIE" },
            { "HUD.Tutorial.NPCInfo", "Dostęp do menu innej postaci pozwala przeglądać jej profil i przekazywać przedmioty. Niektórzy więźniowie mają prośby lub sprzedają przedmioty." },
            { "HUD.Tutorial.OutfitsHeader", "UBRANIA" },
            { "HUD.Tutorial.OutfitsInfo", "Twoja postać zaczyna w stroju więźnia. Dodatkowe stroje można ukraść lub stworzyć, np. strażnika lub medyka, aby ułatwić ucieczkę." },
            { "HUD.Tutorial.QuestLogHeader", "PRZYSŁUGI" },
            { "HUD.Tutorial.QuestLogInfo", "NPC w więzieniach mają przysługi, które możesz wykonać w zamian za pieniądze i nagrody przedmiotowe.\\n\\nKorzystaj z markera celu na minimapie, aby się kierować."},
            { "HUD.Tutorial.CraftingHeader", "RZEMIOSŁO" },
            { "HUD.Tutorial.CraftingInfo", "Przedmioty takie jak narzędzia i broń można tworzyć z przedmiotów znalezionych w więzieniu. Rzemiosło podzielone jest na 5 poziomów Inteligencji, które określają dostępne przepisy." },
            { "HUD.Tutorial.KeysHeader", "KLUCZE/KARTY DOSTĘPU" },
            { "HUD.Tutorial.KeysInfo", "Różne drzwi mogą mieć odpowiadające im kolorowe klucze lub karty dostępu, które można ukraść i kopiować. Kopie zużywają się z czasem, a kradzież oryginałów podniesie Poziom Bezpieczeństwa do LOCKDOWN!" },
            { "HUD.Tutorial.DogsHeader", "PSY" },
            { "HUD.Tutorial.DogsInfo", "Psy są wypuszczane w miarę wzrostu Poziomu Bezpieczeństwa więzienia. Psy śledzą więźniów i nie można ich powstrzymać." },
            { "HUD.Tutorial.VisitorsHeader", "Odwiedzający" },
            { "HUD.Tutorial.VisitorsInfo", "Podczas wolnych okresów odwiedzający mogą przyjść do ciebie, gdy siedzisz w pokoju odwiedzin. Jeśli masz szczęście, mogą przynieść prezent!" },
            { "HUD.Tutorial.StatsHeader", "STATYSTYKI" },
            { "HUD.Tutorial.StatsInfo", "Siła, Kondycja i Inteligencja tworzą statystyki postaci. Siła decyduje o obrażeniach, Kondycja o utracie Wytrzymałości, a Inteligencja o zdolności rzemieślniczej."},
            { "HUD.Tutorial.SabotageHeader", "SABOTAŻ" },
            { "HUD.Tutorial.SabotageInfo", "Prace innych więźniów można sabotować, aby je stracili. Pobicie właściciela pracy to pewny sposób." },
            { "HUD.Tutorial.EscapingHeader", "UCIECZKA" },
            { "HUD.Tutorial.EscapingInfo", "Uważaj na patrole strażników, aby znaleźć słabe punkty więzienia. Znajdź przedmioty i łącz je, aby stworzyć nowe, które pomogą ci uciec." },
            { "HUD.Tutorial.InfirmaryHeader", "INTERNAT" },
            { "HUD.Tutorial.InfirmaryInfo", "Gdy Zdrowie postaci spadnie do zera, zostanie zabrana do Internatu przez Medyka. Leżenie w łóżku szybko przywróci pełne Zdrowie." },
            { "HUD.Tutorial.StudyRoomsHeader", "POMIESZCZENIE DO NAUKI" },
            { "HUD.Tutorial.StudyRoomsInfo", "W pokojach nauki można wykonywać ćwiczenia zwiększające Inteligencję. Interakcja z minigrą w odpowiednim pokoju rozpoczyna ćwiczenie." },
            { "HUD.Tutorial.IntellectMinigameHeader", "ZWIĘKSZANIE INTELIGENCJI" },
            { "HUD.Tutorial.IntellectMinigameInfo", "Postępuj zgodnie z instrukcjami na ekranie, aby zwiększyć Inteligencję postaci. Im wyższa Inteligencja, tym więcej przepisów możesz wykorzystać do tworzenia przedmiotów."},
            { "HUD.Tutorial.FoodHallHeader", "JADALNIA" },
            { "HUD.Tutorial.FoodHallInfo", "Jedzenie przywraca Zdrowie i Wytrzymałość. Podejdź do bufetu, weź jedzenie i usiądź, aby je zjeść."},
            { "HUD.Tutorial.SecurityRoomHeader", "POKÓJ BEZPIECZEŃSTWA" },
            { "HUD.Tutorial.SecurityRoomInfo", "Strażnicy rejestrują podejrzane zachowania, co zwiększa Poziom Bezpieczeństwa. Ogłuszenie strażnika, który chce zgłosić coś podejrzanego, uniemożliwi mu to!" },
            { "HUD.Tutorial.TransportPrisonsHeader", "WIĘZIENIA TRANSPORTOWE" },
            { "HUD.Tutorial.TransportPrisonsInfo", "Te więzienia, znajdujące się w pojazdach, trzeba opuścić w krótkim czasie. Rutyny nie obowiązują, dając więcej czasu na skradanie się i walkę."},
            { "HUD.Tutorial.LockdownHeader", "LOCKDOWN" },
            { "HUD.Tutorial.LockdownInfo", "Gdy Poziom Bezpieczeństwa osiągnie 5 gwiazdek, więzienie przechodzi w LOCKDOWN. Przez określony czas każdy więzień poza celą zostanie znaleziony i ukarany!"},
            { "HUD.Tutorial.GuardTowersHeader", "WIEŻE STRAŻNICZE" },
            { "HUD.Tutorial.GuardTowersInfo", "Wieże strażnicze obserwują teren więzienia. W dzień snajperzy pilnują podejrzanej aktywności, w nocy reflektory patrolują teren."},
            { "HUD.Tutorial.SolitaryHeader", "IZOLATORIUM" },
            { "HUD.Tutorial.SolitaryInfo", "Za złamanie zasad więźniowie trafiają do Izolatorium. Gracze mogą przeczekać czas lub obierać ziemniaki, by szybciej wyjść!"},
            { "HUD.Tutorial.FreePeriodsHeader", "CZAS WOLNY" },
            { "HUD.Tutorial.FreePeriodsInfo", "Czas wolny można wykorzystać na naukę wzorców strażników, zbieranie zapasów, rzemiosło i planowanie ucieczki."},
            { "HUD.Tutorial.ShowersHeader", "PRYSZNICE" },
            { "HUD.Tutorial.ShowersInfo", "Wejście pod prysznic przywraca Zdrowie i Wytrzymałość. Podejdź do kabiny i wchodź, aby rozpocząć kąpiel."},
            { "HUD.Tutorial.LightsOutHeader", "CZAS SNU" },
            { "HUD.Tutorial.LightsOutInfo", "Podczas Czasu Snu gracze powinni wrócić do celi. Jeśli wszyscy zdecydują się spać, czas zostanie przyspieszony do poranka."},
            { "HUD.Tutorial.CraftingTreeHeader", "DRZEWO RZEMIOSŁA" },
            { "HUD.Tutorial.CraftingTreeInfo", "Pięć poziomów Inteligencji określa dostępne przedmioty do tworzenia. Wyższa Inteligencja pozwala tworzyć bardziej złożone przedmioty."},
            { "HUD.Tutorial.StatDeteriorationHeader", "UTRATA STATYSTYK" },
            { "HUD.Tutorial.StatDeteriorationInfo", "Po utracie przytomności i zabraniu do Internatu lub Izolatorium stracisz wszystkie kontrabandowe przedmioty z ekwipunku."},
            { "HUD.Tutorial.BasicToolsHeader", "PODSTAWOWE NARZĘDZIA" },
            { "HUD.Tutorial.BasicToolsInfo", "Plastikowe sztućce mogą służyć jako podstawowe narzędzia do cięcia, dłutowania i kopania. Szukaj słabych punktów więzienia, np. płotów."},
            { "HUD.Tutorial.JobSabotagedHeader", "NIE TŁUMACZYĆ" },
            { "HUD.Tutorial.JobSabotagedInfo", "NIE TŁUMACZYĆ" },
            { "HUD.Tutorial.UndergroundDigHeader", "KOPANIE" },
            { "HUD.Tutorial.UndergroundDigInfo", "Mając wyposażoną łopatę, używaj kolorowego celownika jako odniesienia. Zielony oznacza możliwość działania. Kopanie w pustej podziemnej płytce pozwala kopać w górę."},
            { "HUD.Tutorial.AccessCraft", "Otwórz menu rzemiosła" },
            { "HUD.Tutorial.QuickMouldHeader", "FORMA/KLON" },
            { "HUD.Tutorial.QuickMouldInfo", "Podczas rabowania nieprzytomnego strażnika możesz szybko stworzyć formę jego klucza lub sklonować kartę dostępu. Musisz mieć co najmniej 50+ inteligencji, aby wykonać tę czynność. Do klucza potrzebny jest 'Kawałek masy plastycznej', a do karty 'Płytka obwodu' i 'Drut'." },
            { "HUD.Tutorial.Hold", "(Przytrzymaj)" },
            { "HUD.Tutorial.JobOfficeHeader", "BIURO PRACY" },
            { "HUD.Tutorial.JobOfficeInfo", "Musisz odwiedzić Biuro Pracy, gdy nie masz pracy. Rozmowa z personelem nagradza pieniędzmi. Aplikuj o pracę przez Tablicę ogłoszeń na zewnątrz Biura."},
            { "HUD.Tutorial.QuestArrowHeader", "STRZAŁKA CELU" },
            { "HUD.Tutorial.QuestArrowInfo", "Podążaj za zielonymi strzałkami na ekranie do następnego celu podczas określonych przysług."},
            { "HUD.Tutorial.Job.ShoemakerTitle", "PRACA SZEWCA" },
            { "HUD.Tutorial.Job.ShoemakerBodyTextA", "Weź podeszwę i szkielet buta z pojemnika na materiały, a następnie połącz je."},
            { "HUD.Tutorial.Job.ShoemakerBodyTextB", "Umieść gotowy but w maszynie przetwarzającej. Po zakończeniu zabierz skończony but."},
            { "HUD.Tutorial.Job.ShoemakerBodyTextC", "Połącz dwa skończone buty, aby zrobić parę. Umieść ją w skrzyni na gotowe buty."},
            { "HUD.Tutorial.Job.PaintingTitle", "PRACA MALARZA" },
            { "HUD.Tutorial.Job.PaintingBodyTextA", "Weź pędzel i wiadro farby z pojemnika. Połącz je, aby przygotować pędzel."},
            { "HUD.Tutorial.Job.PaintingBodyTextB", "Znajdź ściany do pomalowania. Wybierz przygotowany pędzel i użyj go na ścianie."},
            { "HUD.Tutorial.Job.PaintingBodyTextC", "Gdy pędzel skończy farbę, musisz przygotować go ponownie."},
            { "HUD.Tutorial.Job.WasteDisposalTitle", "PRACA PRZY ODPADACH" },
            { "HUD.Tutorial.Job.WasteDisposalBodyTextA", "Weź maskę i rękawice gumowe z pojemnika."},
            { "HUD.Tutorial.Job.WasteDisposalBodyTextB", "Zbierz worki z odpadami z pojemnika na odpady."},
            { "HUD.Tutorial.Job.WasteDisposalBodyTextC", "Umieść je w odpowiednim spalaczu, gdzie zostaną zniszczone."},
            { "HUD.Tutorial.Job.PlumbingTitle", "PRACA HYDRAULIKA" },
            { "HUD.Tutorial.Job.PlumbingBodyTextA", "Weź przepychacz z pojemnika." },
            { "HUD.Tutorial.Job.PlumbingBodyTextB", "Znajdź odpowiednie toalety i użyj przepychacza." },
            { "HUD.Tutorial.Job.FarmingTitle", "PRACA NA FARMIE" },
            { "HUD.Tutorial.Job.FarmingBodyTextA", "Weź kielnię i nasiona z pojemników." },
            { "HUD.Tutorial.Job.FarmingBodyTextB", "Użyj kielni na przygotowanej glebie, aby zrobić mały dołek." },
            { "HUD.Tutorial.Job.FarmingBodyTextC", "Po wykopaniu dołka, wybierz nasiona i użyj ich w dołku."},
            { "HUD.Tutorial.Job.FarmingBodyTextD", "Gdy nasiona zostaną wsadzone, użyj kielni na półwsadzonych nasionach."},
            { "HUD.Tutorial.Job.FarmingBodyTextE", "Powtarzaj, aż osiągniesz wymagany limit." },
            { "HUD.Tutorial.Job.MiningTitle", "PRACA W KOPALNI" },
            { "HUD.Tutorial.Job.MiningBodyTextA", "Weź ciężkie ochraniacze z pojemnika." },
            { "HUD.Tutorial.Job.MiningBodyTextB", "Weź kolorowe kamienie ze składu." },
            { "HUD.Tutorial.Job.MiningBodyTextC", "Umieść je na odpowiednich przenośnikach taśmowych." },
            { "HUD.Tutorial.Job.BlacksmithTitle", "PRACA KUŹNIKA" },
            { "HUD.Tutorial.Job.BlacksmithBodyTextA", "Weź blachy metalowe z pojemnika. Umieść je w maszynie do hartowania." },
            { "HUD.Tutorial.Job.BlacksmithBodyTextB", "Wyjmij tabliczkę pamiątkową z maszyny i włóż do pojemnika na gotowe przedmioty." },
            { "HUD.Tutorial.Job.EngineeringTitle", "PRACA INŻYNIERSKA" },
            { "HUD.Tutorial.Job.EngineeringBodyTextA", "Weź lutownicę i okulary ochronne z pojemnika." },
            { "HUD.Tutorial.Job.EngineeringBodyTextB", "Podążaj za strzałką celu do docelowej skrzynki elektrycznej." },
            { "HUD.Tutorial.Job.EngineeringBodyTextC", "Wypełnij pasek do oznaczonego miejsca i utrzymaj go tam aż do zakończenia."},
            { "HUD.Tutorial.Job.WoodworkTitle", "PRACA STOLARSKA" },
            { "HUD.Tutorial.Job.WoodworkBodyTextA", "Weź 2 kawałki drewna i 1 klej do drewna z pojemnika." },
            { "HUD.Tutorial.Job.WoodworkBodyTextB", "Połącz dwa kawałki drewna, aby uzyskać niezłożone meble." },
            { "HUD.Tutorial.Job.WoodworkBodyTextC", "Połącz niezłożone meble z klejem, aby uzyskać gotowe do klejenia meble." },
            { "HUD.Tutorial.Job.WoodworkBodyTextD", "Użyj tego przedmiotu na maszynie wykończeniowej." },
            { "HUD.Tutorial.Job.WoodworkBodyTextE", "Weź gotowe meble z maszyny i włóż do pojemnika." },
            { "HUD.Tutorial.Job.KennelsTitle", "PRACA W KENNELACH" },
            { "HUD.Tutorial.Job.KennelsBodyTextA", "Weź miski z pojemnika i ustaw przed boksami dla psów." },
            { "HUD.Tutorial.Job.KennelsBodyTextB", "Weź karmę dla psów z pojemnika i włóż do każdej miski, aby nakarmić psy." },
            { "HUD.Tutorial.Job.KitchenTitle", "PRACA W KUCHNI" },
            { "HUD.Tutorial.Job.KitchenBodyTextA", "Weź formę i nadzienie z lodówki. Stwórz surową tartę z formy i nadzienia." },
            { "HUD.Tutorial.Job.KitchenBodyTextB", "Umieść surową tartę w piekarniku. Po upieczeniu wyjmij ją."},
            { "HUD.Tutorial.Job.KitchenBodyTextC", "Umieść upieczoną tartę na tacy." },
            { "HUD.Tutorial.Job.MailSortingTitle", "PRACA PRZY SORTOWANIU POCZTY" },
            { "HUD.Tutorial.Job.MailSortingBodyTextA", "Weź worek z magazynu i włóż do maszyny sortującej." },
            { "HUD.Tutorial.Job.MailSortingBodyTextB", "Po zakończeniu pracy maszyny, weź kolorowe listy."},
            { "HUD.Tutorial.Job.MailSortingBodyTextC", "Kolorowe listy muszą być umieszczone w odpowiednich pojemnikach." },

            { "HUD.Tutorial.Job.PumpkinBodyTextA", "Weź dynie z pojemnika." },
            { "HUD.Tutorial.Job.PumpkinBodyTextB", "Wydrąż dynie przy stole do wydrążania." },
            { "HUD.Tutorial.Job.PumpkinBodyTextC", "Umieść wydrążone dynie w pojemniku na gotowe dynie." },
            { "HUD.Tutorial.Job.VampireBodyTextA", "Weź brudne szaty wampira z kosza na pranie." },
            { "HUD.Tutorial.Job.VampireBodyTextB", "Włóż brudne szaty wampira do pralki." },
            { "HUD.Tutorial.Job.VampireBodyTextC", "Weź czyste szaty z pralki i powieś je w garderobie." },
            { "HUD.Tutorial.Job.ExperimentBodyTextA", "Weź eksperymentalną karmę i miskę z pojemników." },
            { "HUD.Tutorial.Job.ExperimentBodyTextB", "W każdej komorze połóż miskę i napełnij ją eksperymentalną karmą."},
            { "HUD.Tutorial.Job.TrickOrTreatTextA", "Weź składniki z pojemnika." },
            { "HUD.Tutorial.Job.TrickOrTreatTextB", "Stwórz worek psikusów lub worek niespodziankę." },
            { "HUD.Tutorial.Job.TrickOrTreatTextC", "Przekaż stworzony worek dziecku." },
            { "HUD.Tutorial.Job.ToyMakingBodyTextA", "Weź drewno, puszkę farby i pędzel z pojemnika na materiały" },
            { "HUD.Tutorial.Job.ToyMakingBodyTextB", "Włóż drewno do maszyny wykończeniowej" },
            { "HUD.Tutorial.Job.ToyMakingBodyTextC", "Przygotuj pędzel z puszki farby i pędzla" },
            { "HUD.Tutorial.Job.ToyMakingBodyTextD", "Weź drewnianego żołnierza z maszyny wykończeniowej" },
            { "HUD.Tutorial.Job.ToyMakingBodyTextE", "Wykonaj pomalowanego drewnianego żołnierza z drewnianego żołnierza i przygotowanego pędzla" },
            { "HUD.Tutorial.Job.TreeDecoratingBodyTextA", "Weź ozdoby z pojemnika" },
            { "HUD.Tutorial.Job.TreeDecoratingBodyTextB", "Znajdź pustą choinkę i wejdź w interakcję" },
            { "HUD.Tutorial.Job.TreeDecoratingBodyTextC", "Ukończ minigrę, aby udekorować choinkę" },
            { "HUD.Tutorial.Job.LionFeedingBodyTextA", "Weź stek z pojemnika." },
            { "HUD.Tutorial.Job.LionFeedingBodyTextB", "Wejdź do wybiegu i stań na podium." },
            { "HUD.Tutorial.Job.LionFeedingBodyTextC", "Nakarm lwy." },
            { "HUD.Tutorial.Job.HangingPostersBodyTextA", "Weź klej i Plakat Cyrkowy z pojemnika." },
            { "HUD.Tutorial.Job.HangingPostersBodyTextB", "Przygotuj Plakat z Klejem." },
            { "HUD.Tutorial.Job.HangingPostersBodyTextC", "Umieść Plakaty z Klejem na tablicach przy namiocie." },
            { "HUD.Tutorial.Job.BalloonAnimalBodyTextA", "Weź trzy balony z pojemnika." },
            { "HUD.Tutorial.Job.BalloonAnimalBodyTextB", "Stwórz Balonowe Zwierzątko." },
            { "HUD.Tutorial.Job.BalloonAnimalBodyTextC", "Znajdź klientów na zewnątrz namiotu, którzy chcą balonowe zwierzątko i wręcz im przygotowane zwierzątko. " },
            { "HUD.Tutorial.Job.RelightTorchesBodyTextA", "Weź zapalniczkę i paliwo do pochodni z pojemnika." },
            { "HUD.Tutorial.Job.RelightTorchesBodyTextB", "Znajdź pochodnię, najpierw użyj paliwa do pochodni na zgaszonej pochodni." },
            { "HUD.Tutorial.Job.RelightTorchesBodyTextC", "Następnie użyj zapalniczki, aby ją rozpalić." },
            { "HUD.Tutorial.Job.HorseshoeBodyTextA", "Weź sztabkę metalu z pojemnika." },
            { "HUD.Tutorial.Job.HorseshoeBodyTextB", "Włóż sztabkę metalu do pieca i poczekaj aż się stopi." },
            { "HUD.Tutorial.Job.HorseshoeBodyTextC", "Weź roztopiony metal z pieca i przenieś do kowadła." },
            { "HUD.Tutorial.Job.HorseshoeBodyTextD", "Wykonaj podkowę na kowadle, a następnie umieść ją w pojemniku." },
            { "HUD.Tutorial.Job.HorseshoeB.AnvilNoItem", "Potrzebuję roztopionego metalu…" },
            { "HUD.Tutorial.Job.StonemasonBodyTextA", "Weź blok kamienia z pojemnika i przenieś na biurko." },
            { "HUD.Tutorial.Job.StonemasonBodyTextB", "Rzeź kamień." },
            { "HUD.Tutorial.Job.StonemasonBodyTextC", "Przenieś wyrzeźbiony kamień do pojemnika na gotowe." },
            { "HUD.Tutorial.Job.Stonemason.StoneBlocks", "Bloki kamienia" },
            { "HUD.Tutorial.Job.Stonemason.Carved", "Wyrzeźbione bloki" },
            { "HUD.Tutorial.Job.Stonemason.CarveStone", "Rzeźbić kamień" },
            { "HUD.Tutorial.Job.MinstrelBodyTextA", "Weź replikę lutni z pojemnika." },
            { "HUD.Tutorial.Job.MinstrelBodyTextB", "Znajdź jedno z miejsc przeznaczonych do występów." },
            { "HUD.Tutorial.Job.MinstrelBodyTextC", "Zabawiaj personel i współwięźniów!" },
            { "HUD.Tutorial.Job.DLC06EngineeringBodyTextA", "Weź lutownicę i okulary ochronne z pojemnika." },
            { "HUD.Tutorial.Job.DLC06EngineeringBodyTextB", "Podążaj za strzałką celu do skrzynki elektrycznej." },
            { "HUD.Tutorial.Job.DLC06EngineeringBodyTextC", "Wypełnij pasek do wyznaczonego obszaru i utrzymuj go tam do zakończenia zadania." },
            { "HUD.Tutorial.Job.FeedReindeerBodyTextA", "Weź Pokarm dla Reniferów z pojemnika." },
            { "HUD.Tutorial.Job.FeedReindeerBodyTextB", "Umieść Pokarm w pustych żłobach." },
            { "HUD.Tutorial.Job.FeedReindeerBodyTextC", "Weź Pokrojone Warzywa z pojemnika." },
            { "HUD.Tutorial.Job.FeedReindeerBodyTextD", "Umieść Pokrojone Warzywa w żłobach." },
            { "HUD.Tutorial.Job.FeedReindeer.NeedReindeerFood", "Umieść Pokarm dla Reniferów" },
            { "HUD.Tutorial.Job.FeedReindeer.NeedDicedVegetables", "Umieść Pokrojone Warzywa" },
            { "HUD.Tutorial.Job.FeedReindeer.ReindeerFeed", "Pokarm dla Reniferów" },
            { "HUD.Tutorial.Job.FeedReindeer.DicedVegetables", "Pokrojone Warzywa" },
            { "HUD.Tutorial.Job.DestroyLettersBodyTextA", "Weź worek listów z pojemnika." },
            { "HUD.Tutorial.Job.DestroyLettersBodyTextB", "Wrzuć je do pieca." },

            { "Text.Robinson.Favour.Digging", "Kopanie" },
            { "Text.Robinson.Favour.Chipping", "Kucie" },
            { "Text.Robinson.Favour.Cutting", "Cięcie" },
            { "Text.Robinson.Chipping.Title0", "Poradnik Kucia" },
            { "Text.Robinson.Chipping.Title1", "Poradnik Kucia Cz.1" },
            { "Text.Robinson.Chipping.Desc", "Najpierw chcę upewnić się, że potrafisz wykonywać instrukcje… Zaznaczyłem lokalizację na Twojej mapie, notatkę, którą umieściłem na ścianie do przeczytania. Podążaj zieloną strzałką do notatki, przeczytaj ją, a potem wróć do mnie." },
            { "Text.Robinson.Chipping.FirstObjective", "Przejdź przez Fioletowe drzwi i przeczytaj notatkę Robinsona" },
            { "Text.Robinson.Chipping.FirstObjectiveAlt", "Przeczytaj notatkę pozostawioną przez Robinsona" },
            { "Text.Robinson.Chipping.SecondObjective", "Wróć do Robinsona" },
            { "Text.Robinson.Chipping.Title2", "Poradnik Kucia Cz.2" },
            { "Text.Robinson.Chipping.Part2.Desc", "Rączka narzędzia to niezbędny element wyposażenia, można ją użyć do stworzenia łopat i kilofów.\\n\\nBędziesz musiał przyzwyczaić się do rabowania biurek w poszukiwaniu składników do craftingu. Znajdź składniki, stwórz rączkę narzędzia, a potem wróć do mnie." },
            { "Text.Robinson.Chipping.ThirdObjective", "Stwórz $ItemToCraft dla $QuestGiver" },
            { "Text.Robinson.Chipping.FourthObjective", "Naciśnij [X], aby otworzyć menu craftingu i stwórz $ItemToCraft dla $QuestGiver" },
            { "Text.Robinson.Chipping.Title3", "Poradnik Kucia Cz.3" },
            { "Text.Robinson.Chipping.Part3.Desc", "Możesz połączyć rączkę narzędzia z łomem i taśmą, aby stworzyć najprostszy kilof, Łamliwy Kilof. Ukryłem też dodatkowe składniki do zebrania…\\n\\nGdy zdobędziesz Łamliwy Kilof, zaktualizuję mapę z idealnym miejscem na rozpoczęcie kucia!" },
            { "Text.Robinson.Chipping.FifthObjective", "Stwórz $ItemToCraft1" },
            { "Text.Robinson.Chipping.SixthObjective", "Kuj ścianę docelową" },
            { "Text.Robinson.Chipping.SeventhObjective", "Wróć do Robinsona" },
            { "Text.Robinson.Chipping.Title4", "Poradnik Kucia Cz.4" },
            { "Text.Robinson.Chipping.Part4.Desc", "Narzędzia można ulepszać, dodając dodatkowe komponenty, aby podnieść ich jakość z Łamliwego, do Lekkiego, a potem do Solidnego. Pamiętaj, aby sprawdzić menu craftingu, aby zobaczyć, jak ulepszyć narzędzie! \\n\\nInne przedmioty mogą być używane do kucia, np. zwykły śrubokręt. Umieściłem jeden w moim biurku do zebrania, a potem będziesz mógł przebić się przez ścianę. Powodzenia na zewnątrz!" },
            { "Text.Robinson.Chipping.EighthObjective", "Użyj śrubokręta, aby przebić ścianę docelową" },
            { "Text.Robinson.Chipping.NinthObjective", "Ucieczka!" },
            { "Text.Robinson.Chipping.TenthObjective", "Zbierz $ItemToGet z biurka Robinsona" },
            { "Text.Robinson.Cutting.Title0", "Poradnik Cięcia" },
            { "Text.Robinson.Cutting.Title1", "Poradnik Cięcia Cz.1" },
            { "Text.Robinson.Cutting.Desc", "Zanim przystąpimy do prawdziwej pracy, chcę upewnić się, że mogę Ci zaufać. Zaznaczyłem lokalizację na mapie, notatkę do przeczytania. Podążaj zieloną strzałką, przeczytaj ją, a potem wróć do mnie." },
            { "Text.Robinson.Cutting.FirstObjective", "Przejdź przez Fioletowe drzwi i przeczytaj notatkę Robinsona" },
            { "Text.Robinson.Cutting.FirstObjectiveAlt", "Przeczytaj notatkę pozostawioną przez Robinsona" },
            { "Text.Robinson.Cutting.SecondObjective", "Wróć do Robinsona" },
            { "Text.Robinson.Cutting.Title2", "Poradnik Cięcia Cz.2" },
            { "Text.Robinson.Cutting.Part2.Desc", "Ogrodzenia są zwykle bardzo widoczne dla strażniczych wież. Warto ciąć w nocy, pod osłoną ciemności. Strażnicy zauważą, że nie ma Cię w celi, więc stworzenie Poduszki w Łóżku to dobra ostrożność. \\n\\nNa mapie ukryłem składniki do stworzenia Poduszki w Łóżku. Gdy ją stworzysz, umieść w łóżku…" },
            { "Text.Robinson.Cutting.ThirdObjective", "Naciśnij [X], aby otworzyć menu craftingu i stwórz $ItemToCraft dla $QuestGiver" },
            { "Text.Robinson.Cutting.FourthObjective", "Umieść Poduszkę w Łóżku w swoim łóżku" },
            { "Text.Robinson.Cutting.Title3", "Poradnik Cięcia Cz.3" },
            { "Text.Robinson.Cutting.Part3.Desc", "To zmyli strażników! Czas stworzyć Łamliwe Nożyce. Narzędzia można ulepszać, dodając komponenty, aby podnieść ich jakość z Łamliwego, do Lekkiego, a potem do Solidnego. Każde ulepszenie poprawia skuteczność i trwałość narzędzia." },
            { "Text.Robinson.Cutting.FifthObjective", "Stwórz $ItemToCraft1" },
            { "Text.Robinson.Cutting.SixthObjective", "Wróć do Robinsona" },
            { "Text.Robinson.Cutting.Title4", "Poradnik Cięcia Cz.4" },
            { "Text.Robinson.Cutting.Part4.Desc", "Będziesz musiał poczekać aż zgasną światła, aby wykonać tę ucieczkę, ale MUSISZ pamiętać, aby najpierw udać się na Wieczorną Apelację! Zaktualizuję mapę i dziennik, gdy nadejdzie czas realizacji planu.\\n\\nPo prostu podążaj za moimi instrukcjami, a wkrótce będziesz na wolności!... " },
            { "Text.Robinson.Cutting.SeventhObjective", "Poczekaj na Wieczorną Apelację na dalsze instrukcje" },
            { "Text.Robinson.Cutting.EighthObjective", "Weź udział w Wieczornej Apelacji" },
            { "Text.Robinson.Cutting.NinthObjective", "Zbierz $ItemToGet z biurka Robinsona" },
            { "Text.Robinson.Cutting.TenthObjective", "Udaj się do ogrodzenia perymetru" },
            { "Text.Robinson.Cutting.EleventhObjective", "Poczekaj na zakończenie Apelacji…" },
            { "Text.Robinson.Cutting.TwelfthObjective", "Poczekaj na zakończenie Powrotu do Celi…" },
            { "Text.Robinson.Cutting.ThirtheenthObjective", "Przetnij docelowe ogrodzenie" },
            { "Text.Robinson.Cutting.FourteenthObjective", "Ucieczka!" },
            { "Text.Robinson.Cutting.FifthteenthObjective", "Dostarcz $ItemToCraft1 do $DeliverTo1" },
            { "Text.Robinson.Digging.Title0", "Poradnik Kopania" },
            { "Text.Robinson.Digging.Title1", "Poradnik Kopania Cz.1" },
            { "Text.Robinson.Digging.Desc", "Zanim zabrudzisz sobie ręce błotem, mam dla Ciebie szybkie zadanie… Zaznaczyłem lokalizację na mapie, notatkę w pokoju do przeczytania. Podążaj zieloną strzałką do notatki, przeczytaj ją, a potem wróć do mnie." },
            { "Text.Robinson.Digging.FirstObjective", "Przejdź przez Fioletowe drzwi i przeczytaj notatkę Robinsona" },
            { "Text.Robinson.Digging.FirstObjectiveAlt", "Przeczytaj notatkę pozostawioną przez Robinsona" },
            { "Text.Robinson.Digging.SecondObjective", "Wróć do Robinsona" },
            { "Text.Robinson.Digging.Title2", "Poradnik Kopania Cz.2" },
            { "Text.Robinson.Digging.Part2.Desc", "Kopanie tuneli powoduje powstawanie dużej ilości ziemi… lub jak powiedzieliby strażnicy – ‘dowodów’. Jeśli zamierzasz kopać tunele, najpierw musisz wiedzieć, jak ukryć powstałą ziemię!\\n\\nW moim biurku jest trochę ziemi, proszę ją zutylizować. Spłukanie w toalecie jest bezpiecznym sposobem." },
            { "Text.Robinson.Digging.ThirdObjective", "Zniszcz $QuestGiver's $ItemToDestroy" },
            { "Text.Robinson.Digging.Title3", "Poradnik Kopania Cz.3" },
            { "Text.Robinson.Digging.Part3.Desc", "Kolejne zadanie to stworzenie niezbędnego elementu… rączki narzędzia. Można ją użyć do wykonania łopat i kilofów.\\n\\nBędziesz musiał przyzwyczaić się do przeszukiwania biurek w poszukiwaniu składników do craftingu. Znajdź składniki, stwórz rączkę narzędzia, a potem wróć do mnie." },
            { "Text.Robinson.Digging.FourthObjective", "Naciśnij [X], aby otworzyć menu craftingu i stwórz $ItemToCraft dla $QuestGiver" },
            { "Text.Robinson.Digging.Title4", "Poradnik Kopania Cz.4" },
            { "Text.Robinson.Digging.Part4.Desc", "Świetna robota! Teraz zamienisz rączkę narzędzia w najprostszy łopatkę – Łamliwą Łopatę. Ponownie umieściłem składniki w biurkach, które musisz znaleźć! Gdy zdobędziesz Łamliwą Łopatę, czas zacząć kopać!" },
            { "Text.Robinson.Digging.FifthObjective", "Stwórz $ItemToCraft1" },
            { "Text.Robinson.Digging.SixthObjective", "Wykop dziurę na docelowej kafelce" },
            { "Text.Robinson.Digging.SeventhObjective", "Wróć do Robinsona" },
            { "Text.Robinson.Digging.Title5", "Poradnik Kopania Cz.5" },
            { "Text.Robinson.Digging.Part5.Desc", "Narzędzia można wzmacniać, dodając dodatkowe komponenty, aby podnieść ich jakość z Łamliwego, do Lekkiego, a następnie do Solidnego. Każde ulepszenie poprawia skuteczność i trwałość narzędzia. Pamiętaj, aby sprawdzić menu craftingu! \\n\\nW moim biurku znajduje się Solidna Łopata, zabierz ją i kontynuuj kopanie tunelu!" },
            { "Text.Robinson.Digging.EighthObjective", "Wykop dziurę na docelowej kafelce" },
            { "Text.Robinson.Digging.NinthObjective", "Kontynuuj kopanie tunelu…" },
            { "Text.Robinson.Digging.TenthObjective", "Wróć do Robinsona" },
            { "Text.Robinson.Digging.Title6", "Poradnik Kopania Cz.6" },
            { "Text.Robinson.Digging.Part6.Desc", "Wygląda na to, że dotarłeś do limitu tunelu bez podpór… będziesz musiał stworzyć Belkę Podporową, aby wesprzeć tunel i móc kopać dalej. Im dłuższy tunel, tym więcej belek będziesz potrzebować!\\n\\nRozłożyłem trochę drewna, abyś zrobił Belkę Podporową. Gdy ją zdobędziesz, umieść ją w tunelu!" },
            { "Text.Robinson.Digging.EleventhObjective", "Stwórz $ItemToCraft2" },
            { "Text.Robinson.Digging.TwelfthObjective", "Umieść Belkę Podporową na docelowej kafelce" },
            { "Text.Robinson.Digging.ThirteenthObjective", "Wróć do Robinsona" },
            { "Text.Robinson.Digging.Title7", "Poradnik Kopania Cz.7" },
            { "Text.Robinson.Digging.Part7.Desc", "Wygląda na to, że opanowałeś podstawy kopania… bez żartu… Mam dla Ciebie jeszcze jedną Solidną Łopatę i Napój Energetyczny w moim biurku. \\n\\nTen Napój Energetyczny powinien dodać Ci energii, aby wykonać ostatni wysiłek i wydostać się stąd! Powodzenia!" },
            { "Text.Robinson.Digging.FourteenthObjective", "Kontynuuj kopanie tunelu…" },
            { "Text.Robinson.Digging.FifteenthObjective", "Kop na docelowej kafelce" },
            { "Text.Robinson.Digging.SixteenthObjective", "Ucieczka!" },
            { "Text.Robinson.Digging.SeventeenthObjective", "Zbierz $ItemToGet z biurka Robinsona" },
            { "Text.Robinson.Digging.EighteenthObjective", "Zbierz Solidną Łopatę i Napój Energetyczny z biurka Robinsona" },
            { "Text.Robinson.Intro.Title1", "Oto dla Ciebie, panie Robinson" },
            { "Text.Robinson.Intro.Desc", "Więc… zostałem znów złapany… ale nie martw się, zawsze mam pomysły, jak uciec z takiego miejsca. \\n\\nMożesz używać telefonów publicznych, aby kupić wskazówki do unikalnych ucieczek w więzieniu, ale moją specjalnością są ucieczki z perymetru. Chcesz się nauczyć jak uciec? Po prostu powiedz mi, jaką metodą ucieczki jesteś zainteresowany…" },
            { "Text.Robinson.TalkTo.Objective", "Porozmawiaj z Robinsonem" },
        };
    }
}
